### ISSUE TITLE
[Feature Request] Add DNS CommType

### ISSUE THREAD

**Issue by CG-root** [cobbr/Covenant#100]
Hi there,
Is it possible to add DNS CommType?
Thanks

**Comment by cobbr** [comment]
@CG-root No plans to currently, maybe in the very distant future.

But I'd be happy to merge a PR 🙂

**Comment by cobbr** [comment]
@CG-root I've addressed this with v0.4 (f072ade)

While Covenant does not include a DnsListener out of the box, it does offer the tooling to build communication protocols w/ Listeners and C2Bridges
