### ISSUE TITLE
[Issue] "Edit" button doesn't let you change Grunt details

### ISSUE THREAD

**Issue by last-byte** [cobbr/Covenant#101]
I'm using Covenant as a C2 on Ubuntu Server. If you press the "edit" button while trying to change a grunt's details using the web interface nothing happens: the page refreshes and the details are not saved.

**Comment by cobbr** [comment]
Thanks for the heads up @last-byte!

Should be fixed in 111d03b64793f599d208e8a3ffeeb6a7dd77d38e
