### ISSUE TITLE
How to change certificate

### ISSUE THREAD

**Issue by Hach0u** [cobbr/Covenant#102]
Hi,
I tried to change Covenant certificate (as it seems Covenant is starting to be known by security systems :D ). This is what I've done:
1. Generate a new self-signed certificate
2. Created 2 files out of it (covenant-dev-private.pfx & covenant-dev-public.cer)
3. Copy in Covenant/Data/
4. Build and then start container as suggested in the read me

I have the following error:
> Error importing Covenant certificate.
Application startup exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Covenant.Program.<>c__DisplayClass1_0.<BuildWebHost>b__4(HttpsConnectionAdapterOptions httpsOptions) in /app/Covenant.cs:line 186
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOptions)
   at Covenant.Program.<>c__DisplayClass1_0.<BuildWebHost>b__3(ListenOptions listenOptions) in /app/Covenant.cs:line 169

I have not specified the password of the pfx file. Where can I do that ? I think it'll solve the issue.

Thanks a lot for the work already done !

**Comment by cobbr** [comment]
@Hach0u What exactly are you trying to accomplish?

Changing this certificate will change Covenant's `admin` certificate. This will not change the certificate used by an HTTP Listener.

I'd highly recommend to not expose Covenant's admin web gui to the internet.

**Comment by Hach0u** [comment]
@cobbr yes this is the admin interface certificate that I want to change, not the HTTP listener one.

**Comment by cobbr** [comment]
Okay! In that case, I believe that your certificate must **not** be password-protected.

If you need it to be password protected, you will need to make a source code change to provide it. We don't currently have a way to specify this in a friendly way.

**Comment by Hach0u** [comment]
@cobbr, thanks a lot !

For the record, I solved it by using the following commands:
cd Covenant/Data
openssl genrsa 4096 > private.pem
openssl req -x509 -new -key private.pem -out public.pem
openssl pkcs12 -export -in public.pem -inkey private.pem -out covenant-dev-private.pfx
openssl x509 -pubkey -outform der -in public.pem -out covenant-dev-public.cer
rm ./Data/public.pem
rm ./Data/private.pem

**Comment by cobbr** [comment]
Great! Glad you got it working @Hach0u 🙂
