### ISSUE TITLE
[Feature Request] Modify Kill Task to kill an arbitrary process

### ISSUE THREAD

**Issue by rasta-mouse** [cobbr/Covenant#104]
**Feature Request or Bug**
Feature Request

**Describe the feature request or bug**
I was thinking of adding a Task that would allow you to kill an arbitrary process on the host.  But the alias is taken up by the existing Task and I think it would just be a more elegant solution if it was all part of the same Task.

Usage could be:
- `Kill` (no params) kills the Grunt (same as the current behaviour)
- `Kill <pid>` kills the process of the specified PID

**Comment by cobbr** [comment]
Interesting. I might have to think about this. I think it could be confusing to have `Kill` do two very different things. Maybe we could rename the current `Kill` to `Exit` or something else.

**Comment by rasta-mouse** [comment]
In pretty sure Meterpreter behaves along the lines I described, so people may not find it that unusual. Though obviously happy to take your lead either way.

If you decide to keep the tasks separate, I can (attempt 😉) to PR the changes.  Given the way the Taskings work anyway, it’s probably also the easier route.

**Comment by cobbr** [comment]
Resolved in 74a015fc215c6f8e2c0754a9eb07074949401a12

Thanks @rasta-mouse !
