### ISSUE TITLE
[Bug| DOTNET version 2.0.9 not found 3.0.0 installed ERROR

### ISSUE THREAD

**Issue by daimalkogaz** [cobbr/Covenant#107]
With my luck again nothing works from the first try. When building the project it asks for an older version (2.0.9) of .NET yet I have the newest one installed (3.0) Is there a fix to this or should I start re-installing .NET packages? This has been done on a fresh OpenSUSE Leap 15.1 install:

`zoltar@linux-9bf4:~/Covenant/Covenant> dotnet build
It was not possible to find any compatible framework version
  The specified framework 'Microsoft.NETCore.App', version '2.0.9' was not found.
    - The following frameworks were found:
        3.0.0 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  
  You can resolve the problem by installing the specified framework and/or SDK.
  
  The .NET Core frameworks can be found at:
    - https://aka.ms/dotnet-download
/home/zoltar/.nuget/packages/microsoft.aspnetcore.razor.design/2.2.0/build/netstandard2.0/Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets(79,5): error : rzc discover exited with code 150. [/home/zoltar/Covenant/Covenant/Covenant.csproj]

Build FAILED.

/home/zoltar/.nuget/packages/microsoft.aspnetcore.razor.design/2.2.0/build/netstandard2.0/Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets(79,5): error : rzc discover exited with code 150. [/home/zoltar/Covenant/Covenant/Covenant.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:03:34.11`

**Comment by cobbr** [comment]
Hey @daimalkogaz , you can just install the 2.2 version of the dotnet sdk found here: https://dotnet.microsoft.com/download/linux-package-manager/opensuse15/sdk-2.2.402

**Comment by daimalkogaz** [comment]
that was fast. thanks.

**Comment by cobbr** [comment]
No problem!
