### ISSUE TITLE
WmicLauncher instructions typo

### ISSUE THREAD

**Issue by x86party** [cobbr/Covenant#11]
Just a small thing but presumably: `wmic os get /format:"file.xls"` ought to read `wmic os get /format:"file.xsl"` ?

Affected line: https://github.com/cobbr/Covenant/blob/bd16ef0918c1d0b380e8235dd559c2d77fa1db9b/Covenant/Models/Launchers/WmicLauncher.cs#L24

**Comment by cobbr** [comment]
`xls` vs `xsl` gets me every time 🤦‍♂️ 

Thanks for the heads up @x86party , I'll get this fixed

**Comment by cobbr** [comment]
fixed this typo in 8534ad45231062cdf67d0b42655b919e8fbaa752

thanks @x86party
