### ISSUE TITLE
[Bug] InstallUtil Launcher with .NET Framework Version 4 does not work

### ISSUE THREAD

**Issue by NotoriousRebel** [cobbr/Covenant#110]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
When I try the InstallUtil launcher after placing the dll on their Desktop
I get this error.
`Exception occurred while initializing the installation:
System.BadImageFormatException: Could not load file or assembly 'file:///C:\Users\Administrator\Desktop\wow.dll' or one of its dependencies. The module was expected to contain an assembly manifest..`

**To Reproduce**
1. Go to Launchers
2. Click on InstallUtil
3. Set DotNetFrameworkVersion to Net40
4. Put dll file on Target System

**Expected behavior**
Should get beacon back with new grunt.

**Screenshots**
![image](https://user-images.githubusercontent.com/36310667/67610843-5a47f900-f763-11e9-9c2f-0df9b05a0908.png)

**Covenant Server Information:**
 - OS: Ubuntu 16.04.3 LTS
 - Docker or Native: Docker

**Browser Information:**
 - Chrome
 - Version 78.0.3904.70 (Official Build) (64-bit)

**Target Information (System that implant is running on):**
 - OS: Microsoft Windows Server 2019 Datacenter
 - Version 10.0.17763 N/A Build 17763

**Additional context**

**Comment by cobbr** [comment]
Thanks @NotoriousRebel , keep getting the InstallUtil output format wrong 🙂 

Should be fixed in c7eb9284ef5742c4bc6ef166b0b05d800843317f
