### ISSUE TITLE
[Bug] NullReferenceException on CreateListener View

### ISSUE THREAD

**Issue by emmasuki** [cobbr/Covenant#115]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
cannot create a new listener

**To Reproduce**
1. Go to Listener
2. Click on Create
3. See error
![ERROR_creating_listene](https://user-images.githubusercontent.com/57483641/68685330-43c6dd80-056a-11ea-86e9-3e11f3b8c536.png)

**Expected behavior**
Create a listener on osx

**Screenshots**
see additional context

**Covenant Server Information:**
 - OS: OSX 10.14
 - Docker or Native: [Native]

**Browser Information:**
 - Browser [Firefox / Chrome]
 - Version [latest]

**Target Information (System that implant is running on):**
 - OS: [na]
 - Version [na]

**Additional context**
dot net core for OSX from 'dotnet-sdk-2.2.402-osx-x64'
![netcoreversion](https://user-images.githubusercontent.com/57483641/68685535-90121d80-056a-11ea-9d94-ea276b156b2e.png)

the debugger catch the exception in this line of CreateBridgeListener.cshtml:
![exception_row](https://user-images.githubusercontent.com/57483641/68685843-06af1b00-056b-11ea-982f-b06aa546dc70.png)

removing the selected line fix the issue (as workaround) but the ip is not automatically filled

seems related  to this line of BridgeListener.cs:
![bridgelistener_suspected_row](https://user-images.githubusercontent.com/57483641/68685473-7cff4d80-056a-11ea-8be8-1e74bc41de63.png)

**Comment by scaughy** [comment]
Bug also replicated on Ubuntu 16.04 server host. Confirming that deleting the recommended line above resolved the issue.

**Comment by cobbr** [comment]
@emmasuki I think this should be fixed in the new version 79c45e7

Can you verify this problem is fixed for you?

**Comment by cobbr** [comment]
Closing for now, feel free to reopen if you continue to have problems.

**Comment by AyberkHalac** [comment]
cant create listener in kali 2021.2. When I press create it doesnt give me a listener + no exceptions
