### ISSUE TITLE
[Bug] Create 'empty' user cause unhandled exception

### ISSUE THREAD

**Issue by emmasuki** [cobbr/Covenant#116]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
Creating an user with all the fields empty cause unhandled exception

**To Reproduce**
1. Go to 'Users'
2. Click on 'Create'
3. See error

**Expected behavior**
an alert pointing mandatory field

**Screenshots**
![createuserbug](https://user-images.githubusercontent.com/57483641/68688496-1d577100-056f-11ea-9a7b-18d404d0f77e.png)

**Covenant Server Information:**
 - OS: [Windows/OSX/Ubuntu] (not OS related)
 - Docker or Native: [Native]

**Browser Information:**
 - Browser [Firefox]
 - Version [latest]

**Target Information (System that implant is running on):**
 - OS: [na]
 - Version [na]

**Comment by cobbr** [comment]
@emmasuki I think this should be fixed in the new version, can you verify this is working for you now?

**Comment by emmasuki** [comment]
@cobbr yes it's fixed, tested on latest covenant, it now display an alert about required fields
