### ISSUE TITLE
[Bug] Exception thrown when task is run with an optional option left as default

### ISSUE THREAD

**Issue by amohar** [cobbr/Covenant#117]
### Setup the Task
* Create a new Task through Web App UI (*NOT* as explained in the wiki, so no task file and no DbInitializer file updates)
* Add a first option called NotOptional and make sure the optional checkbox is not ticked
* Add a second option called Optional and make sure the optional checkbox is ticked
* Add the following simple code
```
public static class Task
{
	public static string Execute(string NotOptional, string Optional="Default")
	{
                return "Done.";
	}
}
```
### Run the grunt
* I manually turned off Windefender 
* I used a powershell launcher, copied the powershell part of the non-encoded launcher
* I executed it in a powershell window - this left the window open. This is important because here I got the exception output
### Run the task with both parameters - works
`OptionalOptionTest Test1 Test2` 
* this prints "Done." as expected
### Run the task with only one parameter - exception
`OptionalOptionTest Test1` 
* "Done." message is not printed
* this prints the following exception in the powershell window running the grunt on the target:
```
Loop Exception: System.Net.WebException The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at GruntExecutor.HttpMessenger.Read()
   at GruntExecutor.TaskingMessenger.ReadTaskingMessage()
   at GruntExecutor.Grunt.Execute(String CovenantURI, String CovenantCertHash, String GUID, Aes SessionKey)
```

The interesting thing is that other tasks with default values work just fine if I leave out the optional parameters. Also all other tasks run after this produce the same exception effectively breaking the grunt.

## Covenant Server Information:
OS: Kali Linux
Docker or Native: Native

## Target Information (System that implant is running on):
OS: Windows 10 Pro

Let me know if other info is needed.

**Comment by manasmbellani** [comment]
I noticed this exact same behavior as well. I had a single argument which was "Optional" and set to an empty value. 

When I do not set any value for it, I get 404 Not Found error similar to the finding from `amohar` above. As a workaround, I am running a pre-processor bash script to generate my task which populates the optional value in a variable via `string variable = $variable`.

**Comment by cobbr** [comment]
Hey @amohar and @manasmbellani, thanks for the heads up on this, and sorry it took me so long to get back with you.

This should now be fixed. Closing for now. If you continue to have issues with the latest code, we can reopen.
