### ISSUE TITLE
[Feature Request] Don't update Activation time

### ISSUE THREAD

**Issue by C-Sto** [cobbr/Covenant#119]
**Feature Request or Bug**
Feature Request

**Describe the feature request or bug**
Currently, a grunt that has become inactive will have the 'activation time' value updated when it becomes active again. This overwrites the initial checkin time, which might be important for reporting purposes.

**To Reproduce**
1. Run grunt on host
2. Observe activation time
3. Disconnect host from internet/network long enough for grunt to become inactive 
4. Connect host again
5. Observe updated activation time

**Expected behavior**
Initial activation time should be persisted somewhere.

**Screenshots**
N/A

**Covenant Server Information:**
 - OS: Ubuntu
 - Docker or Native: Native

**Browser Information:**
N/A

**Target Information (System that implant is running on):**
 - OS: Windows
 - Version: Any

**Additional context**
N/A

**Comment by cobbr** [comment]
Made this change in dev. Should be in master soon.
