### ISSUE TITLE
CLI navigation across menus

### ISSUE THREAD

**Issue by iSteal** [cobbr/Covenant#12]
It'll be nice if we could navigate to any of the main menu options while in a particular menu, such as "Listeners." For example, if I just started a new Listener and I want to start a launcher, I should be able to immediately jump to the launcher menu by typing "launcher" rather than having to go back and then type launcher.

**Comment by cobbr** [comment]
I like this idea, I'll try to add it. Thanks @iSteal!

**Comment by cobbr** [comment]
Fixed w/ the new web interface 🙂
