### ISSUE TITLE
[Bug] Ability to add multiple connection addresses in one listener

### ISSUE THREAD

**Issue by S33ker-star** [cobbr/Covenant#122]
Feature Request 

It would be great to have the ability to add multiple connect addresses for a single listener. The grunt could randomly connect to one of the listed connect addresses. When this address is burnt, it will connect to one of the remaining addresses.

The platform allows you to add more than one connect address but only saves ones. I got a bit excited when I saw that it allows more than one.

Feature would be cool to have. Its coming in CS....#justsaying

**Comment by rasta-mouse** [comment]
I think this should be a bug report, not a feature request.

As far as I understand, each ConnectAddress should be added to the Grunt which then iterates through each one.  However, it seems only the first address is being added to the Grunt.

![image](https://user-images.githubusercontent.com/7346521/69626458-9b704900-1040-11ea-8332-d5fcee6a28e0.png)
--
![image](https://user-images.githubusercontent.com/7346521/69626531-b9d64480-1040-11ea-955b-df5812a666e7.png)
--
![image](https://user-images.githubusercontent.com/7346521/69626780-408b2180-1041-11ea-86e2-4a37f03e1365.png)

**Comment by cobbr** [comment]
Confirmed as a bug. This should be the way it already functions @S33ker-star

**Comment by cobbr** [comment]
@S33ker-star  I think this should be fixed in the new version 79c45e7

Can you verify this problem is fixed for you?

**Comment by cobbr** [comment]
Closing for now, feel free to reopen if you continue to have problems.
