### ISSUE TITLE
[Bug] Loading SharpSploit and SharpUp generated "Syntax Tree already Present" Error

### ISSUE THREAD

**Issue by manasmbellani** [cobbr/Covenant#124]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
Loading SharpSploit and Sharpup Reference Libraries in the same custom task generates an error: "Syntax Tree already Present"

**To Reproduce**
1. Create a new task called "MyTask" with "SharpUp" and "Sharpsploit" reference libraries
2. Add the attached code below to the custom task - this is just some test code but the issue is likely to occur with any other code too.
```


using System;

using System.IO;

using System.Linq;

using SharpUp;

using SharpSploit;

public static class Task

{

    public static bool shouldExecModule(string userInput, string moduleId) {

    // Function to validate whether the module should be executed or not...

        return userInput.Contains("all") || userInput.Contains(moduleId);

    }   

    public static string Execute()

    {

        string output = "";

        string command = "";

        string serverip = "";

        string modulesToExec= "sharpup";

        string moduleId = "";

        string title = "";

        try

        {             

            moduleId = "sharpup";

            title = "Running SharpUp: Privilege Escalation Checks";

            if (shouldExecModule(modulesToExec, moduleId)) {

                Console.WriteLine("[*] " + title);

                Program.PrivescChecks(true);

            }

        }

        catch (Exception e) { output += e.GetType().FullName + ": " + e.Message + Environment.NewLine + e.StackTrace; }

        return output;

    }

}
```
3. Go to a grunt and type in the task name `MyTask`
4. See error "Syntax Tree Already Found" in Interact tab.

**Expected behavior**
The task should work and SharpUp must execute when `MyTask` is launched

**Screenshots**
![Screenshot from 2019-11-28 01-46-39](https://user-images.githubusercontent.com/2260634/69733418-67507180-1181-11ea-9a7c-0e6f028ccf31.png)

**Covenant Server Information:**
 - OS: Kali Linux Rolling
 - Docker or Native: Docker

**Browser Information:**
 - Browser Firefox 
 - Version 60.6.3esr

**Target Information (System that implant is running on):**
 - OS: Windows 7

**Comment by cobbr** [comment]
I realize it's been a very long time since you file the issue @manasmbellani , but thanks for catching this. It's been fixed in the dev branch.
