### ISSUE TITLE
[Bug] Powershell or MSBuild launcher generation ignores user supplied fields

### ISSUE THREAD

**Issue by emmasuki** [cobbr/Covenant#125]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
some Launcher 'views' seems to not care about user edit.

**To Reproduce (Powershell):**
1. Go to Launchers
2. Click on Powershell
3. Edit ParameterString
4. Click on Generate
5. See both 'Launcher' and 'EncodedLauncher': don't contain user input.

**To Reproduce (MSBuild)**
1. Go to Launchers
2. Click on MSBuild
3. Edit TargetName and/or Taskname
4. Click on Generate
5. See xml file: doesn't contain user input.

**Expected behavior**
Click on generate should consider input field edit.

**Screenshots**
![powershell_bug_1](https://user-images.githubusercontent.com/57483641/69822739-67935000-1207-11ea-840b-c05db759bf13.png)

and

![msbuild_bug_crop](https://user-images.githubusercontent.com/57483641/69822751-6cf09a80-1207-11ea-8768-5bae9e768c92.png)

**Covenant Server Information:**
 - OS: WINDOWS
 - Docker or Native: [Native]

**Browser Information:**
 - Browser [Firefox]
 - Version [Latest]

**Additional context**
May Other launcher type could be affected too

**Comment by cobbr** [comment]
Thanks @emmasuki, I believe this should now be fixed.

Closing for now. If you continue to have issues with the latest code, we can reopen.
