### ISSUE TITLE
[Feature Request] Add additional libraries/references to an ImplantTemplate

### ISSUE THREAD

**Issue by rasta-mouse** [cobbr/Covenant#128]
**Feature Request or Bug**
Feature Request

**Describe the feature request or bug**
The compiler will not currently allow the inclusion of additional libraries within an ImplantTemplate.

My use case was to include a reference to `System.ServiceProcess`, to create a Service Binary capable of being used with PsExec.

Of course there are lots of other "useful" possibilities such as UnmanagedExports, ConfuserEx / Obfuscar and more, to create more exoteric templates.

**Comment by checkymander** [comment]
Seconding this for getting a working demo of Coresploit for use with a Cross-Platform grunt.

**Comment by cobbr** [comment]
Feature has been added. Changes currently in dev branch.

@checkymander Unfortunately, for now, ReferenceSourceLibraries/ReferenceAssemblies/EmbeddResources are only supported on .NET Framework, not .NET core. Can work on that eventually.
