### ISSUE TITLE
[Bug] Using mimikarz kills grunt

### ISSUE THREAD

**Issue by h0nus** [cobbr/Covenant#132]
**Feature Request or Bug**
It seems that using mimikatz kills the listener

**Describe the feature request or bug**
Using mimikatz with some dumping options (like sekurlsa::logonpassword and others) make the Grunt (tested only with HTTP one) crash/die.
Once thing i've noticed is that on normal Windows 10 it works (elvated), but on Windows Server 20XX it doesn't and crashes.
Note that if i wrote a command in a wrong way, the task became complete and i have the output of mimikats.

**To Reproduce**
1) Getting a new Grunt (by GruntHTTP)
2) Interact with him
3) Run whoami (everything fine)
4) Run Mimikats sekurlsa:logonpasswords (or start it from tasks)
4) Grunt just dies (On own machine with powershell payload and windows 10, it works without problems)

**Expected behavior**
I would expect Mimikats to work and to have the output into the task window

**Screenshots**
1) Died grunts: ![img](https://imgur.com/CpCvNX4.png)
2) Grunt task tasked forever: ![img](https://imgur.com/bw5NMpx.png)
3) Grunt tasking: ![img](https://imgur.com/eRRcYU5.png)
4) Grunt output empty: ![img](https://imgur.com/V84qwT0.png)

**Covenant Server Information:**
 - OS: Vagrant with Ubuntu 19-04
 - Docker or Native: Native with dotnet core installed

**Browser Information:**
 - Browser: Chrome, from Windows 10 machine
 - Version: Latest

**Target Information (System that implant is running on):**
 - OS: Windows 2012 (Microsoft Windows NT 6.3.9600.0)

**Additional context**
Idk honestly, maybe we'll get more after.

**Comment by cobbr** [comment]
Sorry for the delay @h0nus , I'll try to test this out on a 2012 server soon.

**Comment by h0nus** [comment]
No problem, let me know! 
Also, awesome project!

**Comment by cobbr** [comment]
Unfortunately, I haven't been able to reproduce this issue. I didn't have a Windows 2012 server handy, but tested on 2016 and 2008. Were you experiencing this issue on those OS as well?

**Comment by h0nus** [comment]
Hi.
Nope, I haven't tested on those version, only on 2012.
But this days i'll take a look.

**Comment by cobbr** [comment]
Closing for now, haven't been able to reproduce. If you continue to run into this issue, let me know and we can reopen.
