### ISSUE TITLE
[BUG] Can't connect from grunt

### ISSUE THREAD

**Issue by ioscanner** [cobbr/Covenant#133]
Bug

Can't get grunt to connect.  Even with normal http no cert enabled.  It give an SSL error:

warn: Microsoft.EntityFrameworkCore.Query[10103]
      Query: '(from HttpProfile <generated>_1 in DbSet<HttpProfile> select [<generated>_1]).First()' uses First/FirstOrDefault/Last/LastOrDefault operation without OrderBy and filter which may lead to unpredictable results.
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLSUIDTRC1M3", Request id "0HLSUIDTRC1M3:00000003": An unhandled exception was thrown by the application.
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.

**To Reproduce**
1. Go to create http listener with SSL off
2. Click on Grunt create with Cert off
3. Try to use on Windows machine with everything turned off
4. throws error.

Covenant version: latest as of today.  I even deleted and pulled source and tried native and with docker. Both with the same issue.
OS: Ubuntu 19.10
Browser: chrome, firefox and safari
Target: windows 10 everything disabled.  My powershell code works fine from empire and other C2 servers.

**Comment by cobbr** [comment]
Hey @ioscanner, I'm a little confused by the output you are showing. Can you share a screenshot of any errors the Grunt is throwing? (i.e. not server errors)

**Comment by cobbr** [comment]
@ioscanner bump. Let me know if you have any more details.

**Comment by ioscanner** [comment]
I apologize  I forgot all bout this and got tied up.

It doesn't throw any errors.  It can see the connection hit this box, but it just doesn't connect.  I will update and try it again just to be sure.

**Comment by cobbr** [comment]
Closing due to lack of detail.
