### ISSUE TITLE
[Bug] Compilation Errors

### ISSUE THREAD

**Issue by sandwich-destroyer** [cobbr/Covenant#135]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
Unable to execute any commands on a grunt. Sample error output below:
```


[01/24/2020 15:01:46 UTC] Command aborted

(operator) > ShellCmd dir

CompilerException: CompilationErrors: 
warning CS8021: No value for RuntimeMetadataVersion found. No assembly containing System.Object was found nor was a value for RuntimeMetadataVersion specified through options.
(2,21): error CS0518: Predefined type 'System.Object' is not defined or imported
(4,34): error CS0518: Predefined type 'System.String' is not defined or imported
(4,19): error CS0518: Predefined type 'System.String' is not defined or imported
(8,20): error CS0518: Predefined type 'System.Object' is not defined or imported
(8,20): error CS0103: The name 'Shell' does not exist in the current context
(10,16): error CS0518: Predefined type 'System.Object' is not defined or imported
(10,16): error CS0246: The type or namespace name 'Exception' could not be found (are you missing a using directive or an assembly reference?)
(10,61): error CS0518: Predefined type 'System.String' is not defined or imported
(10,80): error CS0518: Predefined type 'System.Object' is not defined or imported
(10,80): error CS0103: The name 'Environment' does not exist in the current context

[01/24/2020 15:07:45 UTC] Command aborted

(operator) > LogonPasswords

CompilerException: CompilationErrors: 
warning CS8021: No value for RuntimeMetadataVersion found. No assembly containing System.Object was found nor was a value for RuntimeMetadataVersion specified through options.
(2,21): error CS0518: Predefined type 'System.Object' is not defined or imported
(4,19): error CS0518: Predefined type 'System.String' is not defined or imported
(8,20): error CS0518: Predefined type 'System.Object' is not defined or imported
(8,20): error CS0103: The name 'Mimikatz' does not exist in the current context
(10,16): error CS0518: Predefined type 'System.Object' is not defined or imported
(10,16): error CS0246: The type or namespace name 'Exception' could not be found (are you missing a using directive or an assembly reference?)
(10,61): error CS0518: Predefined type 'System.String' is not defined or imported
(10,80): error CS0518: Predefined type 'System.Object' is not defined or imported
(10,80): error CS0103: The name 'Environment' does not exist in the current context

```

**To Reproduce**
1. Go to Grunts
2. Click on Interact
3. Type command

**Expected behavior**

**Screenshots**

**Covenant Server Information:**
 - OS: Windows 10 Enterprise 1903
 - Docker or Native: Docker

**Browser Information:**
 - Browser FireFox
 - Version 72.0.2 (64-bit)

**Target Information (System that implant is running on):**
 - OS: Windows 10 Enterprise 1903

**Additional context**

**Comment by cobbr** [comment]
Hey @sandwich-destroyer, looks like something went wrong on Installation. Be sure to follow the installation instructions precisely! https://github.com/cobbr/Covenant/wiki/Installation-And-Startup

I've noticed a common issue with Docker users is not specifying the correct path during this instruction: `docker run -it -p 7443:7443 -p 80:80 -p 443:443 --name covenant -v </absolute/path/to/Covenant/Covenant/Data>:/app/Data covenant`

Be sure you are specifying the full, correct path to your own Data folder.

**Comment by cobbr** [comment]
Can you try again and confirm that you have followed the instructions precisely. And if the issue continues, can you share a log of the exact instructions you use?

**Comment by sandwich-destroyer** [comment]
I am looking into it, will provide logs soon. Restarting from scratch.

**Comment by sandwich-destroyer** [comment]
Thanks for your help, turns out Windows Defender likes to turn itself back on after you disable it (even with Tamper Protection off).. Certain files were being cleaned off the system </3 . I had to make a change in the registry. [instructions on tenforums](https://www.tenforums.com/tutorials/3569-turn-off-windows-defender-real-time-protection-windows-10-a.html)
