### ISSUE TITLE
[Bug] Mimikatz parsing/output errors

### ISSUE THREAD

**Issue by asaurusrex** [cobbr/Covenant#139]
**Feature Request or Bug**
Output error mimikatz

**Describe the feature request or bug**
When trying to use mimikatz dpapi features, having problems getting any output, even when using the Task and quoting Mimikatz as suggested.

**To Reproduce**
1. Go to working Grunt
2. Click on 'Task' (note: this also does not work from Interact mode)
3. Set Task to Mimikatz
4. Command: "dpapi::cred /in:<your file here>"
4. See error - no output.

**Expected behavior**
On other C2 platforms and with Mimikatz, you would expect to see information regarding the "content" of a credential file

**Screenshots**

**Covenant Server Information:**
 - OS: Kali
 - Docker or Native: [e.g. Native] Dotnet Core

**Browser Information:**
 - Browser [e.g. chrome, safari] Firefox

**Target Information (System that implant is running on):**
 - OS: [e.g. iOS8.1] Windows 10 

**Additional context**

**Comment by cobbr** [comment]
Thanks @asaurusrex! I think this should be fixed in d315bbfa5ade82121cfc1cbeb4c2140789ec4d6e in dev branch, will be merged to master soon.

Would you mind verifying this is working as expected now? Thanks again.

**Comment by cobbr** [comment]
Closing for now, I think this should be fixed. If you continue to have problems, we can reopen.
