### ISSUE TITLE
Error: git submodules have not been initialized

### ISSUE THREAD

**Issue by Comanio00** [cobbr/Covenant#14]
Hi. 
I install according to the instructions. I use the command: git clone --recurse-submodules https://github.com/cobbr/Covenant. I do the assembly in docker, there is no error. After starting, I get an error message:

  Error: git submodules have not been initialized
Covenant's submodules can be cloned with: git clone --recurse-submodules https://github.com/cobbr/Covenant
Or initialized after cloning with: git submodule update --init --recursive.

Working system: Ubuntu 18.04, Docker 18.09.3, git 2.11.0.
 What could be the problem?

**Comment by cobbr** [comment]
Hey @Comanio00, I'm going to guess that you have not re-built Covenant since you pulled down the latest copy? We have to be sure that the container has the submodules, not just the docker host.

First, verify that you initialized the submodules properly:
```
$ ~/Covenant/Covenant > ls Data\Tasks\src\SharpSploit
CHANGELOG.md      README.md         SharpSploit.Tests
LICENSE           SharpSploit       SharpSploit.sln
$ ~/Covenant/Covenant > ls Data\Tasks\src\Rubeus
CHANGELOG.md LICENSE      README.md    Rubeus       Rubeus.sln
```

Now that we know you have the submodules, let's make sure the submodules are present *in the container*:
```
$ ~/Covenant/Covenant > docker exec -it covenant ls /app/Data/Tasks/src/SharpSploit
CHANGELOG.md  README.md    SharpSploit.Tests
LICENSE       SharpSploit  SharpSploit.sln
$ ~/Covenant/Covenant > docker exec -it covenant ls /app/Data/Tasks/src/Rubeus
CHANGELOG.md  LICENSE  README.md  Rubeus  Rubeus.sln
```

Assuming that your docker host has the submodules, but your container does not, then give this a try:
```
$ ~/Covenant/Covenant > docker stop covenant
$ ~/Covenant/Covenant > docker rm covenant
$ ~/Covenant/Covenant > docker build -t covenant .
$ ~/Covenant/Covenant > docker run -it -p 7443:7443 -p 80:80 -p 443:443 --name covenant -v /absolute/path/to/Covenant/Covenant/Data covenant --username AdminUser --computername 0.0.0.0
```

**Comment by cobbr** [comment]
Went ahead and added details on using docker's `-v` parameter to the README. This may make things easier for you, and I've been meaning to make this change anyway.

7bfb67bd416a223f3edab293a5cb8f3a8658f8b7

**Comment by dtrizna** [comment]
Had the same problem after last commit.
Acknowledge that volume mount with `-v` solves it.

**Comment by cobbr** [comment]
Turns out there was an issue with Docker not copying over the correct files that Covenant was checking for existence of the submodules.

Pushed out a fix df42fcd2f8c6432aeca779df2345c520f4a41e11
Let me know if you still have issues. You should be able to use the `-v` parameter or not.

**Comment by Comanio00** [comment]
Thank you.
This decision helped. Everything is working.

When starting Covenant a warning appears:

Password: *******
Hosting environment: Development
Content root path: /app
Now listening on: http://0.0.0.0:80
Using Covenant certificate with hash: 3F03FC3C0AB9E88467A3CB94E0D9DF6624AC02B3
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Overriding address(es) 'http://+:80'. Binding to endpoints defined in UseKestrel() instead.
Hosting environment: Development
Content root path: /app
Now listening on: https://0.0.0.0:7443
Application started. Press Ctrl+C to shut down.
warn: Microsoft.EntityFrameworkCore.Query[10103]
      Query: '(from HttpListener <generated>_1 in DbSet<HttpListener> select [<generated>_1]).FirstOrDefault()' uses First/FirstOrDefault/Last/LastOrDefault operation without OrderBy and filter which may lead to unpredictable results.

How can this affect the Covenant?

**Comment by cobbr** [comment]
Hey @Comanio00, that's expected. Maybe eventually it's something I should address.

**Comment by navemitt001** [comment]
Hi, I am facing this same problem today. I have checked the Data\Tasks\src\SharpSploit...this directory does not exist. The files are actually in /Data/ReferenceSourceLibraries.
Has there been a change to the directory structure since last time? Do i need to move the directories as per above?
Thanks
