### ISSUE TITLE
[Bug] Certificate Mismatch

### ISSUE THREAD

**Issue by yahia123321** [cobbr/Covenant#140]
**Covenant & Elite**
 Bug

**Certificate Mismatch when connecting Elite to Covenant**
I have just installed Covenant on my parrot vm both ways (via dotnet building & docker )
when i start my covenant server using dotnet run.. it starts normally generating a hash to authenticate 
but when starting Elite client using dotnet run ... when prompted :

Covenant ComputerName:{my eth0 ip}
Username:{previously registered username on fresh install} 
Password: ********
Covenant CertHash (Empty to trust all): DFA86EAE8DDC4AB107239FC78486A5E590BADAB0
[*] Logging in to Covenant...
[!] Covenant certificate does not match: DFA86EAE8DDC4AB107239FC78486A5E590BADAB0

Notes:
[=] tried the same thing with docker ... same error

[+] How to generate a new Admin User with a new password with a new Hash ??
**Covenant Server Information:**
 - OS: [linux x64 parrot security]
 
**Browser Information:**
 - Browser [chrome]
 - Version [Version 71.0.3578.98 (Official Build) (64-bit)]

**Comment by cobbr** [comment]
Hi @yahia123321, Elite has been deprecated. Have you tried the web GUI?

**Comment by yahia123321** [comment]
i am kinda lost in GUI , big fan of CMDline :)
can it be solved if i used earlier versions?? v0.1 or v0.2??

**Comment by cobbr** [comment]
Sorry 🙁  I don't have the bandwidth to support multiple clients at the moment.

Sure, earlier versions are compatible with Elite, but I wouldn't recommend it.

**Comment by yahia123321** [comment]
sorry for being pushy ..
tried installing v0.2 via docker build , but i get this error when running :
$docker run -it -p 7443:7443 -p 80:443 --name covenant -v $(pwd)/Data:/app/Data covenant --username MITO
Error: git submodules have not been initialized
Covenant's submodules can be cloned with: git clone --recurse-submodules https://github.com/cobbr/Covenant
Or initialized after cloning with: git submodule update --init --recursive
if i cloned the current repository with git clone to get the "submodules" it will run the current version not the older one :( 
is there  a way to download "submodules" manually and extract it to same directory ??
