### ISSUE TITLE
[Feature Request] Give management interface port in parameter

### ISSUE THREAD

**Issue by upils** [cobbr/Covenant#144]
**Description**
I would like to be able to set the listening port number for the management interface. Even if in docker we can use port translation, I am not using bridge networks but macvlan ones , thus I cannot bind another port to 7443.

Could it be possible to keep 7443 as a default but add a command line parameter to set it ?

**Expected behavior**
Launch Covenant like : `dotnet Covenant.dll --port 443`

**Comment by cobbr** [comment]
Hey @upils, apologies for missing this issue. This has been added for a little while now, so closing this issue.
