### ISSUE TITLE
[Bug] Creating ImplantTemplates doesn't see to work

### ISSUE THREAD

**Issue by import-au** [cobbr/Covenant#145]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
If you go to `Templates -> Create -> Fill out Fields`  then go to `Launchers - Binary`. The newly created Template is unavailable. Also, worth noting the `CompatibleListenerTypes` field does not save.

**To Reproduce**
1. Go to Templates
2. Click Create
3. Fill out the necessary fields
4. Go to Launchers
5. Click on Binary
6. Try to select the Template you just created.

**Expected behavior**
User would be able to select a newly created template in their Binary

**Screenshots**
![image](https://user-images.githubusercontent.com/30837560/75265034-28907e80-57a5-11ea-98cb-77c5d2fa7da9.png)
![image](https://user-images.githubusercontent.com/30837560/75265052-2fb78c80-57a5-11ea-8a6d-b3dd1bd4f9b9.png)

**Covenant Server Information:**
 - OS: Debian GNU/Linux 9 (stretch)
 - Docker or Native: docker

**Browser Information:**
 - Browser: Brave
 - Version:  Version 1.3.118 Chromium: 80.0.3987.116 (Official Build) (64-bit)

**Target Information (System that implant is running on):**
 - OS: N/A
 - Version: N/A

**Comment by kaluche** [comment]
Hello ! Exactly the same problem here, with native and docker. Can't use custom template, and CompatibleListenerTypes can't by modifiy.

**Comment by BinaryScary** [comment]
Same problem, profiles and templates don't seem to last after reboot either.

**Comment by cobbr** [comment]
@import-au  I think this should be fixed in the new version 79c45e7

Can you verify this problem is fixed for you?

**Comment by cobbr** [comment]
Closing for now, feel free to reopen if you continue to have problems.
