### ISSUE TITLE
[Bug| Can't Interact with a grunt through the api

### ISSUE THREAD

**Issue by ilan199929** [cobbr/Covenant#146]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
I'm trying to interact with a grunt through the Swagger UI but it returns an error
with status code  400

**To Reproduce**
1. Go to Swagger UI
2. Click on 'post /api/users/login' tab and login to get the api key and then authorize it
3. Scroll down to 'post /api/grunts/{id}/interact' tab and type the id and the command

**Expected behavior**
Send a command to the grunt through the api

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/43996999/75275112-aa67c280-580c-11ea-9eda-7a5b401d88b1.png)

![Untitled1](https://user-images.githubusercontent.com/43996999/75275139-b5baee00-580c-11ea-9ab4-b51075e9020b.png)

**Covenant Server Information:**
 - OS: Windows 10
 - Docker or Native: Native

**Browser Information:**
 - Browser : FireFox
 - Version: 73.0.1

**Target Information (System that implant is running on):**
 - OS: Windows
 - Version: 10

**Comment by ilan199929** [comment]
Help ? Someone ?

**Comment by cobbr** [comment]
Hey @ilan199929, were you able to figure this one out? Apologies for the delay, I just haven't had the time to take a look quite yet.
