### ISSUE TITLE
[Bug] Out Of Memory - GET request - GruntTasks & ReferenceSourceLibraries

### ISSUE THREAD

**Issue by SadProcessor** [cobbr/Covenant#147]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
Request hangs and run out of memory when trying to return full list of GruntTasks or ReferenceSourceLibraries (=no id specified)

**To Reproduce**
1- Issue a **GET** request to **/api/grunttasks** or **/api/referencesourcelibraries**
2- Wait for output

**Expected behavior**
Return json object containing all Tasks/RefSrclibs 

**Screenshots**
![image](https://user-images.githubusercontent.com/15706849/75347576-51963980-58a1-11ea-9e5b-4919c2d3c7aa.png)

**Covenant Server Information:**
 - OS: Win10
 - Docker or Native: Native

**Browser Information:**
 n/a

**Scripting Language:**
PowerShell

**Target Information (System that implant is running on):**
 n/a

**Additional context**
none

**Comment by cobbr** [comment]
Sorry for missing this issue earlier on @SadProcessor , I think this should be fixed now. Let me know if you are able to verify that this works now.

**Comment by cobbr** [comment]
Closing for now, can reopen if issues persist.
