### ISSUE TITLE
[Bug] fail: Microsoft.AspNetCore.SignalR.HubConnectionContext[5]   Failed connection handshake.

### ISSUE THREAD

**Issue by donjuanme** [cobbr/Covenant#150]
Overriding address(es) 'https://localhost:7443, http://localhost:7442'. Binding to endpoints defined in UseKestrel() instead.
Hosting environment: Development
Content root path: /root/Covenant/Covenant
Now listening on: https://0.0.0.0:7443
Application started. Press Ctrl+C to shut down.
Hosting environment: Development
Content root path: /root/Covenant/Covenant
Now listening on: http://0.0.0.0:80
fail: Microsoft.AspNetCore.SignalR.HubConnectionContext[5]
      Failed connection handshake.
fail: Microsoft.AspNetCore.SignalR.HubConnectionContext[5]
      Failed connection handshake.

NATIVE install on ubuntu 18

any idea why  get these errors ? does it affect anything ?

**Comment by fasetto** [comment]
I had same issue before @donjuanme I was using nginx with reverse proxy. 
If you are using reverse proxy you need to set some necessary headers.

```
        location / {
                proxy_pass         https://localhost:7443;
                proxy_http_version 1.1;
                proxy_set_header   Upgrade $http_upgrade;
                proxy_set_header   Connection $http_connection;
                proxy_set_header   Host $host;
                proxy_cache_bypass $http_upgrade;
                proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header   X-Forwarded-Host $host:$server_port;
                proxy_set_header   X-Forwarded-Proto $scheme;
        }
```

Not all of them but forward headers and the Connection header is needed for SignalR.

**Comment by cobbr** [comment]
@donjuanme Is this actually causing a breaking error or any issues for you? Otherwise, I think it'd be safe to ignore.

**Comment by cobbr** [comment]
Going to close this for now, let me know if you are able to provide more details and we can re-open.
