### ISSUE TITLE
[Bug] Assembly Task Parsing Woes

### ISSUE THREAD

**Issue by rasta-mouse** [cobbr/Covenant#152]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
The assembly task appears to have trouble parsing arguments that need a space in them.  Single and double quotes don't seem to help, escaped or not.

**To Reproduce**
1. Clone and compile [CsPosh](https://github.com/rasta-mouse/MiscTools/blob/master/CsPosh/Program.cs)
2. Run the Assembly task with a test command:
`Assembly CsPosh "-t dc-1 -c 'powershell -enc RwBlAHQALQBQAHIAbwBjAGUAcwBzAA=='"`

Where:

- `-t` is a target machine
- `-c` is the command to execute

**Expected behavior**
When executed from a cmd prompt, the results of the command are returned. E.g:
```
CsPosh.exe -t wkstn-2 -c "powershell -enc RwBlAHQALQBQAHIAbwBjAGUAcwBzAA=="

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    387      23    12812      23724              4840   1 ApplicationFrameHost
    143       9     1640       7400              4996   1 browser_broker
     74       5     2356       3780              5368   1 cmd
    256      13     7408      20120              3168   1 conhost
    147      10     4088       9160       0.02   5080   0 conhost
```

**Screenshots**
![image](https://user-images.githubusercontent.com/7346521/75725341-2e6fed80-5cd8-11ea-95e4-e46706490592.png)
![image](https://user-images.githubusercontent.com/7346521/75725440-61b27c80-5cd8-11ea-85c4-e5719b46a3e6.png)

The assembly is displaying the values of `-t` and `-c` that it has had passed to it.

**Covenant Server Information:**
 - OS: Kali Rolling 2020.1
 - Docker or Native: Native

**Browser Information:**
 - Browser: Google Chrome
 - Version: 80.0.3987.122 (Official Build) (64-bit)

**Target Information (System that implant is running on):**
 - OS: Windows 10 Enterprise
 - Version: 1909, Build 18363.657

**Additional context**

**Comment by s0lari** [comment]
This seems to be a similar issue to : https://github.com/cobbr/Covenant/issues/118 ?

**Comment by cobbr** [comment]
@rasta-mouse I've added logic to do command-line style parsing to Assembly tasks in 54c3dbc8e835dfac42a327a0e33fc8556c509b0c in the dev branch, will be merged to master soon. Thanks for all the details provided here, it helped out a lot.

Would you mind verifying this fixes the issue for you?

**Comment by rasta-mouse** [comment]
Hey @cobbr 

I repeated the same test and got the following output:

```
(rasta) > Assembly /assemblyname:"CsPosh" /parameters:"-t web-1 -c \"powershell -enc RwBlAHQALQBQAHIAbwBjAGUAcwBzAA==\""

Usage:
  -t, --target=VALUE         Target machine
  -c, --code=VALUE           Code to execute
  -e, --encoded              Indicates that provided code is base64 encoded
  -o, --outstring            Append Out-String to code
  -r, --redirect             Redirect stderr to stdout
  -d, --domain=VALUE         Domain for alternate credentials
  -u, --username=VALUE       Username for alternate credentials
  -p, --password=VALUE       Password for alternate credentials
  -h, -?, --help             Show Help
Cannot bundle unregistered option '-n'.
```

I'm not sure where `Cannot bundle unregistered option '-n'.` comes from, it's not from my assembly.

**Comment by cobbr** [comment]
argh looks like this is a difference between the Interact and Task tabs. From the Task tab:

```
(cobbr) > Assembly /assemblyname:"CsPosh.exe" /parameters:"-t web-1 -c 'powershell -enc RwBlAHQALQBQAHIAbwBjAGUAcwBzAA=='"


Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName                                                                                                                     
-------  ------    -----      -----     ------     --  -- -----------  
```

```

[6/13/2020 1:11:33 AM UTC] Assembly completed

(cobbr) > Assembly /assemblyname:"CsPosh.exe" /parameters:"-t web-1 -c \"powershell -enc RwBlAHQALQBQAHIAbwBjAGUAcwBzAA==\""


Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName                                                                                                                     
-------  ------    -----      -----     ------     --  -- -----------         
```

From the Interact tab:
```
(cobbr) > Assembly /assemblyname:"CsPosh.exe" /parameters:"-t dc-1 -c 'powershell -enc RwBlAHQALQBQAHIAbwBjAGUAcwBzAA=='"


Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName                                                                                                                     
-------  ------    -----      -----     ------     --  -- ----------- 
```

```
(cobbr) > Assembly /assemblyname:"CsPosh.exe" /parameters:"-t dc-1 -c \"powershell -enc RwBlAHQALQBQAHIAbwBjAGUAcwBzAA==\""

The string is missing the terminator: ".
```

I _think_ this issue is actually fixed, but issues #118 / #139 are still in the way of the last format.

**Comment by cobbr** [comment]
Ok, found the other bug! Should be fixed in 5d8a684d389872b0656d9f3e921ecff33b50d3ff in dev branch.

Here's the last result:

```
(cobbr) > Assembly /assemblyname:"CsPosh.exe" /parameters:"-t dc-1 -c \"powershell -enc RwBlAHQALQBQAHIAbwBjAGUAcwBzAA==\""


Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName                                                                                                                     
-------  ------    -----      -----     ------     --  -- ----------- 
```

Hopeful that this will fix #118 / #139 as well, but we will see. Let me know if you are able to verify @rasta-mouse , sorry for the repeated testing.

**Comment by rasta-mouse** [comment]
@cobbr can confirm this seems fixed now.  Happy to close the issue.

**Comment by cobbr** [comment]
Great! Thanks @rasta-mouse!
