### ISSUE TITLE
Facing error when using binary and powershell launchers

### ISSUE THREAD

**Issue by sohelahmed786** [cobbr/Covenant#157]
Hi team,
After generating binary and powershell launchers , when running on  windows 10 i'm getting a strange error i.e. Could not find a part of the path 'C:\en-us\test.html'. Please help to resolve this issue.
![error-covenant](https://user-images.githubusercontent.com/12643717/76827872-c677e600-6845-11ea-955b-edf1b811c09b.jpeg)

**Comment by tiag1855** [comment]
I got this error when I mistakenly tried sending my first Grunt callback through an SSH tunnel to the 7443 C2 port, instead of the bind port specified in the listener

**Comment by sohelahmed786** [comment]
http payload is working but not https .. so i guess the problem is with the certificate i generated. I used openssl to generate x.509 cert. is that okay?

**Comment by sohelahmed786** [comment]
Figured it out ... problem was with the configuration ..

**Comment by codan-bahrama** [comment]
Hi @sohelahmed786 

Which configuration caused the issue?
