### ISSUE TITLE
[Bug|Feature Request] How to pass arguments to mimikatz command

### ISSUE THREAD

**Issue by sohelahmed786** [cobbr/Covenant#160]
**Feature Request or Bug**
Getting error on running mimikatz.

>> mimikatz kerberos::golden /user:test123

mimikatz(powershell) # kerberos::golden
ERROR kuhl_m_kerberos_golden ; Missing user argument

mimikatz(powershell) # /user:test123
ERROR mimikatz_doLocal ; "/user:test123" command of "standard" module not found !

Module :	standard
Full name :	Standard module
Description :	Basic commands (does not require module name)

**Covenant Server Information:**
 - OS: kali linux 5.4.0-kali4-amd64
 - Native

**Browser Information:**
 - Firefox 60.8

**Target Information (System that implant is running on):**
 - OS: windows 10
 - Version 10.0.17763

**Additional context**

**Comment by rasta-mouse** [comment]
Use the Task GUI rather than the CLI and wrap the whole thing in double-quotes, like:
`"kerberos::golden /user:test123"`

**Comment by sohelahmed786** [comment]
Thanks, It worked :smiley: :smiley:
