### ISSUE TITLE
[Bug]Cannot create listener

### ISSUE THREAD

**Issue by Mursi-Alzanati** [cobbr/Covenant#167]
Bug

When I try to create a listener and change the listener name I prompted with error page, however if I keep it as is after I wiped the database it's work fine tile i try to change the name again.

1- Follow install instructions [here](https://github.com/cobbr/Covenant/wiki/Installation-And-Startup#option-1---dotnet-core)
2- Click on 'Listeners' in the left-hand sidebar
3- Click on 'Create' on the Listeners page
4- See error

**Expected behavior**
To create a listener 

**Screenshots**
![image](https://user-images.githubusercontent.com/64800151/81011366-80f89200-8e60-11ea-9c89-3e82551c0bac.png)

**Covenant Server Information:**
 - OS: kali 2020
 -Native

**Browser Information:**
 - chrome
 - Version 81.0.4044.129 (Official Build) (64-bit)

**Comment by rasta-mouse** [comment]
Seems like some incorrect data is being passed to that `new Uri()` call.  What are you actually providing as the Listen Address for your Listener?

**Comment by Mursi-Alzanati** [comment]
my Ip address of my VPNinterface

**Comment by cobbr** [comment]
@Mursi-Alzanati I think this should be fixed in the new version 79c45e77e95b4010f9676e34aacae3d18bbb5df0

Can you verify this problem is fixed for you?

**Comment by Mursi-Alzanati** [comment]
@cobbr Thanks for the nudge, so far for the works like a charm I will update as soon as I got an issue.

**Comment by cobbr** [comment]
Fantastic! If you have additional problems, we can reopen the issue. Closing for now.
