### ISSUE TITLE
[Bug] Selected enum values wiped when editing code fields in CreateImplantTemplate

### ISSUE THREAD

**Issue by 3xpl01tc0d3r** [cobbr/Covenant#171]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
While creating the new template and entering any value in the text field StagerCode or ExecutorCode the CompatibleListenerTypes & CompatibleDotNetVersions values get reset

**To Reproduce**
1. Go to Templates
2. Click on Create
3. Enter the required values in name & description field.
4. Select CommType(HTTP), ImplantDirection(Pull), CompatibleListenerTypes(HTTP), CompatibleDotNetVersions(Net35)
5. Enter value in StagerCode or ExecutorCode and we can see that the value of CompatibleListenerTypes & CompatibleDotNetVersions will get reset.

**Expected behavior**
The value of CompatibleListenerTypes & CompatibleDotNetVersions should not get reset.

**Screenshots**

**Covenant Server Information:**
 - OS: Windows 10
 - Docker or Native: Native

**Browser Information:**
 - Browser chrome
 - Version 83

**Target Information (System that implant is running on):**
 - OS: Windows 10
 - Version 1909

**Additional context**

**Comment by cobbr** [comment]
Thanks for the heads up @3xpl01tc0d3r. I believe this was fixed in v0.6, I just forgot to update this issue.

Closing for now. If you continue to have issues with the latest code, we can reopen.
