### ISSUE TITLE
Can not access web ui

### ISSUE THREAD

**Issue by onepad** [cobbr/Covenant#172]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
Can not access web ui

**To Reproduce**
dotnet build success
dotnet run showing this:
```
warn: Microsoft.EntityFrameworkCore.Model.Validation[10400]
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data, this mode should only be enabled during development.
Using Covenant certificate with hash: 2322E245C1E67F53F771C86B49B6E18294B589
```

**Covenant Server Information:**
 - OS: MacOS Catalina
 - Docker or Native: Native

**Additional context**
I grep listen port and see dotnet only listen on port 7443. Open localhost:7443 on browser but nothing happen.

**Comment by cobbr** [comment]
Hey @onepad , did you try navigating to `https://localhost:7443` in a browser?

If so, what browser are you using?

**Comment by onepad** [comment]
> Hey @onepad , did you try navigating to `https://localhost:7443` in a browser?
> 
> If so, what browser are you using?

Thank you very much! I forgot to use https.

**Comment by cobbr** [comment]
No problem, glad it's working!
