### ISSUE TITLE
[Bug] Listener not letting go of port after stopped/deleted

### ISSUE THREAD

**Issue by mubix** [cobbr/Covenant#176]
**Bug**

**Describe the feature request or bug**
When removing listeners on Linux server, the bindings / ports are not released when stopping / deleting listeners.

**To Reproduce**
1. Create a new HTTP listener and wait until it's marked as Active
2. Stop or Delete the HTTP listener
3. Attempt to start another listener on the same IP/port or just check netstat 

**Expected behavior**
Release of the binding

**Covenant Server Information:**
 - OS: Debian 9
 - Docker or Native: Native

Using latest from master.

**Comment by cobbr** [comment]
Fixed in b2896b85b55329e32788a17bd6dcef791a4b38c4 in dev branch, will be in master soon

Thanks @mubix!
