### ISSUE TITLE
[Bug] Net40 missing System.Configuration.Install.dll

### ISSUE THREAD

**Issue by mubix** [cobbr/Covenant#178]
After a successful build on Linux the following DLL is missing. It is present on net35 however
```
System.IO.FileNotFoundException: Could not find file '/opt/Covenant/Covenant/Data/AssemblyReferences/net40/System.Configuration.Install.dll'.
```

**Comment by cobbr** [comment]
Fixed in f9d71c61b508703440b3825b51a86992ef4532ad in dev branch, will be merged to master soon

Thanks again @mubix 🙂
