### ISSUE TITLE
[Bug] Error when editing Grunt Tasks with aliases.

### ISSUE THREAD

**Issue by kltdwd** [cobbr/Covenant#179]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
An exception occurs when a Grunt Task (with an alias) is viewed within the Web UI.

Error does not occur on Tasks without aliases.

**To Reproduce**
1. Browse to task with an alias, for example (List Directory) ./grunttask/edit/23

**Screenshots**
Example exception below.
![image](https://user-images.githubusercontent.com/4188978/83956810-d6f29800-a859-11ea-9f7f-794944458cf8.png)

**Covenant Server Information:**
 - OS: Windows 10
 - Docker or Native: Native

**Browser Information:**
 - Browser: Chrome
 - Version: 83

**Comment by cobbr** [comment]
Fixed by merging #183 into dev branch, will be in master soon

Thanks again @kltdwd 🙂
