### ISSUE TITLE
MakeToken functionality

### ISSUE THREAD

**Issue by attl4s** [cobbr/Covenant#18]
Hi Ryan, first want to thank you for these awesome tools you are creating :)

Wanted to report you something that I think is not working properly: the MakeToken Task (and probly all the token-related things).
First I've confirmed that the method is working properly on SharpSploit, as can be seen in this image:

![maketoken](https://user-images.githubusercontent.com/35996395/54865817-c1d03d00-4d6b-11e9-82cd-f853bd999efe.png)

But, when you make the token in a Covenant's session, it seems there is something failing in the logic of how the token is applied. From my little knowledge, I guess this is happening because whenever you use a new Task (Shell, Powershell, WmiGrunt...) they are executed in other "enviroment" where our new token is not present.

![maketoken2](https://user-images.githubusercontent.com/35996395/54865898-6acb6780-4d6d-11e9-92ff-a2963f63df5f.png)

Thank you very much!!

**Comment by cobbr** [comment]
Thanks for the report @attl4s. I've been digging into this, and it seems like you are right. I believe this is a result of tasks being processed in new process threads.

Haven't come up with a solution for this quite yet. In the meantime, here's a non-ideal solution:
`sharpshell using (Tokens t = new Tokens()) { t.MakeToken("username", "domain.local", "Password"); return String.Join(",", Directory.GetFiles("\\\\DC\\C$")); }`

**Comment by cobbr** [comment]
Fixed in 1d1daaad77786a9eb7fb8c7be0fc56f75b653421!

This ended up being a bit of work to fix, and I'm not sure we have a perfect solution yet, but I think it should work for now!
