### ISSUE TITLE
[Feature Request] Make Clean

### ISSUE THREAD

**Issue by mubix** [cobbr/Covenant#181]
It would be really nice to have a version of "make clean" or a way to clear out all built binaries, data from the database, and files / downloads. Using the framework for teaching, or taking classes, demos, or labs I find myself constantly deleting the Covenant directory, resetting to master/HEAD, re-pulling submodules, rebuilding. It would be really awesome if this was automated in some way.

**Comment by cobbr** [comment]
I think this is a good idea. I'd like to get an easy "Clear" button in the GUI to restore the state to a new Covenant instance.

For now, keep in mind that a `rm Data\covenant.db` should do the trick rather than messing with `git`.

**Comment by mpgn** [comment]
Result of `rm Data\covenant.db`

When reloading the webpage:

![image](https://user-images.githubusercontent.com/5891788/94317125-ea02b280-ff85-11ea-8076-e3812256a79b.png)

**Comment by cobbr** [comment]
Feature has been added. Changes currently in dev branch.
