### ISSUE TITLE
[Bug] Form Field Limitation set to 5000 Characters

### ISSUE THREAD

**Issue by forstern** [cobbr/Covenant#184]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
After generating a new PowerShell launcher, only 5000 characters get shown int the "Lauchner" filed. Therefore, the launcher does not work.

**To Reproduce**
1. Go to Launchers > PowerShell
2. Click on Generate
3. C&P the the launcher code from the filed "Launcher"
4. Only 5000 characters of the payload are shown / copied.

**Expected behavior**
The entire Payload is shown.

**Covenant Server Information:**
 - OS: Windows 10 Build 17763
 - Docker or Native: Native

**Browser Information:**
 - Browser Chrome
 - Version 83.0.4103.97

**Comment by WayneJLee** [comment]
Can confirm this issue exists. A workaround at the moment is to download the PS1 to get the full launcher and base64 encode it if you want.

**Comment by cobbr** [comment]
Should be fixed in 9905deef6317eb5066cfce555e130cc783ff0d39 in dev branch, will be merged to master soon.

Thanks for the heads up @forstern 🙂

**Comment by forstern** [comment]
ah I see, thanks for the reply :) I will update as soon as it is available.

**Comment by cobbr** [comment]
Hey @forstern , it's already available! Just switch to the dev branch: `git checkout dev` 🙂
