### ISSUE TITLE
[Bug|Feature Request] Short Description of Issue

### ISSUE THREAD

**Issue by naruto985** [cobbr/Covenant#186]
Covenant Stops - Overriding address(es) 'http://+:80'

Hi Ryan,
I have installing Covenant several times and every time I end up getting the same error "Overriding address(es) 'http://+:80'" My OS is Kali 2020. I have gone through the post related to this and have tried running the docker ending up with same error. 

**To Reproduce**
1. git clone --recurse-submodules https://github.com/cobbr/Covenant
2. cd Covenant/Covenant
3. docker build -t covenant .
4. docker run -it -p 7443:7443 -p 80:80 -p 443:443 --name covenant covenant --username AdminUser --computername 0.0.0.0
Post this command the output I get as below
 /opt/Covenant/Covenant#docker run -it -p 7443:7443 -p 80:80 -p 443:443 --name covenant covenant --username AdminUser --computername 0.0.0.0
Password: ********
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
warn: Microsoft.EntityFrameworkCore.Model.Validation[10400]
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data, this mode should only be enabled during development.
Using Covenant certificate with hash: 834265090DDFED8677E143C814E546A7226FC44B
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {35ba61b5-f7fa-4ade-a398-b1c57ac8c30b} may be persisted to storage in unencrypted form.
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Overriding address(es) 'http://+:80'. Binding to endpoints defined in UseKestrel() instead.

My System Information
 - OS:Kali Linux 2020
 - Docker version 19.03.9, build 9d988398e7
 
 Troubleshooting did till now 
1. Error launching Covenant #10 (Closed Issue)

Regards

**Comment by cobbr** [comment]
Hey @naruto985 , the "error" you are describing is just a warning message. This is not the cause of any issues you are having.

I'd highly recommend following the instructions here if you are going to use Docker: https://github.com/cobbr/Covenant/wiki/Installation-And-Startup

Notably, you are missing the `-v` parameter in your `docker run` command, which is going to be required.

**Comment by naruto985** [comment]
Hi Cobbr

Thanks for the quick response. I removed the entire docker and redid the entire steps along with -v. Attaching the Screenshot. I am still getting frozen at exact same point as mentioned above. 
Attaching the screenshots from my installation. 

![step1](https://user-images.githubusercontent.com/59492442/84154187-69767f80-aa84-11ea-8e30-2e489ffbd4be.png)
![step2](https://user-images.githubusercontent.com/59492442/84154191-6aa7ac80-aa84-11ea-8f04-df36dff921e5.png)
![step3](https://user-images.githubusercontent.com/59492442/84154193-6b404300-aa84-11ea-9e06-6de94d5b3e44.png)
![step4](https://user-images.githubusercontent.com/59492442/84154195-6bd8d980-aa84-11ea-9878-6d8e97100f12.png)
Regards

**Comment by cobbr** [comment]
Hey @naruto985 , what exactly is the issue? It appears to be working.

Have you tried navigating to `https://localhost:7443` in a web browser?

**Comment by naruto985** [comment]
Hi Cobbr
My bad. I was looking for the message "Now it is listening on: https://0.0.0.0:7443". And I thought for some reason covenant froze. Its working fine when i Opened the above mentioned link.
Thanks again. 
Regards

**Comment by cobbr** [comment]
No problem! Possible that message is no longer present in the new version.
