### ISSUE TITLE
[Feature Request] Web Log For Listener

### ISSUE THREAD

**Issue by 3lpsy** [cobbr/Covenant#188]
**Feature Request**
Track requests to download hosted files from a listener in Web Log

**Describe the feature request**
Each Listener would have a tab (next to Hosted files) called Web Log where they can view all requests to download hosted files

**Additional context**
If this is something that seems like an acceptable/useful feature, I'd be happy to build out a PR.

**Comment by cobbr** [comment]
@3lpsy I think this is a great idea. A PR would be fantastic!

**Comment by cobbr** [comment]
Feature has been added. Changes currently in dev branch.
