### ISSUE TITLE
[Bug] | Docker won't build

### ISSUE THREAD

**Issue by cathedrall** [cobbr/Covenant#191]
**Feature Request or Bug**
Bug

**Describe the bug**
Docker instructions result in build failure when following Docker build command:
Output:
```
$ docker build -t covenant . 
Sending build context to Docker daemon   85.4MB 
Step 1/10 : FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build 
 ---> 5f369f0d8192
Step 2/10 : WORKDIR /app
 ---> Using cache
 ---> 11a8a0a8f7f4
Step 3/10 : COPY . ./
 ---> Using cache 
 ---> a1b5a933f873
Step 4/10 : RUN dotnet publish -c Release -o out
 ---> Running in 6f5985a8d04e 
Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Core 
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore... 
/usr/share/dotnet/sdk/3.1.301/NuGet.targets(128,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [/app/Covenant.csproj] 
/usr/share/dotnet/sdk/3.1.301/NuGet.targets(128,5): error :   Resource temporarily unavailable [/app/Covenant.csproj]
The command '/bin/sh -c dotnet publish -c Release -o out' returned a non-zero code: 1
```

**To Reproduce**
Follow Docker build instructions:
1. `git clone --recurse-submodules https://github.com/cobbr/Covenant`
2. `cd Covenant/Covenant`
3. `docker build -t covenant .`

**Expected behavior**
Project builds

**Covenant Server Information:**
 - OS: Ubuntu 20.04
 - Docker 

**Additional context**
Not that I can think of.

**Comment by cobbr** [comment]
Hey @cathedrall , to me this looks like an internet connection problem. Does your host have a stable Internet connection? I'd give it another try.

**Comment by cathedrall** [comment]
I thought so to, honestly - but I can successfully curl the URL from the Docker host with no problem. Could it be a docker networking issue? I could try pruning docker and try again.

**Comment by cathedrall** [comment]
Restarting the docker daemon (oof!) seemed to solve the problem. Thanks :)
