### ISSUE TITLE
[Covenant - Docker container] Inability to run covenant in Kali Linux Via Docker or host machine.

### ISSUE THREAD

**Issue by Allevon412** [cobbr/Covenant#192]
I am unable to run covenant via docker or the host machine. If I install and build the covenant files using dotnet I receive similar results. In both circumstances it stops immediately after outputting "Using Covenant certificate with hash: 142F6445B02967EF5AEF0CDC70AD366BB488A1D6" to screen. Plz help.

root@kali:~/Documents/Covenant/Covenant# docker build -t covenant .
Sending build context to Docker daemon  95.39MB
Step 1/10 : FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
 ---> 5f369f0d8192
Step 2/10 : WORKDIR /app
 ---> Using cache
 ---> 02050655f3b5
Step 3/10 : COPY . ./
 ---> Using cache
 ---> 3305e3e6aa55
Step 4/10 : RUN dotnet publish -c Release -o out
 ---> Using cache
 ---> f7fef0496632
Step 5/10 : FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS runtime
 ---> 5f369f0d8192
Step 6/10 : WORKDIR /app
 ---> Using cache
 ---> 02050655f3b5
Step 7/10 : COPY --from=build /app/out .
 ---> Using cache
 ---> 71d14b1a14cc
Step 8/10 : COPY ./Data ./Data
 ---> Using cache
 ---> 0b573445909c
Step 9/10 : EXPOSE 7443 80 443
 ---> Using cache
 ---> e28708fa1797
Step 10/10 : ENTRYPOINT ["dotnet", "Covenant.dll"]
 ---> Using cache
 ---> 455b7464d223
Successfully built 455b7464d223
Successfully tagged covenant:latest
root@kali:~/Documents/Covenant/Covenant# docker run -it -p 7443:7443 -p 80:80 -p 443:443 --name covenant -v /root/Documents/Covenant/Covenant/Data:/app/Data covenant --username AdminUser --computername 0.0.0.0
docker: Error response from daemon: Conflict. The container name "/covenant" is already in use by container "ead2910183f40dd266109ac9c78b7a8c7a6a92c511dac881e7a73c4e4f45b864". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
root@kali:~/Documents/Covenant/Covenant# docker rm covenant
covenant
root@kali:~/Documents/Covenant/Covenant# docker run -it -p 7443:7443 -p 80:80 -p 443:443 --name covenant -v /root/Documents/Covenant/Covenant/Data:/app/Data covenant --username AdminUser --computername 0.0.0.0
Password: *************
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
warn: Microsoft.EntityFrameworkCore.Model.Validation[10400]
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data, this mode should only be enabled during development.
Using Covenant certificate with hash: 142F6445B02967EF5AEF0CDC70AD366BB488A1D6
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {1291d71d-0deb-4929-af8b-3b81c9a20725} may be persisted to storage in unencrypted form.

**Comment by shadow1587** [comment]
I'm having exactly the same issue!

**Comment by cobbr** [comment]
@Allevon412 @shadow1587 Have you tried navigating to `https://localhost:7443` in a browser? It looks like it may be working to me.

**Comment by Allevon412** [comment]
> @Allevon412 @shadow1587 Have you tried navigating to `https://localhost:7443` in a browser? It looks like it may be working to me.

Yes I am unable to connect to the web server running on port 7443 it just says connection reset by server or whatever. As if the port is not running a webserver.

**Comment by cobbr** [comment]
@Allevon412 Were you sure to include `https:\\`?

**Comment by Allevon412** [comment]
In all honesty. I don't remember but probably not.... that is most likely the issue. Going to close this issue case until I can verify. If there's still an issue I will make another thread. Thanks!
