### ISSUE TITLE
[Bug] Task Export includes command history?

### ISSUE THREAD

**Issue by rasta-mouse** [cobbr/Covenant#197]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
I created some new tasks around the `SharpSploit.LateralMovement.SCM` class via the GUI.  I tested the tasks with a running Grunt and then exported the tasks from the UI.  The exported YAML seems to pick up values I used in my testing, even though I didn't put them in the task definition.

Example from my `CreateRemoteService` task:

```
  - Name: ServiceName
    Value: GruntSVC
    DefaultValue: ''
    Description: ''
    SuggestedValues: []
    Optional: false
    DisplayInCommand: true
    FileOption: false

  - Name: ServiceDisplayName
    Value: Very friendly Grunt Service
    DefaultValue: ''
    Description: ''
    SuggestedValues: []
    Optional: false
    DisplayInCommand: true
    FileOption: false

  - Name: BinaryPath
    Value: C:\Windows\Temp\GruntService.exe
    DefaultValue: ''
    Description: ''
    SuggestedValues: []
    Optional: false
    DisplayInCommand: true
    FileOption: false
```

`DefaultValue` and `SuggestedValues` are blank, as described in the create task UI.  However `Value` of fields are what I used in my `CreateRemoteService` task test.

**To Reproduce**
1. Go to Tasks & create a new Task
2. Execute Task in a Grunt
3. Export Task
4. Task YAML should contain the last values used

**Expected behavior**
I'd expect the `Value` fields to be blank so that the tasks can be shared publically without leaking or revealing information from the test/target environment the task was built in.

**Screenshots**
![image](https://user-images.githubusercontent.com/7346521/85395450-11da1880-b548-11ea-961d-76a548121287.png)

**Covenant Server Information:**
 - OS: Kali Rolling 2020.1
 - Docker or Native: Native

**Browser Information:**
 - Browser: Google Chrome
 - Version: 83.0.4103.106 (Official Build) (64-bit)

**Target Information (System that implant is running on):**
 - OS: Windows 10 LTSB
 - Version: 1607 14393.3750

**Comment by cobbr** [comment]
Thanks @rasta-mouse. Yeah I suppose this is expected, but I agree it'd be a good change to make. I'll likely leave the DefaultValue and SuggestedValues fields, but the Value field should really be cleared.

**Comment by rasta-mouse** [comment]
@cobbr yeah wasn't sure what your intention was. I haven't played with these new YAML tasks much yet, so I'm not sure what the `Value` field does over `DefaultValue` and `SuggestedValues`.

My initial feeling was just that the task shouldn't export anything that I didn't define when I created it, that's all.

**Comment by cobbr** [comment]
Yep, only the `Value` field will have that type of information. `DefaultValue` is used for optional parameters, and `SuggestedValues` is used for tab completion/suggestion.

**Comment by cobbr** [comment]
I think this should be fixed in the dev branch now @rasta-mouse . Mind trying it out and verify that it fixes the issue?

**Comment by cobbr** [comment]
Closing for now. Let me know if the issue persists and we can re-open.
