### ISSUE TITLE
[Bug] GruntTaskingType "Tasks" does not exist, causes GruntTaskingMessage.FromJson to throw 

### ISSUE THREAD

**Issue by Flangvik** [cobbr/Covenant#200]
**Description of bug**
During the initial process for stage2, after Grunt.ExectuerCode is loaded , the initial tasking message fetched indicates a type of string "Tasks"
(This is line ~77 ,ExectuerCode in the Covenant Templates view, default GruntHTTP template)

![image](https://user-images.githubusercontent.com/23613997/85564061-3b6d6f80-b62e-11ea-9963-6f67195b3f11.png)

Further down in the function FromJson, type is attempted parsed into a type-of GruntTaskingType

![image](https://user-images.githubusercontent.com/23613997/85564324-753e7600-b62e-11ea-82be-f7758b7a5d19.png)

GruntTaskingType does not contain an definition of "Tasks", throwing error ( line 744-750 in the picture)

![image](https://user-images.githubusercontent.com/23613997/85564357-7bcced80-b62e-11ea-931f-d49110064406.png)

**To Reproduce**
Default installation of Covenant, just pulled hours ago.

**Expected behavior**
GruntTaskingType needs to contain an definition of "Tasks" ?(Seems to work when added)

**Covenant Server Information:**
 - Linux **** 4.4.0-169-generic Ubuntu x86_64 
 - Native

**Target Information (System that implant is running on):**
 - Windows 10 1909

**Comment by cobbr** [comment]
Hey @Flangvik , my guess is that you did `git pull` from an existing Covenant installation? If so, you'll need to wipe the database with `rm Data\covenant.db` and restart Covenant.

**Comment by Flangvik** [comment]
True, but not actually. I removed the entire (existing) Covenant folder before re-doing git clone
So db should have been deleted aswell

**Comment by cobbr** [comment]
Hmm, well I would just give that a try and see what happens @Flangvik . Just stop Covenant, `rm Data/Covenant.db` and restart Covenant. If that doesn't work, we can look into what's going on.

**Comment by cobbr** [comment]
Here's why that is my suspicion: https://github.com/cobbr/Covenant/blob/master/Covenant/Data/Grunt/GruntHTTP/GruntHTTP.cs#L747

**Comment by Flangvik** [comment]
Weird, must be on my side then. Thanks anyhow!

**Comment by cobbr** [comment]
Were you able to get it working @Flangvik ?

**Comment by Flangvik** [comment]
> 
> 
> Were you able to get it working @Flangvik ?

Yes, it was on my side. Sorry for the bother!

**Comment by cobbr** [comment]
No worries at all, just wanted to make sure you got it fixed and working 🙂
