### ISSUE TITLE
[Bug] "Create" button not working for ReferenceAssemblies, EmbeddedResources, and ReferenceSourceLibraries

### ISSUE THREAD

**Issue by py7hagoras** [cobbr/Covenant#204]
**Bug**

**Describe the feature request or bug**
The Create button does not work for ReferenceAssemblies, EmbeddedResources, and ReferenceSourceLibraries

**To Reproduce**
1. Go to 'Tasks'
2. Click on 'Reference Assemblies'
3. Click on '+ Create' button

**Expected behavior**
It should show the page for creating a new reference assembly

**Screenshots**

![image](https://user-images.githubusercontent.com/6564346/86963297-4944e980-c132-11ea-858c-7aaf9e8b0643.png)

**Covenant Server Information:**
 - OS: Linux kali 5.2.0-kali2-amd64 #1 SMP Debian 5.2.9-2kali1 (2019-08-22) x86_64 GNU/Linux
 - Docker or Native: Docker 

**Browser Information:**
 - Browser : Chrome
 - Version:  83.0.4103.106 (Official Build) (64-bit)

**Comment by cobbr** [comment]
Thanks for the heads up @py7hagoras . This was fixed in 7d64880d05af4786a65d4b7d9476ce7b781f4f52, I just forgot to update this issue at the time.

Closing for now. If you continue to have issues with the latest code, we can reopen.
