### ISSUE TITLE
[Bug] Covenant not starting

### ISSUE THREAD

**Issue by f8al** [cobbr/Covenant#205]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
running `dotnet build` completes successfully, however when running `dotnet run` covenant never starts.  have tried in both kali 2020 and windows 10

**To Reproduce**
1. $ ~ > git clone --recurse-submodules https://github.com/cobbr/Covenant
2. $ ~ > cd Covenant/Covenant
3. $ ~/Covenant/Covenant > dotnet build
4. $ ~/Covenant/Covenant > dotnet run

**Expected behavior**
covenant to start successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/7221183/86975398-db062400-c13d-11ea-8045-e8fccc21f6b6.png)
![image](https://user-images.githubusercontent.com/7221183/86975542-291b2780-c13e-11ea-9d85-0f6568890bc1.png)

**Covenant Server Information:**
 - OS: both kali 2020.1 and windows 10
 - Docker or Native: Native

**Browser Information:**
- N/A

**Target Information (System that implant is running on):**
 - N/A
**Additional context**
N/A

**Comment by cobbr** [comment]
@f8al It looks to be working to me, have you tried navigating to `https://localhost:7443` in a browser?

**Comment by f8al** [comment]
yes, wasnt able to connect on 7443

**Comment by cobbr** [comment]
@f8al Did you use https?

**Comment by f8al** [comment]
yes.  looks like it was being stopped by an overzealous crowdstrike policy.  got my endpoint team to whitelist it and its now working

**Comment by cobbr** [comment]
Ahh, interesting. Glad it's working now 👍
