### ISSUE TITLE
[Feature Request] Please update Mimikatz for newer Windows OS compatibility

### ISSUE THREAD

**Issue by MiSERYYYYY** [cobbr/Covenant#206]
Please update the Mimikatz to the latest version. I can't get it working on a Windows 10 build 1909 but it works on older Windows builds. Thanks

![image](https://user-images.githubusercontent.com/66387143/86978418-e3b22680-c14c-11ea-80d8-12d60c41e56f.png)

**Comment by Iorpim** [comment]
I am not sure this is within the Covenant scope, the Mimikatz command is part of the SharpSploit module, so you would need to make a request in that repo, or, you could manually update it. 
All you need to do is:
- Clone the Mimikatz repository
- Compile it with the "Second_Release_PowerShell" config
- Replace them appropriately here: _"Covenant/Data/ReferenceSourceLibraries/SharpSploit/SharpSploit/Resources/"_

(If Docker, image rebuild may be necessary, not sure.)

**Comment by MiSERYYYYY** [comment]
Thank you, good sir.

**Comment by Iorpim** [comment]
Always great to help! 
Good day to you, sir.
