### ISSUE TITLE
[Error] Unable to proceed further after "dotnet run"

### ISSUE THREAD

**Issue by rebootcuong** [cobbr/Covenant#208]
**Error**
warn: Microsoft.EntityFrameworkCore.Model.Validation[10400]
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data, this mode should only be enabled during development.
Using Covenant certificate with hash: CFEDAFC59FB9C8F91D94ADF191A562DC9C2DE37D

**To Reproduce**
$ ~ > git clone --recurse-submodules https://github.com/cobbr/Covenant
$ ~ > cd Covenant/Covenant
$ ~/Covenant/Covenant > dotnet build
$ ~/Covenant/Covenant > dotnet run

**Expected behavior**
I expect this to show me the localhost with the specific port number so I can log in and register.

**Screenshots**
![Screenshot_2020-07-20_06-31-50](https://user-images.githubusercontent.com/46670348/87928657-29c39000-ca53-11ea-9400-ded1b7c89417.png)

**Covenant Server Information:**
 - OS: Kali Linux in VirtualBox
 - Docker or Native: Native

**Browser Information:**
 - Browser: Firefox Quantum
 - Version: 68.9.0esr (64-bit)

**Additional context**
Nothing

**Comment by d-sec-net** [comment]
Check it's actually running. It no longer outputs the connection address. But it is running check the port is open and try it through the browser.

**Comment by rebootcuong** [comment]
Thank you for your reply. I thought there was an output that lets me know that it is up and running. I browsed to https://127.0.0.1:7443 and it works
You can now close this off. Thank you so much again
