### ISSUE TITLE
[Bug| using nginx proxy error

### ISSUE THREAD

**Issue by isafe** [cobbr/Covenant#209]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
Using nginx proxy Listeners(DefaultHttpProfile) websocker error
```
failed: Error during WebSocket handshake: Unexpected response code: 200
Error: Failed to start the transport 'WebSockets': Error: There was an error with the transport.
```
**To Reproduce**
1. Go to Chrome
2. DevTools
3. Console
4. refresh and See error

**Expected behavior**

**Screenshots**

**Covenant Server Information:**
 - OS: Linux
 - Docker

**Browser Information:**
 - Browser [chrome]
 - Version [84]

**Target Information (System that implant is running on):**

**Additional context**
my nginx proxy conf
```
location / {
	        proxy_pass http://127.0.0.1:80;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host:$server_port;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Real-PORT $remote_port;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}
```

**Comment by cobbr** [comment]
@isafe I'll probably need more detail with why you think this is a Covenant issue rather than an issue with the nginx setup?

**Comment by isafe** [comment]
@3lpsy  It's work for me. Thank you !
