### ISSUE TITLE
stuck at Using Covenant certificate with hash: 2068EC21....

### ISSUE THREAD

**Issue by dodiorne** [cobbr/Covenant#211]
Wanting to get up to speed on this tool.

I've tried fresh installs on Kali/ParrotOS/W10.  All of them yield the same hangup.

sudo dotnet --list-runtimes
Microsoft.NETCore.App 3.1.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by cobbr** [comment]
Navigate to `https://localhost:7443` in a browser

**Comment by dodiorne** [comment]
I think i missed part of this in the original message.  will try your suggestion and reply in a minute.

PS /home/osboxes/htb/Covenant/Covenant> sudo /root/.dotnet/dotnet run
warn: Microsoft.EntityFrameworkCore.Model.Validation[10400]
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data, this mode should only be enabled during development.
Using Covenant certificate with hash: 2068EC21...

**Comment by dodiorne** [comment]
facepalm

i was waiting for the indication like in the instructions.  thank you!
