### ISSUE TITLE
[Bug and Feature Request] Please update to support TLS 1.2

### ISSUE THREAD

**Issue by mepher** [cobbr/Covenant#212]
The grunt call back fails when using strict TLS 1.2 enforcing domain fronts, to fix this change to support TLS 1.2 && use `(SecurityProtocolType)3072`

Line 61 in the Grunt Template StagerCode :
`ServicePointManager.SecurityProtocol = (SecurityProtocolType)3072 | SecurityProtocolType.Ssl3 | SecurityProtocolType.Tls;`
Line 608 in the Grunt Template ExecutorCode
`ServicePointManager.SecurityProtocol = (SecurityProtocolType)3072 | SecurityProtocolType.Ssl3 | SecurityProtocolType.Tls;`

**Comment by cobbr** [comment]
@mepher Have you tested this change with your own template?

**Comment by mepher** [comment]
I have & it works. 
I used DNSpy to debug an agent as it called back, to see the original error. 
Altough, the actual domain fronting with <redacted> provider was significantly more work :)
