### ISSUE TITLE
[Bug] Proxy aware payload

### ISSUE THREAD

**Issue by b4b857f6ee** [cobbr/Covenant#213]
**Feature Request or Bug**
Bug ?

**Describe the feature request or bug**
I can't find in the documentation but Covenant didn't generate proxy aware payload?

**To Reproduce**
1. Run payload behind a proxy, for exemple a lan with a squid proxy to go outside.

**Expected behavior**
Connect to the C2 from a LAN behind a proxy

**Screenshots**

**Covenant Server Information:**
 - OS: Ubuntu 18.04
 - Docker or Native: Docker
**Browser Information:**
 - Browser Chromium
 - Version 84

**Target Information (System that implant is running on):**
 - OS: Windows 7
 - Version pro 64 bits

**Additional context**
None

**Comment by cobbr** [comment]
Hi @b4b857f6ee , a Grunt will use the default proxy configured on a Windows system, but it's not going to detect a transparent proxy that isn't configured as the system's default proxy. It really has no way of doing that, but you could hard-code a transparent proxy if you needed to do so.

**Comment by b4b857f6ee** [comment]
Ok so i need to found why my payload connect once and get untrusted and i can't run command to it...
Maybe you have an idea?

**Comment by cobbr** [comment]
It's difficult to tell without a a lot more information @b4b857f6ee, but it sounds like it could be an AMSI problem.

**Comment by cobbr** [comment]
Closing this for now, issue seems unrelated to proxies.
