### ISSUE TITLE
Do not create the link please help me

### ISSUE THREAD

**Issue by Anonymejo** [cobbr/Covenant#214]
root@kali:~/Covenant/Covenant# dotnet build
Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  Covenant -> /root/Covenant/Covenant/bin/Debug/netcoreapp3.1/Covenant.dll
  Covenant -> /root/Covenant/Covenant/bin/Debug/netcoreapp3.1/Covenant.Views.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.08
root@kali:~/Covenant/Covenant# dotnet run
warn: Microsoft.EntityFrameworkCore.Model.Validation[10400]
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data, this mode should only be enabled during development.
Using Covenant certificate with hash: 2870208F64744BBC7FA93E971ADDA7A2576979A9

**Comment by cobbr** [comment]
Navigate to https://localhost:7443 in a browser.
