### ISSUE TITLE
[Bug] Unhandled Exception on /listener/create

### ISSUE THREAD

**Issue by antisnatchor** [cobbr/Covenant#217]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
It appears I can't create Listeners

**To Reproduce**
Fresh installation of Covenant on Ubuntu server, Dotnet 3.1.
dotnet build. dotnet run (as root).
After creting a new user, go to https://IP:7443/listener/create

**Expected behavior**
Listener create page. Instead I always get an exception. The error seems to be in blazor_server JS client.
I need to do a full refresh if I want to keep using the web UI.

**Screenshots**

<img width="1282" alt="Screenshot 2020-08-04 at 08 43 15" src="https://user-images.githubusercontent.com/910293/89262674-3558ae80-d630-11ea-827b-1da5d38fa3cb.png">

**Covenant Server Information:**
 - OS: Ubuntu 18
 - Native (tried both v0.5 tag and latest master)

**Browser Information:**
 - Browser: Chrome

**Comment by antisnatchor** [comment]
NOTE: I can't replicate using Docker. With docker IT WORKS.

However, it must be something related in the dotnet sdk upgrades in Ubuntu.

I remember it used to work fine in May 2020, with the native build.
Using .NET 3.1.302 on Ubuntu 18. a dotnet clean before the dotnet build/run doesn't seem to make any diff.

**Comment by Flangvik** [comment]
I can confirm having the same issue, worked fine just months ago.

**Comment by cobbr** [comment]
Hmm I believe this should have been fixed in this commit: 79ef1696ae37903a1aa440083cdc31f6deb26c6e

Are either of you still seeing this issue with the latest code? @antisnatchor @Flangvik

**Comment by cobbr** [comment]
I'm fairly certain this has been fixed, so I'm closing it for now. If you continue to have the issue @antisnatchor  or @Flangvik, I'll be happy to reopen the issue.
