### ISSUE TITLE
[Bug] Upload different file

### ISSUE THREAD

**Issue by juliourena** [cobbr/Covenant#218]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
I can't reproduce this, but I have seeing the error more than 3 times. When using upload the file uploaded is not the correct one, I can't validate if was previos one or if it get mess-up in the transfer. 

I think, I'm not sure that it happens with Assembly Execution too. 

**Expected behavior**
Upload correct file 

**Screenshots**
![image](https://user-images.githubusercontent.com/29603107/89481221-4c4ced00-d765-11ea-8ee1-d0fee86680b3.png)

**Covenant Server Information:**
 - OS: Kali
 - Native

**Target Information (System that implant is running on):**
 - OS: Windows 10
 - Version 1809

**Additional context**
If I restart covenant it works, as you can see in the picture.

**Comment by cobbr** [comment]
@juliourena I'm think this might have something to do with executing a Task before a file upload is able to complete. We've implemented a lock/and progress spinner on file uploads, so the task won't begin until an upload has completed. Has been pushed to dev, will be in master soon.

I can't be sure that this is the source of the issue, so let me know if you continue to see this issue and we can re-open.
