### ISSUE TITLE
Please tag v0.6

### ISSUE THREAD

**Issue by frenkel** [cobbr/Covenant#220]
v0.6 was released according to [this blogpost](https://posts.specterops.io/covenant-v0-6-134c5054505f). It seems it was not pushed to Github though. Could you please push the tag?

**Comment by cobbr** [comment]
It was all pushed, I just forgot to tag it. Done now! Thanks for the reminder @frenkel

**Comment by frenkel** [comment]
Great, keep up the good work! :+1:
