### ISSUE TITLE
[Bug] Token impersonation issue

### ISSUE THREAD

**Issue by artofwar2306** [cobbr/Covenant#222]
**Bug**
Bug

**Describe the feature request or bug**
Hi I have been testing out v0.6 and noticed that when i attempt to create a Token it is created, however when i attempt to list out the remote machines directory i get an access denied error message.

Also when i attempt to run Powershell commands using the Interactive menu the input seems to not be read, i there fore need to go into the Task menu to enter the command and only then do i get the command to execute.

This did not used to happen in v0.5 
![error message cov](https://user-images.githubusercontent.com/43460290/90236022-c7449080-de54-11ea-95db-bc1bd8da9694.PNG)

**Screenshots**
Screenshot added

**Covenant Server Information:**
 - OS: Kali

**Browser Information:**
 - Browser Chrome and Firefox
 

**Target Information (System that implant is running on):**
 - OS: Windows 2016
 - Version 1493

**Comment by cobbr** [comment]
Confirmed, there is an issue with token impersonation tasks. I think I know what's going on here.

**Comment by cobbr** [comment]
Should be fixed in 490e7ea378c6ebac6443662eb2aa77d6084505be

Let me know if you continue to have issues!
