### ISSUE TITLE
[Bug] Deletion of grunt through API invalidates the respective payload

### ISSUE THREAD

**Issue by py7hagoras** [cobbr/Covenant#228]
**Feature Request or Bug**
Bug

**Describe the bug**
 If one deletes a lost or active grunt through API, it also invalidates the payload that was used to generate the grunt. Latter attempts to run the payload gives a "404 NOT Found" error. I think its because the GUID and Setup Key are wiped upon deletion of grunt.

**To Reproduce**
1. Generate a binary and execute it to get a grunt.
2. Either exit the grunt or leave it active
3. Through the API (https://covenantIP:7443/swagger), delete the grunt using its ID, ```/api/grunts/{id}```
4. then try to execute the same binary that got the initial grunt.
5. Gets a 404 Error, though already existing grunts would still continue checking in, but the payload cant produce any new ones.

**Expected behavior**
Deletion of a grunt should not affect the payload.

**Comment by cobbr** [comment]
Good catch @py7hagoras. Thanks for the heads up.

This should be fixed in the dev branch.
