### ISSUE TITLE
[BUG] Encoded Launcher Field Not Long Enough

### ISSUE THREAD

**Issue by digitalohm** [cobbr/Covenant#229]
Bug

We created a new grunt template for the zeropoint class and the encoded launcher output is over the 10000 character limit of the field.  Currently in testing its 10266, but I would suggest padding it a little more just in case

**Expected behavior**
I would expect the encoded output to not be cutoff

**Additional context**
Discussed with @cobbr via slack !

**Comment by cobbr** [comment]
Well it turns out the limit is actually already set to 20000. Are you able to provide the custom template you are using and I can debug what is going on?

**Comment by digitalohm** [comment]
apologies for the delay, I was making sure I had permission to post the code:

in order to get around the instability of the GruntSMB we are using an GruntHTTPProxyAuth.  We copy the template code for the GruntHTTP

![image](https://user-images.githubusercontent.com/5267192/91891359-c2018700-ec45-11ea-9f9a-3facfff1ef3e.png)


![image](https://user-images.githubusercontent.com/5267192/91891380-cc238580-ec45-11ea-9146-6fcacbeef2d1.png)


and replaced them respectively with:

```
wc.UseDefaultCredentials = false;
wc.Proxy = new WebProxy
{
    Address = new Uri("http://tehproxy:tehport"),
    Credentials = new NetworkCredential
    {
        Domain = "tehdomain",
        UserName = "user.name",
        Password = "MySecretPassword1"
    }
};
```

and 

```
this.CovenantClient.UseDefaultCredentials = false;
this.CovenantClient.Proxy = new WebProxy
{
    Address = new Uri("http://tehproxy:tehport"),
    Credentials = new NetworkCredential
    {
        Domain = "tehdomain",
        UserName = "user.name",
        Password = "MySecretPassword1"
    }
};
```

Then go to Templates > Create.  Give the template a name and description, then set the following options:

Language: CSharp
CommType: HTTP
ImplantDirection: Pull
CompatibleListenerTypes: HTTP
CompatibleDotNetVersions: Net35 & Net40

**Comment by cobbr** [comment]
Fixed this by allowing up to 30000 characters. Fixed in dev branch, will be merged to master soon.
