### ISSUE TITLE
Error parsing reference: "microsoft/dotnet:2.1-sdk as build" is not a valid repository/tag: invalid reference format

### ISSUE THREAD

**Issue by demonsec666** [cobbr/Covenant#23]
Covenant demon$ docker build -t covenant .
Sending build context to Docker daemon 25.05 MB
Step 1/11 : FROM microsoft/dotnet:2.1-sdk as build
Error parsing reference: "microsoft/dotnet:2.1-sdk as build" is not a valid repository/tag: invalid reference format

**Comment by cobbr** [comment]
@demonsec666 I can't seem to reproduce this issue. What version of docker are you using?

**Comment by demonsec666** [comment]
![image](https://user-images.githubusercontent.com/24873495/55693080-a7d76100-59df-11e9-9365-e9621e032b78.png)

**Comment by cobbr** [comment]
For MacOS, try out Docker Desktop. Or just install `dotnet` and use without docker if you are having problems with it.
