### ISSUE TITLE
[Bug] SMB Grunt - Disconnect and Reconnect to SMB Grunt fails (same host)

### ISSUE THREAD

**Issue by chopicalqui** [cobbr/Covenant#230]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
While working on PR #166, I discovered this issue, which needs to be resolved on the C2 server side:

By disconnecting and reconnecting to a SMB Grunt, a `NullReferenceException` is thrown in `Covenant\Covenant\Components\Grunts\GruntTable.razor`, which requires a restart of the C2 server. The cause for this behaviour is that Razor accesses `grunt.ImplantTemplate.Name` but `grunt.ImplantTemplate` is `null`. A quick fix to resolve this issue would be replacing the following line in `GruntTable.razor`:
`<td @attributes="InputAttributes">@grunt.ImplantTemplate.Name</td>`
by
`<td @attributes="InputAttributes">@grunt.ImplantTemplate?.Name</td>`
This fix, however, is incomplete as column **Template** is temporarily not populated in the Grunts table in the web frontend.

**To Reproduce**
1. Launch HTTP Grunt **A** (e.g., via PowerShell launcher)
2. Launch SMB Grunt **B** (e.g., via PowerShell launcher)
3. On HTTP Grunt **A**, connect to SMB Grunt **B** via the `Connect` task. 
4. After SMB Grunt **B** became active, disconnect from SMB Grunt **B** by executing the `Disconnect` task on HTTP Grunt **A**.
5. On HTTP Grunt **A**, connect again to the SMB Grunt **B** via the `Connect` task.

**Expected behavior**
The information in `grunt.ImplantTemplate` should be available at all times so that accessing its information does not result in a `NullReferenceException`. In addition, the affected Razor code should check if the member is `null` before accessing it.

**Screenshots**
The following screenshot documents all executed commands to reproduce the issue. The third command results in the `NullReferenceException` (see second and third screenshot) on C2 server and therefore, the last command is not tasked anymore.

![02_issue_01](https://user-images.githubusercontent.com/39760194/91642815-b5571600-ea2e-11ea-856c-475d1d9ed39e.png)

![02_issue_02](https://user-images.githubusercontent.com/39760194/91642821-c56ef580-ea2e-11ea-85ba-73437ef7c4c7.png)

![02_issue_03](https://user-images.githubusercontent.com/39760194/91642825-ca33a980-ea2e-11ea-8281-686b72317e08.png)

**Covenant Server Information**
 - OS: Microsoft Windows 10 Enterprise, 10.0.18362
 - Docker or Native: Native
 - Tested on: **dev** branch; commit `550cff8a41fdb1f885073b2b4f2ef838e89cf9c0` (Aug 26, 2020) with and without PR #166 applied

**Browser Information**
 - Browser Microsoft Edge
 - Version 44.18362.449.0

**Target Information (System that implant is running on):**
see Server Information

**Comment by cobbr** [comment]
Thanks for all the detail here @chopicalqui , it is very appreciated!

**Comment by cobbr** [comment]
Hey @chopicalqui, I believe this should now be fixed. Please take a look and let me know if you can confirm.

**Comment by cobbr** [comment]
Closing for now. If issues persist, just let me know and we can re-open.
