### ISSUE TITLE
[Bug] SMB Grunt - Starting Same SMB Grunt Several Times on Same Host

### ISSUE THREAD

**Issue by chopicalqui** [cobbr/Covenant#231]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
While working on PR #166, I discovered this issue, which needs to be resolved on the C2 server side:

A SMB Grunt with the same named pipe name can be used on a host only once. If the same SMB Grunt is started again, then a new SMB Grunt is created in the **Grunts** table but its status remains in `Stage0` with integrity `Untrusted`. The made observations indicate that the C2 server incorrectly calculates the path from Egress Grunts to Target Grunts. As a result, only the SMB Grunt's initial request for `Stage0` is successful but as the C2 server cannot calculate the path back to the SMB Grunt, no further communication is possible.

**To Reproduce**
Steps to reproduce the behavior (see Screenshots section for more details):

1. Launch HTTP Grunt **A** (e.g., via PowerShell launcher)
2. Launch SMB Grunt **B** (e.g., via PowerShell launcher)
3. On HTTP Grunt **A**, connect to SMB Grunt **B** via the `Connect` task.
4. After SMB Grunt **B** became active, kill SMB Grunt **B**
5. On HTTP Grunt **A**, disconnect from SMB Grunt **B** via the `Disonnect` task.
5. Launch SMB Grunt **B'** again
6. On HTTP Grunt **A**, connect to the new SMB Grunt **B'** via the `Connect` task (execution also leads to issue #230).

**Expected behavior**
The C2 server should correctly calculate paths from the C2 server via Egress Grunts back to Target Grunts to ensure that no communication to Target Grunts is lost.

**Screenshots**
1. The following screenshot shows the content of the **Grunts** table after the HTTP and SMB launchers were created. At that point, the launchers have not been executed.
![03_initial-db-state_01](https://user-images.githubusercontent.com/39760194/91644017-9493be00-ea38-11ea-9b27-6fc4b492d3c3.png)

2. a. The following screenshot documents that the HTTP and SMB Grunts (**A**, **B**) have been launched and that the HTTP Grunt **A** connected to SMB Grunt **B**:
![03_initial-db-state_11](https://user-images.githubusercontent.com/39760194/91644052-cdcc2e00-ea38-11ea-9c65-5829c7ebef56.png)

2. b. The `Connect` task updated the **Children** column in the **Grunts** table of HTTP Grunt **A** (ID 1) to register the path to the SMB Grunt **B**:
![03_initial-db-state_05](https://user-images.githubusercontent.com/39760194/91644092-30bdc500-ea39-11ea-9e85-8a725207e811.png)

3. The following screenshot shows that SMB Grunt **B** was killed to be able to launch SMB Grunt **B'** again:
![03_initial-db-state_04](https://user-images.githubusercontent.com/39760194/91644097-492ddf80-ea39-11ea-9f62-7f8405415aac.png)

4. The HTTP Grunt **A** disconnected from the SMB Grunt **B**:
![03_initial-db-state_06](https://user-images.githubusercontent.com/39760194/91644114-62cf2700-ea39-11ea-9f4d-f849ccd63b7a.png)

**Note** that although the `Disconnect` task was successfully executed, HTTP Grunt **A** still has SMB Grunt **B** registered as a child in the **Grunts** table. Therefore, this path still exists for the C2 server:
![03_initial-db-state_12](https://user-images.githubusercontent.com/39760194/91644142-a164e180-ea39-11ea-8f7c-1b277f22fddf.png)

5. Launching SMB Grunt **B'** again and trying connecting to it from HTTP Grunt **A** does not work anymore; the newly created SMB Grunt **B'** remains in status `Stage0`.
![03_initial-db-state_13](https://user-images.githubusercontent.com/39760194/91644174-fc96d400-ea39-11ea-9faf-daeb4ca99932.png)

As depicted in the following screenshot, the previous execution of task `Connect` created a new SMB Grunt **B'** (ID 3) entry in the **Grunts** table, but the **Children** column was incorrectly updated to the SMB Grunt **B** (ID 2), which represents the SMB Grunt that was already killed.
![03_initial-db-state_10](https://user-images.githubusercontent.com/39760194/91644237-88a8fb80-ea3a-11ea-89f7-c04ca14247a6.png)

**Note** that even if column **Children** of the first row in the `Grunt` table (HTTP Grunt **A**) is updated from `["9b92142ce7"]` to `[]` before connecting to the new SMB Grunt **B'**, the execution still has the same effect.

Due to the incorrect path information in the **Children** column, the `CreateMessageForGrunt` method in method `PostStage0` (see first screenshot below) cannot determine the path back to the newly created Target Grunt and as a result, a HTTP response with status code 404 is returned (see second screenshot below):
![03_initial-db-state_15](https://user-images.githubusercontent.com/39760194/91645080-6e731b80-ea42-11ea-869c-fd5937994536.png)

![03_initial-db-state_14](https://user-images.githubusercontent.com/39760194/91644770-9dd45900-ea3f-11ea-8de5-13c9c4c0a039.png)

This indicates that the C2 server cannot calculate the path due to the incorrect path information in the database.

**Covenant Server Information**
OS: Microsoft Windows 10 Enterprise, 10.0.18362
Docker or Native: Native
Tested on: dev branch; commit 550cff8a41fdb1f885073b2b4f2ef838e89cf9c0 (Aug 26, 2020)

**Browser Information**
Browser Microsoft Edge
Version 44.18362.449.0

**Target Information (System that implant is running on)**
see Server Information

**Comment by cobbr** [comment]
Thanks again for all the details on this one @chopicalqui , this is very helpful.

**Comment by cobbr** [comment]
Hey @chopicalqui, I believe this should now be fixed. Please take a look and let me know if you can confirm.

**Comment by cobbr** [comment]
Closing for now. If issues persist, just let me know and we can re-open.
