### ISSUE TITLE
[Bug Hosted files on Listener are not correctly deleted

### ISSUE THREAD

**Issue by Jormungand999** [cobbr/Covenant#234]
Bug

**Describe the feature request or bug**
When deleting a hosted file from a listener in the GUI the file is not actually deleted on the server and is still being served.

**To Reproduce**
1. Click on Hosted Files tab for a listeren
2. Create a new file
3. Confirm it's served by server
4. Remove the file in the UI
5. Observe the file is not deleted from the filesystem and is still served

**Expected behavior**
Deleting a file in the UI must also prevent that file from being served by the server.

**Comment by cobbr** [comment]
Great catch @Jormungand999 , apologies for the delay.

This has been fixed. Changes currently in dev branch.
