### ISSUE TITLE
[Bug] Listener using TLS is not correctly shown in the UI

### ISSUE THREAD

**Issue by Jormungand999** [cobbr/Covenant#235]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
When opening the settings page of a listener that is using a SSL certificate, the UI shows **UseSSL: False** while that listener is in fact using a certificate.

**Expected behavior**
The UI should reflect the actual configuration at all times

**Comment by rocketscientist911** [comment]
I thought its not working until i hit this page and realized its a bug.
