### ISSUE TITLE
Cannot successfully Run Container after building

### ISSUE THREAD

**Issue by Wraiith1** [cobbr/Covenant#24]
Step 1:

git clone --recurse-submodules https://github.com/cobbr/Covenant

Step 2: 

cd into /tmp/Covenant/Covenant

docker build -t covenant .

Container successfully builds image

Step 3: 

docker run -it -p 7443:7443 -p 80:80 -p 443:443 --name covenant -v /root/tmp/Covenant/Covenant/Data:/app/Data covenant --username AdminUser --computername 0.0.0.0

ERROR: 

Error: git submodules have not been initialized
Covenant's submodules can be cloned with: git clone --recurse-submodules https://github.com/cobbr/Covenant
Or initialized after cloning with: git submodule update --init --recursive

Step 4: docker rm covenant 

Step 5: git submodule update --init --recursive

Step 6: Rebuild container and try again

Same ERROR as above:

Using Kali Linux 2019 x64

**Comment by cobbr** [comment]
Hey @Wraiith1! From your example, it looks like your data directory does not match your path. You are cloning the directory to `/tmp/Covenant/Covenant/Data`, but your `-v` parameter is `/root/tmp/Covenant/Covenant/Data`. You must point the `-v` parameter to a valid `Data` directory or you will receive this error message.

Perhaps I could add an alternative error message if a malformed Data directory is specified. Let me know if this fixes the issue for you!

**Comment by Wraiith1** [comment]
This was a user error.
