### ISSUE TITLE
[Bug] Docker container fails to run (git submodules not initialised)

### ISSUE THREAD

**Issue by HeckerBirb** [cobbr/Covenant#243]
**Bug**
Docker container fails to run (git submodules not initialised)

**Describe the feature request or bug**
When following the steps to create and run a Docker container in the documentation, the container produces the following output, the quits  immediately:
```
Error: git submodules have not been initialized
Covenant's submodules can be cloned with: git clone --recurse-submodules https://github.com/cobbr/Covenant
Or initialized after cloning with: git submodule update --init --recursive
``` 

**To Reproduce**
1. Visit [the install guide for Docker containers](https://github.com/cobbr/Covenant/wiki/Installation-And-Startup#option-2---docker) and follow the guide to create an image.
2. Be sure to use the correct git clone command.
3. Run the command to start the container in interactive mode: 
  `docker run -it -p 7443:7443 -p 80:80 -p 443:443 --name covenant -v /root/htb/rastalabs/covenant/data/:/app/Data covenant`
4. See error:
```
root@kali:~# docker run -it -p 7443:7443 -p 80:80 -p 443:443 --name covenant -v /data/:/app/Data covenant
Error: git submodules have not been initialized
Covenant's submodules can be cloned with: git clone --recurse-submodules https://github.com/cobbr/Covenant
Or initialized after cloning with: git submodule update --init --recursive
```

**Expected behavior**
The container starts withtout problems, just like when running `dotnet run` inside the Covenant directory (which works without problems).

**Covenant Server Information:**
 - OS: Linux kali 5.8.0-kali1-amd64 #1 SMP Debian 5.8.7-1kali1 (2020-09-14) x86_64 GNU/Linux
 - Docker or Native: Docker

**Comment by HeckerBirb** [comment]
I have a solution ready already which I can do a pull request of, if preferred. Basically:
1. Move `Dockerfile` to the root (up one level)
2. Replace the contents with the following:
```
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /app
COPY . ./
RUN git submodule update --init --recursive
WORKDIR /app/Covenant
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS runtime
WORKDIR /app/Covenant
COPY --from=build /app/Covenant/out .
COPY ./Covenant/Data ./Data
EXPOSE 7443 80 443
ENTRYPOINT ["dotnet", "Covenant.dll"]
```
Essentially: copy the entire git folder, do git sub module initialisation and then build and run.

**Comment by cobbr** [comment]
I'm unable to reproduce this @HeckerBirb . I'd ensure that you are using the fully qualified path to your data folder. It's unlikely that `/data/` is correct.

**Comment by HeckerBirb** [comment]
Yep, my full path was something along the lines of `/root/fun/path/to/my/data/` which I also specified. That you're not able to reproduce is odd... I've spend over an hour trying to get around it, lol.

**Comment by cobbr** [comment]
Glad you got it working!

**Comment by theguly** [comment]
hi there, i see this issue is still alive and kickin.
do think you will accept a PR that fixes as https://github.com/cobbr/Covenant/issues/243#issuecomment-694539808 points out?

**Comment by cobbr** [comment]
Hey @theguly , I'm not sure what you mean. This issue has been closed.

**Comment by theguly** [comment]
> Hey @theguly , I'm not sure what you mean. This issue has been closed.

thanks for the reply. yes, the issue is closed, but instructions to run covenant as docker container leads to the error about submodules that has been raised last september.

maybe the issue is not resolved, and because the workaround posted here works i'm offering to prepare and send a pull request if you think it could be useful.

**Comment by cobbr** [comment]
Hi @theguly , it will not give that error if you have correctly cloned the submodules. I don't think a workaround is needed, unless I am misunderstanding something.

**Comment by theguly** [comment]
i am following instruction step by step:
```
mkdir -p /root/cov/data
cd /root/cov/
git clone --recurse-submodules https://github.com/cobbr/Covenant
cd Covenant/Covenant
docker build -t covenant .
docker run -it -p 7443:7443 -p 80:80 -p 443:443 --name covenant -v /root/cov/data:/app/Data covenant
```

and the command replies with a:
```Error: git submodules have not been initialized
Covenant's submodules can be cloned with: git clone --recurse-submodules https://github.com/cobbr/Covenant
Or initialized after cloning with: git submodule update --init --recursive```
