### ISSUE TITLE
[Bug] Covenant Crash after connect to SMBGrunt

### ISSUE THREAD

**Issue by S3cur3Th1sSh1t** [cobbr/Covenant#260]
**Bug**
Covenant Crash after connect to SMBGrunt

**Description**
I have a Grunt connected to my Covenant C2 via HTTP over a proxy. I build a powershell SMBGrunt stager to connect another system in the network which has no proxy connectivity. Execute the SMBGrunt stager on the seccond remote system works, after issuing "Connect hostname PipeName" the whole Covenant instance crashes without any error message.

**To Reproduce**
1. Create HTTP Listener
2. Connect System over proxy
3. Create and execute SMBGrunt stager on a seccond system with no proxy access
4. "Connect Seccondhostname Pipename"
5. Covenant crash

**Expected behavior**
A new Session from the seccond host or at least no crash.

**Covenant Server Information:**
 - OS: Default Kali
 - Native

**Browser Information:**
 - Firefox

**Target Information **
 - Windows 10 first system
 - Windows Server 2016 seccond system

Can i run convenant with debug/verbose parameters or something like that to get more information about the issue?

**Comment by S3cur3Th1sSh1t** [comment]
2b556cf45f596d94b367171b0938fc22bd22e6ab fixed it for me i can connect to SMBGrunts now. They still die sometimes but it works generally.

**Comment by cobbr** [comment]
Glad it is working for you @S3cur3Th1sSh1t . Let me know if any issues persist.
