### ISSUE TITLE
[Bug] GruntBridge is tightly coupled with TcpC2Bridge

### ISSUE THREAD

**Issue by v-p-b** [cobbr/Covenant#262]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**

The `GruntBridge` class assumes properties specific to the TcpC2Bridge example of the C2Bridge project. This prevents developing bridges without modifying Covenant code.

**To Reproduce**

here we can see that it is assumed that `BridgeMessenger`s have `client` and `stream` properties while none of these are defined by the `IMessenger` interface:

https://github.com/cobbr/Covenant/blob/5b90f203c2e42c0f0e5607653c71f6fc452adaab/Covenant/Data/Grunt/GruntBridge/GruntBridge.cs#L62

https://github.com/cobbr/Covenant/blob/5b90f203c2e42c0f0e5607653c71f6fc452adaab/Covenant/Data/Grunt/GruntBridge/GruntBridge.cs#L63

This assumption is also reflected in the signature of the `Execute()` method:

https://github.com/cobbr/Covenant/blob/5b90f203c2e42c0f0e5607653c71f6fc452adaab/Covenant/Data/Grunt/GruntBridge/GruntBridge.cs#L21

**Expected behavior**

`GruntBridge` should make no assumptions about the internals of C2Bridges.

**Screenshots**
N/A

**Covenant Server Information:**

Not relevant.

**Browser Information:**

Not relevant.

**Target Information (System that implant is running on):**

Not relevant.

**Additional context**

N/A

**Comment by cobbr** [comment]
Hey @v-p-b , apologies for the late response. Great catch, I'm pretty confused as to how this happened. But either way, it should be addressed in the current dev branch. Please use this with the new update to the C2Bridge in the dev branch on that project.

Closing for now, as I believe it is fixed. If it's still not working, we can re-open.
