### ISSUE TITLE
[Bug] Illegal Characters in Path When Executing Listener

### ISSUE THREAD

**Issue by BlackRobinLabs** [cobbr/Covenant#263]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
Cannot successfully launch a Grunt with any available method. Receive error message (on PowerShell launcher for instance "Illegal Characters in path")

**To Reproduce**
1. clone Covenant repo
2. ran dotnet build and dotnet run (as admin)
3. created listener
4. created launcher
5. tried all launchers, on various versions of Windows 10

**Expected behavior**
Expected Grunt to launch and communicate back with listener.

**Error Output**
Illegal characters in path.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean  checkForDuplicates, Boolean needFullPath)
   at System.Net.WebClient.GetUri(String path)
   at System.Net.WebClient.UploadString(String address, String data)
   at GruntStager.GruntStager.ExecuteStager()

**Covenant Server Information:**
 - OS: Ubuntu 20.04LTS
 - Docker or Native: Native

**Browser Information:**
N/A

**Target Information (System that implant is running on):**
 - OS: Win10
 - Version 10.0.19041

**Comment by BlackRobinLabs** [comment]
This was resolved by updating the Grunt Stager code:

Line 61 should be:
`ServicePointManager.SecurityProtocol = (SecurityProtocolType)3072 | SecurityProtocolType.Ssl3 | SecurityProtocolType.Tls;`

as per Mepher's fix here: https://github.com/cobbr/Covenant/issues/143#issuecomment-665044862

**Comment by pravingit** [comment]
Same issue even after changing the ServicePointManager.SecurityProtocol = (SecurityProtocolType)3072 | SecurityProtocolType.Ssl3 | SecurityProtocolType.Tls; in stager code. appreciate if you can provide resolution ASAP.

**Comment by havocsh** [comment]
This happens when you're using a launcher to connect to a listener via a NAT IP address. In other words, the IP address the listener is bound to is different from the Covenant host's public IP address. To fix it, add another ConnectAddress to the listener as shown in the screenshot.

<img width="1403" alt="Covenant_ConnectAddresses" src="https://user-images.githubusercontent.com/44458038/161182868-79af2916-08ac-4cd3-962a-9c2842ca7aa4.png">
