### ISSUE TITLE
[Issue] Unhandled exception creating Listener with bad ConnectAddresses

### ISSUE THREAD

**Issue by brandontict** [cobbr/Covenant#267]
**Describe the feature request or bug**
While attempting to run Covenant , **donet run** errors out

**Screenshots**
![dotnet-error](https://user-images.githubusercontent.com/10290245/99114867-22eafb00-25b7-11eb-9046-118e2f41823b.png)

**Covenant Server Information:**
 - OS: Kali 2020 ; rolling update 
kernel 5.9.0

**Browser Information:**
firefox 

**Additional context**
Installing dotnet sdk finished with no issues. 

I was able to run and login into Covenant one time, The issues happened next time I try and start Covenant .

Any help or input would be appreciated! I'll keep this post updated if I find a fix. 
Thanks for releasing this project

**Comment by checkymander** [comment]
Go into the Data folder and delete covenant.db (assuming you don't have any data you want to keep). Sounds like something got messed up in there.

**Comment by brandontict** [comment]
Thank you for the prompt response and solution. 

removing covenant.db did the trick!

**Comment by cobbr** [comment]
Issue has been fixed. Changes are currently in dev branch.
