### ISSUE TITLE
[Bug] HTTP SSL Listener - Grunt fails to start

### ISSUE THREAD

**Issue by decardcain603** [cobbr/Covenant#268]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
Covenant HTTP listener-produced Grunt fails to start with the following error:

Invalid URI: The URI is empty.
    at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
    at GruntStager.GruntStager.ExecuteStager()

**To Reproduce**
1. Goto listeners
2. Click "Create"
3. Set ConnectAddress as needed
4. Set UseSSL to True
5. Select a certificate, under SSLCertificatePassword - leave empty
6. HttpProfile - DefaultHttpProfile
7. Click "Create"
8. Click on "Launchers"
9. Click on "Binary" Generate and download. Run and see the error

**Expected behavior**
Grunt connects

**Screenshots**

**Covenant Server Information:**
 - OS: Ubuntu 18
 - Docker or Native: Native

**Browser Information:**
 - Browser Chrome
 - Version 84

**Target Information (System that implant is running on):**
 - OS: Windows 10

**Additional context**

**Comment by chosenonepl** [comment]
Have you tried this little change in the code? 

https://github.com/cobbr/Covenant/issues/212

**Comment by decardcain603** [comment]
The problem was with the certificate I tried to import - it doesn't say anywhere you need to import a PFX!

**Comment by cobbr** [comment]
@decardcain603 This is documented in the Wiki: https://github.com/cobbr/Covenant/wiki/Listeners
