### ISSUE TITLE
[Bug] SMB Grunts Hanging at Stage 0 although connection shows as succeeded

### ISSUE THREAD

**Issue by a7t0fwa7** [cobbr/Covenant#271]
**Feature Request or Bug**
Bug
SMB Grunts hanging at Stage0 
**Describe the feature request or bug**
In Covenant when deploying SMB grunt packages, I have deployed them previously in the lab environment, but as of today whenever I go to use the connect command to a named pipe they get to Stage0 and never pass that stage
![image](https://user-images.githubusercontent.com/43460290/101152444-0f82fb00-365e-11eb-94c9-a1d4be05dd9a.png)

**Expected behavior**
The Grunt shows as successfully connected but then just hangs at Stage0, guys in the labs at RTO seem to be exeperiencing the same issues
**Screenshots**
![image](https://user-images.githubusercontent.com/43460290/101153159-0181aa00-365f-11eb-8e4a-b98fbe77a7e5.png)
![image](https://user-images.githubusercontent.com/43460290/101153245-2118d280-365f-11eb-8bad-06284a4083fb.png)

**Covenant Server Information:**
 - OS: Kali
 - Native

**Browser Information:**
 - Browser chrome, firefox
 - Version latest

**Target Information (System that implant is running on):**
 - OS: Windows Server 2016 
 - Version  10.0.14393 N/A Build 14393

Currently doing the exam and it is penalising my progression. This did not happen in previous versions of Covenant before

**Comment by rasta-mouse** [comment]
There's a silly bug in WMICommand where the command is executed twice.  This means you have 2 SMB Grunts with the same pipe name running on the same machine, which is bad.

Steps to reproduce:

```text
(rasta) > PowerShell Get-Process -Name notepad

Cannot find a process with the name "notepad". Verify the process name and call the cmdlet again.


(rasta) > WMICommand localhost "cmd /c notepad"

ReturnValue  ProcessID
-----------  ---------
0            11440


(rasta) > PowerShell Get-Process -Name notepad

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName                                                   
-------  ------    -----      -----     ------     --  -- -----------                                                   
    246      14     3168      14052       0.09  13016   1 notepad                                                       
    246      14     3164      14020       0.03  22784   1 notepad
```

**Comment by rasta-mouse** [comment]
Having a quick look, it appears this bug is in the Task?
https://github.com/cobbr/Covenant/blob/master/Covenant/Data/Tasks/SharpSploit.LateralMovement.yaml#L154-L158

It does:
```c#
WMI.WmiExecuteResult result = WMI.WMIExecute(ComputerName, Command, Username, Password);
```
and then if that result is *not null* it executes again:
```c#
return new SharpSploitResultList<WMI.WmiExecuteResult> { WMI.WMIExecute(ComputerName, Command, Username, Password) }.ToString();
```

The same issue seems to be in WMIGrunt:  https://github.com/cobbr/Covenant/blob/master/Covenant/Data/Tasks/SharpSploit.LateralMovement.yaml#L26-L29

`WMIGrunt localhost powershell` does give me 2 HTTP Grunts at the same time.

![image](https://user-images.githubusercontent.com/7346521/101475730-a7296780-3944-11eb-864a-f820231702dc.png)

**Comment by cobbr** [comment]
Oops! 🤦‍♂️ 

Thanks for the diagnosis and help on this one @rasta-mouse 

This has been fixed. Changes are in dev branch. Let me know if you still have issues @a7t0fwa7
