### ISSUE TITLE
[Bug] Creating new/custom MessageTransform Results in 404 from Server on Initial Grunt Connection

### ISSUE THREAD

**Issue by ac3lives** [cobbr/Covenant#272]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
Creating new MessageTransforms which conduct basic operations, such as rot13 on the message, fail, resulting in a 404 not found error received from the server when attempting to connect at stage 0.

**To Reproduce**
1. Create a new listener profile, using the provided defaults. Verify this works before adding a message transform to it.
2. Take down the listener after verified it is working. Edit the listener profile with a transform which performs the following on the message: `Base64 -> rot13 -> Base64` (sample code provided below)
3. Start a new listener with the profile. Generate a basic grunt payload, compile it, and run it on Windows with .NET v4.8 and all antivirus disabled.
4. The following error is received by the grunt, after sending the encoded stage 0 check-in to the server: 

```
The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   at System.Net.WebClient.UploadString(Uri address, String method, String data)
   at GruntStager.GruntStager.ExecuteStager()
```

**Expected behavior**
The grunt should successfully connect, with the 'Invert' method of the MessageTransform working on the Covenant server/listener to properly decode the 'Transformed' message sent by the stage-0 grunt callback.

**Screenshots**
Added screenshots for the following:

- Listener configuration
- Wireshark TCP stream output following the Grunt communication with the server
- Error displayed, along with added printed output from the Grunt to show messages pre-transform, and post-transform
- dotnet-3.1 Program used to 'Invert' locally with the same MessageTransform class, verifying the 'Transformed' content output by the Grunt could be 'Inverted' back, with a String.Equals to verify the 'Inverted' message equals the pre-transform message output by the Grunt.

**Covenant Server Information:**
 - OS: Ubuntu 18.04
 - Docker or Native: Native

**Target Information (System that implant is running on):**
 - OS: Windows 10 Pro
 - Version 1903

**Additional context**
Transform code for `Base64 -> rot13 -> base64` and the inverted in Invert.
```
    public static class MessageTransform
    {
        public static string Transform(byte[] bytes)
        { 
            String b641 = System.Convert.ToBase64String(bytes); //b64 encode
            String rotEncoded = Rot13(b641); // rot13
            byte[] rottenbyte = Encoding.ASCII.GetBytes(rotEncoded); //convert string to byte
            String b642 = System.Convert.ToBase64String(rottenbyte); // b64 again
            return b642;
        }
        public static byte[] Invert(string str)
        {

            byte[] b641 = System.Convert.FromBase64String(str); //decode b64
            String todecode = Encoding.ASCII.GetString(b641);    //convert byte to string
            String rotdecoded = Rot13(todecode);    //rot13
            byte[] b642 = System.Convert.FromBase64String(rotdecoded);    //base64 decode again (byte output)
            return b642;
        }
        public static string Rot13(string value)
        {
            char[] array = value.ToCharArray();
            for (int i = 0; i < array.Length; i++)
            {
                int number = (int)array[i];

                if (number >= 'a' && number <= 'z')
                {
                    if (number > 'm')
                    {
                        number -= 13;
                    }
                    else
                    {
                        number += 13;
                    }
                }
                else if (number >= 'A' && number <= 'Z')
                {
                    if (number > 'M')
                    {
                        number -= 13;
                    }
                    else
                    {
                        number += 13;
                    }
                }
                array[i] = (char)number;
            }
            return new string(array);
        }
    }
```
![Listener](https://user-images.githubusercontent.com/26721330/101180069-1d625d00-3619-11eb-9a9c-af4db010c182.png)
![TCP Stream Output](https://user-images.githubusercontent.com/26721330/101180071-1d625d00-3619-11eb-9440-6cd303b1311c.png)
![Confirmed MessageTransform Working](https://user-images.githubusercontent.com/26721330/101180072-1dfaf380-3619-11eb-8e23-0364f126d103.png)
![Grunt Execution with Debug](https://user-images.githubusercontent.com/26721330/101180074-1dfaf380-3619-11eb-8a06-f394d8ce55a4.png)

**Comment by ac3lives** [comment]
Per suggestion, I tried restarting Covenant to rule out the MessageTransform being cached on the server as using the default transform. The steps were as follows:

1. Created new listener profile with the modified `base64 -> rot13 -> base64` transform, saved.
2. Restarted Covenant
3. Launched new listener using the modified transform
4. Generated a grunt, copied the raw C# and compiled locally, verified the transform was being used on the grunt side. Executed - received a 404 error.
5. Restarted Covenant
6. Re-ran the same grunt, same 404 error.

**Comment by f0cker** [comment]
I was having the same problem, which I've managed to resolve now by using explicit references. It looks like you may need to do the same, for example

Encoding.ASCII.GetBytes(rotEncoded) --> System.Text.Encoding.ASCII.GetBytes(rotEncoded)

**Comment by cobbr** [comment]
Can confirm what @f0cker has said, this appears to be a compilation issue with this specific MessageTransform, here's a copy of the MessageTransform that works @ac3lives :

```
    public static class MessageTransform
    {
        public static string Transform(byte[] bytes)
        { 
            string b641 = System.Convert.ToBase64String(bytes); //b64 encode
            string rotEncoded = Rot13(b641); // rot13
            byte[] rottenbyte = System.Text.Encoding.ASCII.GetBytes(rotEncoded); //convert string to byte
            string b642 = System.Convert.ToBase64String(rottenbyte); // b64 again
            return b642;
        }
        public static byte[] Invert(string str)
        {

            byte[] b641 = System.Convert.FromBase64String(str); //decode b64
            string todecode = System.Text.Encoding.ASCII.GetString(b641);    //convert byte to string
            string rotdecoded = Rot13(todecode);    //rot13
            byte[] b642 = System.Convert.FromBase64String(rotdecoded);    //base64 decode again (byte output)
            return b642;
        }
        public static string Rot13(string value)
        {
            char[] array = value.ToCharArray();
            for (int i = 0; i < array.Length; i++)
            {
                int number = (int)array[i];

                if (number >= 'a' && number <= 'z')
                {
                    if (number > 'm')
                    {
                        number -= 13;
                    }
                    else
                    {
                        number += 13;
                    }
                }
                else if (number >= 'A' && number <= 'Z')
                {
                    if (number > 'M')
                    {
                        number -= 13;
                    }
                    else
                    {
                        number += 13;
                    }
                }
                array[i] = (char)number;
            }
            return new string(array);
        }
    }
```

With that being said, there's some UX/debugging problems that need to be fixed that I will work on. In the future, the MessageTransform should be tested to compile properly before being saved and an error displayed to the user on compilation issues.

**Comment by cobbr** [comment]
UX has been improved, compilation is tested prior to saving new/existing Profiles. Changes currently in dev branch.
