### ISSUE TITLE
[Feature Request] Grunt's "Interact" terminal auto scrolling

### ISSUE THREAD

**Issue by init5-msft** [cobbr/Covenant#281]
Feature Request

Title says it all. PLEASE add an auto scrolling feature to the Interact terminal, going back and forth between keyboard and mouse is very irritating.
At least add a checkbox or a toggle switch to On/Off auto scrolling.

Thanks!

**Comment by cobbr** [comment]
Yeah, this needs to come back. It used to auto-scroll, but we took it out since it can be irritating for it to scroll when doing multi-user interaction and it's someone else's command.

I'd like to have it auto-scroll _only_ when it's your own command.

**Comment by init5-msft** [comment]
Hence the "On/Off" checkbox :-) You'd be able to turn off the feature if multiple operators are using the same grunt at the same time!
Also THANKS for the great tool, great job!

**Comment by cobbr** [comment]
I'm hesitant to add excessive UI features that clutter the screen, but I'll think about it. For now, I think auto-scrolling on your own commands is a good solution.

**Comment by init5-msft** [comment]
+1
I'm not a big fan of UIs with too many bells and whistles either. I'd rather have one global On/Off switch that will enable/disable auto scrolling everywhere for everyone.

**Comment by cobbr** [comment]
Re-implemented the auto-scrolling, currently in dev branch.
