### ISSUE TITLE
Question: How to reset forgotten password.

### ISSUE THREAD

**Issue by abdihakx** [cobbr/Covenant#282]
Is there a way I can reset the password for the web interface user without re-installing it?

**Comment by cobbr** [comment]
If you have access to the database, you can change it manually with a sqlite tool. Otherwise, a re-install may be required.

**Comment by abdihakx** [comment]
Alright, Thanks!

**Comment by FalcoGer** [comment]
What's the format for the password hash in the database? I want to recover my lost password with hashcat, but I couldn't find which format it uses from the source code. I traced it back to "SignInManager" apparently checking if it's correct or not, but no more info than that.

**Comment by FalcoGer** [comment]
Deleting the database file seemed to have done the trick anyhow. Would still be nice to know though.
