### ISSUE TITLE
[Feature Request] Can we update mimikatz?

### ISSUE THREAD

**Issue by mkunz7** [cobbr/Covenant#287]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
It looks like it's been a while (17 months https://github.com/cobbr/SharpSploit/tree/master/SharpSploit/Resources) since powerkatz was updated. Mimikatz fails with a key import error on the latest version of Windows. `ERROR kuhl_m_sekurlsa_acquireLSA ; Key import` https://github.com/gentilkiwi/mimikatz/issues/248

**To Reproduce**
Execute mimikatz on an updated windows 10 grunt.

**Expected behavior**
Mimikatz should work on latest windows 10

**Screenshots**
n/a

**Covenant Server Information:**
kali latest

**Browser Information:**
 chrome latest

**Target Information (System that implant is running on):**
 - OS: Windows / Server 2019
 - Version latest

**Additional context**
https://github.com/EmpireProject/Empire/issues/1379

**Comment by cobbr** [comment]
Mimikatz version has now been updated in the latest dev branch 👍

**Comment by dyna92** [comment]
i have a problem when execute the Invoke-Mimikatz.ps1 , 
"ERROR kuhl_m_sekurlsa_acquireLSA ; Logon list"
i have been looking for the solution , seems there is no update for the script that solve the problem !!!

**Comment by cobbr** [comment]
Hey @dyna92 , this isn't the right place for Invoke-Mimikatz issues, but it looks to me like you are using an outdated version of Mimikatz.

**Comment by init5-msft** [comment]
hi @cobbr 
is this update gonna go to master anytime soon? ^^

**Comment by cobbr** [comment]
It'll move to master whenever 0.7 is released, hopefully sooner rather than later, but have no specific date in mind. Any reason that dev doesn't do the trick @init5-msft ?

**Comment by R3dP1ll** [comment]
Hello @cobbr 

I just tried mimikatz on the dev branch and it fails (Grunts die)

On the hosts I get this error EventID 1000
Faulting application name: powershell.exe, version: 10.0.19041.546, time stamp: 0x7eda4115
Faulting module name: ntdll.dll, version: 10.0.19041.1288, time stamp: 0xa280d1d6
Exception code: 0xc0000409
Fault offset: 0x00000000000a2070
Faulting process id: 0x2650
Faulting application start time: 0x01d7e7d0f026ccc1
Faulting application path: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: d915ceda-eff8-43c6-a62e-a1d41d2116b4
Faulting package full name: 
Faulting package-relative application ID: 

Or am I doing something wrong? Thank you in advance
