### ISSUE TITLE
[Bug] JSON Content for HttpPostRequest in Listener Profile Fails to Establish C2

### ISSUE THREAD

**Issue by ajpc500** [cobbr/Covenant#288]
**Bug**

When creating a custom HTTP listener profile, inclusion of JSON content for the HTTP POST/GET requests and responses leads to Covenant failing to establish a C2 channel with the Grunt. I'm not 100% sure if this issue exists when using JSON for all request/response fields, but can certainly be replicated when applied to the HttpPostRequest field.

**To Reproduce**
1. Take the DefaultHttpListener and modify the HttpPostRequest field to `{"data":"{DATA}"}`.
2. Spin up listener
3. Launch Grunt (I used hosted PowerShell listener for testing)

**Expected behavior**
JSON content used across requests and responses should be parsed correctly, and allow for C2.

**Screenshots**
![image](https://user-images.githubusercontent.com/62765165/108388431-89ab3080-7206-11eb-8381-edc6d5f56147.png)

**Covenant Server Information:**
 - OS: Windows 10 (server and client)
 - Docker or Native: Native

**Additional context**
Tried on main and dev branches. 
Tried removing the surrounding brackets and just used `"data":"{DATA}"`, this worked fine. Leads me to think it might be some parsing for `{DATA}` that's causing issues.

**Comment by cobbr** [comment]
Pushed a fix to the dev branch, would you mind giving it a try @ajpc500 ?

**Comment by ajpc500** [comment]
Perfect, yep all working with JSON output for all requests and responses 👍🏻

**Comment by cobbr** [comment]
Great!
