### ISSUE TITLE
[Bug] Unable to build docker container

### ISSUE THREAD

**Issue by dsolstad** [cobbr/Covenant#290]
I get the following errors when building the container:
kali@kali:~/Covenant/Covenant$ sudo docker build -t covenant .
Sending build context to Docker daemon  98.07MB
Step 1/10 : FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
 ---> ec3ca8a1472c
Step 2/10 : WORKDIR /app
 ---> Using cache
 ---> 594bc8804ec9
Step 3/10 : COPY . ./
 ---> Using cache
 ---> c18451b547cc
Step 4/10 : RUN dotnet publish -c Release -o out
 ---> Running in 746f5307e016
Microsoft (R) Build Engine version 16.7.2+b60ddb6f4 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
/usr/share/dotnet/sdk/3.1.406/NuGet.targets(128,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [/app/Covenant.csproj]
/usr/share/dotnet/sdk/3.1.406/NuGet.targets(128,5): error :   Resource temporarily unavailable [/app/Covenant.csproj]
The command '/bin/sh -c dotnet publish -c Release -o out' returned a non-zero code: 1

Anyone knows what has gone wrong?

**Comment by cobbr** [comment]
I'd make sure your docker host and docker guest is able to get out to the internet and DNS is working. To build the project it has to download nuget packages.

**Comment by dsolstad** [comment]
Internet and DNS is working perfectly fine.

**Comment by cobbr** [comment]
Well, seems like not if it's not able to get to nuget 😛 

I would try building yourself a docker container and execute a command on the guest directly. My guess is that you will find the the guest either does not have internet access or DNS is not working.

**Comment by cobbr** [comment]
You might check out: https://github.com/cobbr/Covenant/issues/191

It seems like some of had luck restarting the Docker daemon to fix internet issues.

**Comment by dsolstad** [comment]
It helped to restart the docker daemon. Thanks!

**Comment by cobbr** [comment]
Awesome, glad that did the trick!
