### ISSUE TITLE
Software infected with win64:Malware-gen alert

### ISSUE THREAD

**Issue by mpelas** [cobbr/Covenant#293]
hello avast antivirus complains and blocks download of the software 

Please advise because concerns arose following the October 2020 JSON Web Token issue
https://portswigger.net/daily-swig/breaking-the-covenant-researcher-discovers-critical-flaw-in-open-source-c2-framework#:~:text=Covenant%20is%20a%20.,interact%20with%20other%20offensive%20toolkits.

![covenant avast blocked](https://user-images.githubusercontent.com/67267439/109938827-1e1e9400-7cd9-11eb-81bd-0684d5d8c094.jpg)

Regards

**Comment by m0rv4i** [comment]
Can you just add an exclusion for it?

I don't think we can reasonably expect an open source red team framework server to not trigger AV when downloaded...

**Comment by cobbr** [comment]
Hey @mpelas , I appreciate the concern. I think if AV companies are choosing to flag Covenant resources, that's their business, but we have no plans to change course based on this information.

**Comment by mpelas** [comment]
Thanks for the replies.
