### ISSUE TITLE
[Issue]launcher, DotNet Version not selected

### ISSUE THREAD

**Issue by biazar-sudo** [cobbr/Covenant#296]
I cant generate launcher, I cant select  "DotNet Version" in launchers tab
![2021-03-08_10-24-44](https://user-images.githubusercontent.com/77272992/110286116-9a76e700-7ff9-11eb-81c5-7e9014b6198b.jpg)

**Comment by cobbr** [comment]
@biazar-sudo Can you be more descriptive about the issue you are facing? It's not clear to me what the problem is.

If I were to guess without much information, it looks like you have not selected a Listener or ImplantTemplate. I would go ahead and select those first.

**Comment by aancw** [comment]
Hi @biazar-sudo this issue exist when you are not creating Listener first. Please create listener and then go create launcher again. 

CMIIW
