### ISSUE TITLE
User Agent string not set

### ISSUE THREAD

**Issue by WheelsVT** [cobbr/Covenant#30]
First, excellent work. Very impressed.

I'm using Covenant with an Apache redirector that I configured to match based on UA string in the HttpProfile. However, the requests arrive at the redirector without any user agent string present.

ex:
"GET /index.html HTTP/1.1" 200 336 "-" "-"  
"GET /login.aspx HTTP/1.1" 200 336 "-" "-"                          
"GET /home/index HTTP/1.1" 200 336 "-" "-" 

Also, if I create or change a profile it seems that I need to stop covenant, remove the db, and restart it for the profile options to be re-cached. Is there a better method?

**Comment by cobbr** [comment]
Like you mentioned, you can customize the User-Agent by changing the Profile. Currently, there's no good way to create/change profiles through the UI. However, you can customize the profile through the API. You should be able to navigate to, https://localhost:7443/swagger, and edit the profile manually through the API.

I'm working on a better solution for changing/creating new profiles through the UI, but it's not quite there yet.

**Comment by WheelsVT** [comment]
Nice. I'll try to work with it that way. What about the UA not actually being used in the request?

**Comment by cobbr** [comment]
@WheelsVT I'm not sure about that one, does you profile include a User-Agent?

**Comment by WheelsVT** [comment]
Yes, even just using the default profile, which has a User-Agent, the request shows up without one. Confirmed that I see a UA if I manually make a request with a regular browser.

**Comment by cobbr** [comment]
Hmm, that is odd, I'll look into it

**Comment by WheelsVT** [comment]
@cobbr in using the swagger API I can see that httpRequestHeaders is mirroring the httpResponseHeaders field in the profiles. So originally the httpRequestHeaders had the response's "Server" value, which would explain why there was no user-agent coming across. I used the api/profiles/http call to attempt to change it, and it changes both the request and response header values.

I'm guessing there is a call somewhere that initializes both when it should be one or the other. Will continue looking.

**Comment by cobbr** [comment]
Oh no 🤦‍♂ I think I've spotted the issue, I'll make sure this is fixed in the the next release. Thanks for the heads up @WheelsVT

**Comment by cobbr** [comment]
This User-Agent issue is fixed in the new version. It is also much simpler to modify and create new profiles through the new interface.

Thanks for the report @WheelsVT!
