### ISSUE TITLE
[Bug] Pop Up functionalities disable Covenant controls until page refresh

### ISSUE THREAD

**Issue by sentientchip** [cobbr/Covenant#300]
**Bug**
 

**Describe the feature request or bug**
When using covenant functionalities that would open a pop up, Covenant front end stops working. 
Reproduction rate is 1 out of 10/20. 

**To Reproduce**
1. Use the upload, inject functions (a pop up should open) 
2. Screen fade show appears over the whole screen and any front end interaction stop being possible. 
3. To resume front end control, a simple page refresh is enough.

![image](https://user-images.githubusercontent.com/34633522/111259276-42f2ff80-8627-11eb-9d4d-924bfd0a2da0.png)
![image](https://user-images.githubusercontent.com/34633522/111258922-9b75cd00-8626-11eb-8d64-61460da76a46.png)
![image](https://user-images.githubusercontent.com/34633522/111259047-d4ae3d00-8626-11eb-9396-7441a44d1b87.png)

 
**Expected behavior**
A popup should open and allow you to upload various payloads.
 
**Covenant Server Information:**
 - OS: Linux kali 5.10.0-kali3-amd64 #1 SMP Debian 5.10.13-1kali1 (2021-02-08) x86_64
 - Native

**Browser Information:**
 - Firefox 78.7,  64bit
 - 89.0.4389.90,  64-bit

**Target Information (System that implant is running on):**
 - Microsoft Windows NT 10.0.14393.0

**Comment by cobbr** [comment]
This seems to happen if it's not the first tab opened. Fixed in dev branch.
