### ISSUE TITLE
[Bug] Dev Branch: Listeners cannot host large files (~>0.5MB)

### ISSUE THREAD

**Issue by s7331** [cobbr/Covenant#306]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
It seems that attempting to host files larger than 0.5MB results in an upload failure and then an application crash.

**To Reproduce**
1. Start Covenant server (dev branch, latest).
2. Create HTTP (no ssl) listener on port 80 using either CustomHttpProfile or DefaultHttpProfile. (I did not test SSL)
3. Click "Hosted Files", then "Create". Enter a path and then browse to a file ~>0.5MB. 
4. Click "Create" and observe error. 

**Expected behavior**
I expected the files I selected to be hosted to be hosted without crashes. 

**Screenshots**
Attached image of the terminal output describing error. 
![image](https://user-images.githubusercontent.com/81834305/113490412-b5713580-9497-11eb-9f01-6399dc45e983.png)

**Covenant Server Information:**
 - OS: Linux
 - Docker or Native: Docker

**Browser Information:**
 - Browser: Firefox
 - Version 78.9

**Target Information (System that implant is running on):**
N/A

**Additional context**
I was able to get files <512k bytes to upload just fine, but files around the 513k-514k range resulted in crashes. This issue is not present on the Master branch. I recognize that saying "it works on the master branch" doesnt really narrow it down given how far ahead the deb branch is now, but I haven't had a chance to dig in enough to determine exactly when hosting files stopped fully functioning.

I tested this with both legitimate, organic files and garbage created using fallocate (fallocate -l 514000 514k.txt). I am not running AV that would be killing anything.

**Comment by s7331** [comment]
After a bit more digging it seems like this is a limitation of the InputFile component (as part of the "Covenant/Components/HostedFiles/HostedFileForm.razor file in this case). According to the MS docs the InputFile component will throw an exception for any files larger than 512k bytes as a mechanism to protect devs from accidentally reading large files into memory.

https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads

**Comment by jannlemm0913** [comment]
Thank you for bringing up this issue and finding the problem, we (@J05ePabl0 and me) had a very similar issue with PowerShellImport not correctly handling large obfuscated scripts. It was also behaving similarly to issue 299 (@ChuanNegro, this could be interesting for you as well) where old files were re-uploaded when files were too big.

We used the "hack" solution with increasing the maxAllowedSize parameter for every OpenReadStream() occurence in the code (can find the occurences in Visual Studio, GitHub is somehow not searching in a specified branch for me...). 

As an example in Covenant\Components\Grunts\GruntTaskAssignForm.razor:
Before: `await e.File.OpenReadStream().CopyToAsync(ms);`
After: `await e.File.OpenReadStream(50*1024*1024).CopyToAsync(ms);` (maxAllowedSize is now 50 MB)

This is surely not the cleanest solution, but works for us at the moment. We are also trying to find a maxAllowedSize that is optimal. Hope this helps someone.

**Comment by cobbr** [comment]
Great catch @s7331 and @jannlemm0913, I wasn't aware of this limitation. I've implemented a higher maxAllowedSize for now. Fixed in dev branch.
