### ISSUE TITLE
[Bug] Add ConnectAddress is disabled in Edit mode [DEV/STABLE]

### ISSUE THREAD

**Issue by aancw** [cobbr/Covenant#310]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
Cannot add connectaddress when editing listener

**To Reproduce**
1. Go to Listener
2. Edit listener
3. Click add connectaddress

**Expected behavior**
Can add connect address like creating first listener

**Screenshots**

![image](https://user-images.githubusercontent.com/6284204/114695596-01e52c80-9d46-11eb-835c-506679468298.png)

**Covenant Server Information:**
 - OS: Linux
 - Docker or Native: Native

**Browser Information:**
 - Browser : Firefox
 - Version 87.0

**Comment by cobbr** [comment]
Hey @aancw , this is intended functionality. You would have to create a new Listener to add ConnectAddresses.

**Comment by aancw** [comment]
Ah i see, i think it's disabled because there is add button. Maybe remove add button in edit mode?

**Comment by cobbr** [comment]
The button is disabled on the edit page, correct @aancw ?

**Comment by aancw** [comment]
Yes, disabled. I was misunderstanding when I saw add button but it disabled. My bad. Maybe this issue is closed.

**Comment by cobbr** [comment]
Going to remove the Add button from the HttpListenerForm when editing. Will be reflected in the dev branch here shortly.
