### ISSUE TITLE
Feature Request - "getNetShares" being added back

### ISSUE THREAD

**Issue by ANSUUVIOUS** [cobbr/Covenant#311]
**Feature Request or Bug**
Feature Request

**Describe the feature request or bug**
The "getNetShares" command seems to be gone from the options within the interact page. I get a command not found, but a commit I saw 2 years ago had it. May this be re-added to the repo please?

**Comment by cobbr** [comment]
You are right, looks like this task got lost. Will be added back in here shortly.

**Comment by cobbr** [comment]
Fixed in dev 49d979644468380eef4d6b627550c75ff501dca8
