### ISSUE TITLE
[Bug] Package DonutCore not found

### ISSUE THREAD

**Issue by rudesec** [cobbr/Covenant#313]
**Bug**
Bug

**Describe the feature request or bug**
Can't install Convenant because package DonutCore is not available.

/app/Covenant.csproj : error NU1101: Unable to find package DonutCore. No packages exist with this id in source(s): nuget.org

https://www.nuget.org/packages/DonutCore/

**To Reproduce**
Installation via Option 1 or 2

**Comment by ameyrk18** [comment]
n1xbyte is the maintainer of this repo https://github.com/n1xbyte/donutCS

**Comment by rvrsh3ll** [comment]
Workaround: 
git clone https://github.com/n1xbyte/donutCS
cd donutCS
dotnet build
<copy Donut.dll to Covenant\refs folder>
comment the DonutCore line 

add this 

<Reference Include="DonutCore">
      <HintPath>refs\Donut.dll</HintPath>
    </Reference>

**Comment by n1xbyte** [comment]
![deleted](https://user-images.githubusercontent.com/18420902/115573850-56286900-a27e-11eb-8449-bbb611d60e93.PNG)

Trying to figure something out. For now @rvrsh3ll fix should work

**Comment by cobbr** [comment]
Fixed in 5decc3ccfab04e6e881ed00c9de649740dac8ad1

Let me know if you continue to have issues
