### ISSUE TITLE
找不到 DonutCore

### ISSUE THREAD

**Issue by Haunted-Banshee** [cobbr/Covenant#314]
C:\Users\BlackWin\Desktop\Covenant-0.6\Covenant\Covenant.csproj : error NU1101: Unable to find package DonutCore. No packages exist with this id in source(s): nuget.org

**Comment by checkymander** [comment]
https://github.com/cobbr/Covenant/issues/313 update to the most recent version, it should be fixed now.

**Comment by cobbr** [comment]
Closing as duplicate
