### ISSUE TITLE
[Bug] Command issued in Hidden grunts dont produce output

### ISSUE THREAD

**Issue by py7hagoras** [cobbr/Covenant#316]
**Feature Request or Bug**
 Bug

**Describe the feature request or bug**
Command issued in Hidden grunts don't produce output, though are tasked, but no output/

**To Reproduce**
1. Hide a grunt
2. Interact with it and issue a command like "whoami"
3. The command is tasked, but there is no output
4. UnHide the grunt
5.  Interact with it and issue a command like "whoami"
6. There is output.
7. GoTo 1

**Expected behavior**
Command issued in Hidden grunts should produce output

**Screenshots**
![image](https://user-images.githubusercontent.com/6564346/116562832-82249980-a8d1-11eb-8667-6224d808595b.png)

**Covenant Server Information:**
- OS - Linux
 - Docker 

**Browser Information:**
 - Browser Chrome

**Target Information (System that implant is running on):**
 - OS: 2016 OS

**Comment by cobbr** [comment]
Changed how "hiding" Grunts affects the model, which has fixed this issue. Fixed in dev branch.
