### ISSUE TITLE
[Feature Request] Dark Mode

### ISSUE THREAD

**Issue by TheWover** [cobbr/Covenant#32]
Can I haz a button that turns on Dark Mode for the UI?

Thanks you kind sir.

**Comment by t94j0** [comment]
I just want to add that Dark mode should be the default mode for the UI. As a l33t hacker, I typically hack at night time, so the process of changing the UI from light mode to dark mode is almost impossible because I get blinded from light mode theme.

+1 for Dark mode, but also I NEED a version of Covenant which is dark mode by default.

**Comment by cobbr** [comment]
NEVAR!!! 😛

**Comment by TheWover** [comment]
Butt then how we do the hax? l33t haxors need dark mode so they can see the code when still haxxing for hours. 
![giphy](https://user-images.githubusercontent.com/17090738/62902758-72d47580-bd15-11e9-8366-09d585dabc05.gif)

**Comment by t94j0** [comment]
I just want to say that I'm completely on board for this

**Comment by nbulischeck** [comment]
+1 for dark mode. It's becoming increasingly more popular now so it only seems reasonable to add it in as an option.

**Comment by cobbr** [comment]
@nbulischeck It seems totally **unreasonable** to me 😛

**Comment by cobbr** [comment]
In all seriousness, I think it would be a cool feature to add in a Themes feature to satisfy all of you dark mode heathens. But it might take me a while to get to this 🙂

**Comment by mrjamiebowman** [comment]
I wanted to contribute so I tried to knock this out... I'm going for the most used-useless-useful feature in Covenant. I have a PR in that meets the minimal requirements for Dark Mode functionality. There's room to grow but the base functionality is there... Could use some more testing.. happy to work through bugs, changes, etc.

https://github.com/cobbr/Covenant/pull/127

https://github.com/mrjamiebowman/Covenant/tree/dev-themes

**Comment by TheWover** [comment]
Heathen mode now supported in v0.6. Welcome to the dark side.

**Comment by cobbr** [comment]
Thanks for the head start on this one @mrjamiebowman. I have been defeated...

**Comment by mrjamiebowman** [comment]
Aweesome!!!!! 🥳
