### ISSUE TITLE
[Bug] Assembly SharpGPOAbuse kills grunt

### ISSUE THREAD

**Issue by T35R6braPwgDJKq** [cobbr/Covenant#339]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
```
Assembly /assembly:"" /assemblyname:"SharpGPOAbuse" /parameters:"--AddComputerTask --TaskName \"TASK\" --Author NT AUTHORITY\SYSTEM --Command \"cmd.exe\" --Arguments \"/c net localgroup Administrators user /delete\" --GPOName \"test\""
```
just cloned the sharpgpoabuse repo and executed the above.
The grunt will go offline the task will be in state "Assembly tasked"

**Covenant Server Information:**
 - OS: kali
 - Docker or Native: docker, dev branch

**Browser Information:**
 - Browser firefox

**Target Information (System that implant is running on):**
 - OS: Microsoft Windows Server 2012 R2 Standard

apprently https://github.com/ZeroPointSecurity/SharpGPOAbuse was a fix, but it was removed.

Edit:
It does not matter whether the launcher is .net40 or .net35 (as well as sharpgpoabuse.exe)

```
powershell .\SharpGPOAbuse.exe ...
```
works though

**Comment by rasta-mouse** [comment]
I suspect this is not an issue with the Grunt, but SharpGPOAbuse itself.  If you review the source code, there are multiple instances where it calls `System.Environment.Exit(0);`

**Comment by cobbr** [comment]
`Environment.Exit()` is evil

**Comment by T35R6braPwgDJKq** [comment]
thanks - thats was the right hint;
