### ISSUE TITLE
Task is always in uninitialized status

### ISSUE THREAD

**Issue by bhaizlett123** [cobbr/Covenant#34]
Everytime i create a task, it was stays in uninitialized status? any way to force it run? Also is there a way to kill a specific task on a grunt? did not see that option anywhere

**Comment by cobbr** [comment]
Hey @bhaizlett123, can’t say that I’ve ever seen this issue. Sounds like you are trying to interact with a Grunt that has stopped calling back. Are you sure that Grunt is still connected?

**Comment by cobbr** [comment]
Closing for now, if you are still having issues I can reopen.

**Comment by mpgn** [comment]
Hello

I got the same error, when launching a simple task like "WhoAmI" :

![image](https://user-images.githubusercontent.com/5891788/65413818-8e419e80-ddf2-11e9-9ae1-6c949bcabb91.png)

And I had this error on the console output of Covenant:

![image](https://user-images.githubusercontent.com/5891788/65413970-fee8bb00-ddf2-11e9-877f-cfa9f7390035.png)


Then I restart Covenant and everything was working fine :+1:

**Comment by whoami-ru** [comment]
I have the same problem. When i start new grunt and input command like screenshot it works properly. However, if i run command "ShellCmdRunAs" it stay with status "Uninitialized" and then all commands are standing with status "Uninitialized".
For more information, i run Binary Grunt from cmd, in cmd there is errors like:

Loop Exception: System.Net.WebException The remote server returned an error: (404) Not found.
   in System.Net.WebClient.DownloadDataInternal (Uri address, WebRequest & request)
   in System.Net.WebClient.DownloadString (Uri address)
   at GruntExecutor.HttpMessenger.Read ()
   in GruntExecutor.TaskingMessenger.ReadTaskingMessage ()
   in GruntExecutor.Grunt.Execute (String CovenantURI, String CovenantCertHash, String GUID, Aes SessionKey)
![pct](https://user-images.githubusercontent.com/60693100/75666163-8fc79a80-5c9f-11ea-8e2e-e5360c664d9d.png)
![pct1](https://user-images.githubusercontent.com/60693100/75666274-ba195800-5c9f-11ea-864b-9dced939dd5a.png)

**Comment by funappfactory** [comment]
Got the same issue, after configuring Date and Time Zone, it worked.

**Comment by cybertuxh4xor** [comment]
> Got the same issue, after configuring Date and Time Zone, it worked.
How do you do that?
i am running into the same issues 
uninitialized on any command i run

**Comment by cybertuxh4xor** [comment]
i do not see how to fix the issue in this post

**Comment by abraidotti** [comment]
@funappfactory  I understand how to set the time zone, but what do you mean by "configuring" the date? The date seems right.

**Comment by AppSecExplained** [comment]
same issue here

**Comment by Kx1z0** [comment]
> Got the same issue, after configuring Date and Time Zone, it worked.

Same issue here. What you mean with "configuring" the date? [funappfactory](https://github.com/funappfactory)

**Comment by wglobke** [comment]
I have the same issue. Could it be that the reason is that the target machine does not have the right .NET Framework version installed?

**Comment by NaseebHelali** [comment]
I had the same problem, I solved it by deleting the covenant copy on docker and rebuilding it again. It worked without deleting the previous data.
