### ISSUE TITLE
Commands do not run

### ISSUE THREAD

**Issue by trickster0** [cobbr/Covenant#35]
Commands do not run on the agents. I used shell and shellcmd for running whoami but i got this error:

"Task Exception: Could not load file or assembly '25088 bytes loaded from 4sefqqcl.0bj, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format. at System.Reflection.RuntimeAssembly.nLoadImage(Byte[] rawAssembly, Byte[] rawSymbolStore, Evidence evidence, StackCrawlMark& stackMark, Boolean fIntrospection, Boolean fSkipIntegrityCheck, SecurityContextSource securityContextSource) at System.Reflection.Assembly.Load(Byte[] rawAssembly) at GruntExecutor.Grunt.TaskExecute(TaskingMessenger messenger, GruntTaskingMessage message)"

This is Ubuntu 19.04 x64
I got the victim back through powershell encoded command.

**Comment by cobbr** [comment]
Hey @trickster0, have not seen this issue before. Can you provide your host OS, target OS, .NET version, and browser version?

**Comment by cobbr** [comment]
@trickster0 Can you confirm that you cloned Covenant recursively using `git clone --recurse-submodules https://github.com/cobbr/Covenant`?

**Comment by trickster0** [comment]
Hey @cobbr i found the problem but i dont know why it happens. Indeed the submodules didn't download. There is no src directory or the cloned dir's from tools that are being used by the tasks.
Although i did git clone --recurse-submodules https://github.com/cobbr/Covenant .
I do not know why this happens. I tried it again.

**Comment by cobbr** [comment]
@trickster0 Is it working now that you have tried again?

**Comment by trickster0** [comment]
Hey @cobbr , this guy has the same issue as me https://github.com/cobbr/Covenant/issues/41
So i reinstalled and the error persists. What is interesting is that when you git clone, the modules from this file https://github.com/cobbr/Covenant/blob/master/.gitmodules are not getting cloned.
So when you actually run it , they are not there. Also src directory does not exist in the Tasks directory.
I tried manually cloning them there and when i did dotnet build errors came raining.
Tell me if i can assist you somehow so it will be resolved.

**Comment by cobbr** [comment]
Hey @trickster0, cloning with `git clone --recurse-submodules https://github.com/cobbr/Covenant` should pull the submodules.

If that does not work then you can try `git submodule update --init --recursive` after cloning.

Can you also tell me what version of git you are using? `git --version`

**Comment by trickster0** [comment]
It still did not work getting the rest of the modules.
Git version is 2.20.1

**Comment by cobbr** [comment]
Did you get output from the `git submodule update --init --recursive` command?

**Comment by trickster0** [comment]
no, nothing

**Comment by panagioto** [comment]
@trickster0 Can you check if the submodules exist within "Covenant/Data/ReferenceSourceLibraries" ?

**Comment by trickster0** [comment]
They do!

**Comment by cobbr** [comment]
It looks as if I have inadvertently converted the submodules into normal directories by changing their folder location.

I'll address that issue, but I don't believe that is the cause of your issue @trickster0. I think you are running into problems with AMSI

**Comment by trickster0** [comment]
Hey indeed, i did what you mentioned and disabled Windows Defender.. It works now, too bad that it gets detected. Let me take this opportunity to thank you for this nice C2 and also would be great to add sharpview as well :) I am closing this since the issue was Windows Defender.
Cheers.

**Comment by cobbr** [comment]
Yeah may be need to add in some AMSI bypasses. SharpView could be a good add too 👍
