### ISSUE TITLE
[Bug] Swagger endpoint missing

### ISSUE THREAD

**Issue by archmangler** [cobbr/Covenant#352]
**Feature Request or Bug**

When  accessing the swagger endpoint as in the documentation () I get the following response in the browser:

"Page not found
Sorry, but there's nothing here!"

I can access the api directly though.

**Describe the feature request or bug**

Make Swagger available, or provide complete CURL-based examples of every API operation possible.

**To Reproduce**

On a new new, docker based installation of Covenant,  Go to  "https://127.0.0.1:7443/swagger/"

**Expected behavior**

The swagger UI should be available as documented in the Covenant API documentation.

**Screenshots**

![image](https://user-images.githubusercontent.com/3898404/151488270-ee08b285-348e-417f-8b7e-d9644d7999e3.png)

**Covenant Server Information:**
 - OS: MacOS Monterey
 - Docker

**Browser Information:**
 - Browser Chrome, Firefox, Safari
 - Version all

**Target Information (System that implant is running on):**
 - OS: MacOS Monterey
 - Version all

**Additional context**

n/a

**Comment by rasta-mouse** [comment]
I didn't try it in Docker specifically, but the URI should be `/swagger/index.html`.

**Comment by archmangler** [comment]
HI @rasta-mouse, I get blank:

![image](https://user-images.githubusercontent.com/3898404/151674827-eae4bcc9-ab0d-4373-9327-252768ce0772.png)


Just a white screen.

**Comment by ghost** [comment]
Swagger only works in development mode. 
```docker run -it -p 7443:7443 -p 80:80 -p 443:443 -e ASPNETCORE_ENVIRONMENT=Development --name covenant -v </absolute/path/to/Covenant/Covenant/Data>:/app/Data covenant```

**Comment by archmangler** [comment]
Thanks @SecurityAndStuff
