### ISSUE TITLE
[Question =-D] How to update mimikatz on covenant master branch?

### ISSUE THREAD

**Issue by UserXGnu** [cobbr/Covenant#358]
So, I'd like to update mimikatz to my build of covenant, I'm using the master branch and it has that old mimikatz bug when using logonpasswords.

I've tried compiling mimikatz using second_release, copying the dlls and also tried using Out-CompressedDll.ps1 to generate the .dll.comp in the /resource folder for sharpsploit.

I've also tried just copying the whole sharpsploit, and yaml tasks from the dev branch into my build (which is using master branch).

Eitherway, covenant freezes and then I get this error message:

![unknown](https://user-images.githubusercontent.com/2071597/160560578-41bc77a5-8d16-48ae-8988-07c8a03c33f8.png)

Don't really know how to go about doing this. Any help would be much appreciated.

P.S.: If this is not the right spot to ask for help, let me know, and sorry in advance.

**Comment by rasta-mouse** [comment]
https://offensivedefence.co.uk/posts/covenant-powerkatz/

**Comment by UserXGnu** [comment]
Thank you man! It worked just fine!
