### ISSUE TITLE
how to install by docker

### ISSUE THREAD

**Issue by smallfox233** [cobbr/Covenant#364]
what is "/app/Data"?
</absolute/path/to/Covenant/Covenant/Data>:/app/Data

**Comment by jannlemm0913** [comment]
That should just be a directory inside your Docker container. From Covenant's wiki on Docker installations: "The -v parameter creates a shared Data directory between the host and the container."  
I don't run Covenant from a container, but I would guess that folder is already part of the container image that you can download and build, or is there an error when you run the command?

**Comment by smallfox233** [comment]
> That should just be a directory inside your Docker container. From Covenant's wiki on Docker installations: "The -v parameter creates a shared Data directory between the host and the container." I don't run Covenant from a container, but I would guess that folder is already part of the container image that you can download and build, or is there an error when you run the command?

thank you
