### ISSUE TITLE
[Bug] Incorrect date and time in Covenant

### ISSUE THREAD

**Issue by Kx1z0** [cobbr/Covenant#373]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
The time used by covenant is one hour behind the system time. (The system time is set automatically)

**Expected behavior**
 Covenants time should be the system time to avoid errors such as uninitialised tasks.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/62154723/206764097-338f24f4-49d4-46fd-b24c-0aab0fd9a352.png)
Because of this, the tasks I run are never executed and remain uninitialised.

**Covenant Server Information:**
 - OS: Windows 11
 - Docker or Native: Native

**Browser Information:**
 - Browser: Firefox
 - Version: 107.0.1

**Comment by rasta-mouse** [comment]
Covenant dates are in UTC not your local time, which I believe is by design.  Your system is UTC +1, hence the hour difference.

**Comment by Kx1z0** [comment]
Okay, ty
