### ISSUE TITLE
DCOMCommand Task Template Issue

### ISSUE THREAD

**Issue by bashexplode** [cobbr/Covenant#42]
The default task template for DCOMCommand always receives a "Parameter count mismatch" error when a task is issued. I created a workaround by using the same code and creating the following options:

0. ComputerName
1. Command
2. Parameters
3. Directory
4. Method

This properly executes the command along with the forked commit I made to change the string comparisons to lowercase rather than CamelCase.

I believe default values for the above options can be used to ease the user:

3. Directory = C:\\Windows\\System32\\
4. Method = MMC20.Application

In SharpSploit I have just been using the Command argument to = "cmd.exe", and prepending the Parameters argument with "/c " so that any command being input just appends to Parameters and doesn't touch Command, but I'll let you make the decision there.

**Comment by cobbr** [comment]
Thanks for the report @bashexplode! I believe I have fixed this in 886d6a04a5b6bb2ab96c50b35a603cc95971252c

Had to fix some cli parsing and there was some inconsistencies between using the Task tab or Interact tab.

Also added DefaultValues for the parameters you mentioned.

Could you re-pull and re-test and let me know if it works for you now?

**Comment by cobbr** [comment]
Closing for now, let me know if this issue persists and we can re-open.
