### ISSUE TITLE
[Issue] InstallUtil Launcher Download Output Format

### ISSUE THREAD

**Issue by 1upo** [cobbr/Covenant#47]
Output format is currently a b64 .xml when using the web GUI generate -> download.
Assuming that this should instead be a binary dll?

**Comment by cobbr** [comment]
Ooops! Thanks for the heads up @1upo. I'll take a look at this.

**Comment by cobbr** [comment]
Fixed in 60c187c6a0d9c2669630f0f5c1f92e0210ebc403!

Thanks for reporting @1upo!
