### ISSUE TITLE
Covenant first launch fail

### ISSUE THREAD

**Issue by acarnage** [cobbr/Covenant#5]
Hello,

I have this error while trying to launch Covenant with docker, it happens just after the password entry : 

> Unhandled Exception: System.IO.FileNotFoundException: Could not find file '/app/appsettings.json'.
>    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
>    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
>    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
>    at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
>    at System.IO.File.InternalReadAllText(String path, Encoding encoding)
>    at System.IO.File.ReadAllText(String path)
>    at Covenant.Program.<>c.<BuildWebHost>b__1_1(WebHostBuilderContext hostingContext, IConfigurationBuilder config) in /app/Covenant.cs:line 152
>    at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
>    at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
>    at Covenant.Program.<>c__DisplayClass0_0.<Main>b__0() in /app/Covenant.cs:line 73
>    at Covenant.Program.Main(String[] args) in /app/Covenant.cs:line 119

Any help ? :)

**Comment by cobbr** [comment]
oops! Not sure how it happened, but it appears that this file had disappeared from the project. Thanks for the heads up @acarnage!

Fixed as of: fed7037d200a32b1c0864f00395f72271c5abf70

Let me know if you have any more issues.
