### ISSUE TITLE
[Question] How to update database

### ISSUE THREAD

**Issue by itpropro** [cobbr/Covenant#51]
I want to implement the other persistence functions from PowerSploit, but I can only get the new tasks to show in the ui after deleting the covenant.db file. Is there any other way to inline update the database with the new created tasks?

**Comment by cobbr** [comment]
@itpropro You can create new Tasks through the interface or through the API. Instructions to add a new Task through the interface can be found here: https://github.com/cobbr/Covenant/wiki/Building-Tasks

**Comment by itpropro** [comment]
I have already implemented tasks using the wiki guide. I added them to the DbInitializer file and added the task file. They just don't show in the GUI before wiping the database.

**Comment by cobbr** [comment]
The Task Contribution Guide is for creating new built-in Tasks. The main purpose of this is to contribute tasks back to the Covenant project, and to have new default tasks on initial Covenant startup. These will not be automatically imported into the database until the database is wiped and Covenant is restarted.

To add new Tasks to a running instance of Covenant, follow the Building Tasks guide and add them through the interface: https://github.com/cobbr/Covenant/wiki/Building-Tasks

**Comment by itpropro** [comment]
Thanks a lot! I am quite new to programming C# :)

**Comment by cobbr** [comment]
No worries! I definitely want to continue to make the development and contribution process as easy as possible. Open to any suggestions you have on how to make this easier 🙂
