### ISSUE TITLE
Cannot add custom HttpRequestHeaders

### ISSUE THREAD

**Issue by n0auth** [cobbr/Covenant#52]
When creating or editing a Listener profile the functionality to add addition `HttpRequestHeaders` does not do anything. Not sure if this as expected but I have tried editing the default `HttpProfile` as well as creating a custom profile.

**Comment by cobbr** [comment]
No, this is not expected behavior. Can you provide some more information?

What header are you trying to add? Do you get an error message? What is the behavior when you try to add the header? Are you editing a profile that is associated with an active listener?

**Comment by n0auth** [comment]
Hey, thanks for the reply.
I just want to add a custom cookie that my listener will listen for. There is no error message at all. Here is a quick screencast.

![Screencast from 09-10-2019 03_44_33 PM](https://user-images.githubusercontent.com/50678852/64645494-06679780-d3e3-11e9-8c95-67c008e38728.gif)

**Comment by cobbr** [comment]
This is a silly bug 🤦‍♂ Fix incoming.

**Comment by cobbr** [comment]
Okay try out ade119f8445c7f639c2e452f6706879ae16966b0

**Comment by cobbr** [comment]
Closing for now, let me know if the issue persists.
