### ISSUE TITLE
No data available in Grunts

### ISSUE THREAD

**Issue by slamet404** [cobbr/Covenant#53]
Hi Bro

I already set listeners and im create Launcher file  Binary 

![Screenshot from 2019-09-12 17-21-29](https://user-images.githubusercontent.com/5875641/64776385-50d34a80-d582-11e9-80a3-c437ee65307d.png)

im send to windows 7 file GruntStager.exe

But in Grunts not data available 

![Screenshot from 2019-09-12 17-21-54](https://user-images.githubusercontent.com/5875641/64776384-503ab400-d582-11e9-8703-e9fb63820139.png)

Any solutiosns ?

**Comment by slamet404** [comment]
hi cobbr

this pictures execute GruntStager.exe from a cmd.exe or powershell.exe

![Screenshot from 2019-09-14 22-00-35](https://user-images.githubusercontent.com/5875641/64909862-5cb63c80-d73b-11e9-887b-6850262d96a1.png)


Any Solutions ?

**Comment by cobbr** [comment]
Usually this indicates a routing issue. What is the IP address of the Covenant server and of the Windows machine? Can you ping the Covenant IP from the Windows machine?

**Comment by slamet404** [comment]
Hi cobbr

im set ping normal / respon

![Screenshot from 2019-09-15 11-52-11](https://user-images.githubusercontent.com/5875641/64916809-ea337400-d7af-11e9-9c77-123f14589513.png)

![Screenshot from 2019-09-15 11-57-54](https://user-images.githubusercontent.com/5875641/64916814-12bb6e00-d7b0-11e9-9a48-c463ae0f93e2.png)

**Comment by slamet404** [comment]
hii cobbr

any update ?

I have not found a solution this case

are there any mistakes ?

**Comment by cobbr** [comment]
Hi @slamet404 I have not been able to reproduce the issue. It seems to be a routing issue, which makes it difficult for me to say what the issue is.

Can you check your incoming firewall rules on the Covenant server? Is it possible you are restricting port 8060?

What OS are you running your server on?

**Comment by cobbr** [comment]
Ahh i have a guess. Are you running Covenant in a docker container?

**Comment by slamet404** [comment]
Im Running Covenant in Ubuntu 18.04

and question : Ahh i have a guess. Are you running Covenant in a docker container?

Yes im running in docker 

![Screenshot from 2019-09-16 22-20-27](https://user-images.githubusercontent.com/5875641/64970531-34ac1200-d8d0-11e9-87d9-22c13374a1bc.png)

**Comment by cobbr** [comment]
Ok so when you use Docker you need to forward any external port into the container. So you need to do something like: `docker run -it -p 7443:7443 -p 8060:8060 --name covenant -v /opt/Covenant/Covenant/Data:/app/Data covenant`

You'll also need to be sure the port is listed in the `Dockerfile`. The default Dockerfile looks like this:
```
FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /app

COPY . ./
RUN dotnet publish -c Release -o out

FROM microsoft/dotnet:2.2-aspnetcore-runtime AS runtime
WORKDIR /app
COPY --from=build /app/out .
COPY ./Data ./Data
EXPOSE 7443 80 443
ENTRYPOINT ["dotnet", "Covenant.dll"]
```

You'll need to add `8060` to the EXPOSE list if you intend to use it as an external port.

Last note, I would recommend *not* using Docker unless you are pretty familiar with it. There are a lot of subtle gotchas.

**Comment by slamet404** [comment]
Sorry 

I wasn't careful reading the Installation-And-Startup

Oke this Fix and Running Grunt

Thanks cobbr

**Comment by cobbr** [comment]
Great! Glad you got it working @slamet404 🙂
