### ISSUE TITLE
[Feature Request] Modify/Delete Credentials/Indicators/Downloads/Screenshots within the Web Interface

### ISSUE THREAD

**Issue by itpropro** [cobbr/Covenant#54]
I would really love to have some way in the UI to modify or delete entries in the Data section. I think it would alternatively make sense to be able to purge everything to start over with a "fresh" covenant.
Is there any guidance for UI modifications? I could try to at least implement the purge functionality.

**Comment by cobbr** [comment]
Feature has been added. Changes currently in dev branch.
