### ISSUE TITLE
[Docs][Issue] Binary Launcher Comms

### ISSUE THREAD

**Issue by elreydetoda** [cobbr/Covenant#56]
In the wiki under the Launchers section the picture and description for the configuration option of CommType appears to have changed to Template in the most recent version of Covenant.

Here is the affected location (as close as I could get it): https://github.com/cobbr/Covenant/wiki/Launchers#binary-launcher

Picture as to why submitting issue
![image](https://user-images.githubusercontent.com/10230166/64949103-74c6b280-d846-11e9-8a55-2989e50e54b9.png)

**Comment by cobbr** [comment]
thanks @elreydetoda!

**Comment by elreydetoda** [comment]
No problem! I really appreciate the good documentation!
I am doing a webinar to show a comparison of all different C2 projects and documentation has been a pain point, so thank you!

So I have a question, you tagged this as _help wanted_ and _good first issue_, but is it possibly for anyone to submit a PR for this since it is in the wiki?

**Comment by cobbr** [comment]
@elreydetoda Ahh good point, I'm really not sure! You are probably correct.

**Comment by elreydetoda** [comment]
That was a good idea though! I only know that you can't,  because before I submitted an issue I was trying to see if I could submit a pull request or something. :smile: I couldn't find a way, but I just might not have seen it.

**Comment by cobbr** [comment]
Hey @elreydetoda, I came up with a workaround for this.

I've created a new repo for the [Wiki](https://github.com/cobbr/Covenant-wiki), which accepts Pull Requests. This Wiki will be kept even with Covenant's "real" Wiki.

**Comment by elreydetoda** [comment]
That's awesome! You might want to think about creating a CONTRIBUTING.md, and linking to the other repo to tell them how to fix docs issues. That way if they go to create an issue it will notify them they should checkout the CONTRIBUTING.md and see where to go for docs issues.

**Comment by cobbr** [comment]
Thanks @elreydetoda, that's a good idea as well 🙂

**Comment by cobbr** [comment]
Docs have been updated!
