### ISSUE TITLE
Build fails: Step 4/10 : RUN dotnet publish -c Release -o out

### ISSUE THREAD

**Issue by stlorenz** [cobbr/Covenant#58]
After starting fresh to root out errors in my other issue, the Build fails in Step 4/10 with the 

following error message:
```Step 4/10 : RUN dotnet publish -c Release -o out
 ---> Running in aa739e9eaf98
Microsoft (R) Build Engine version 16.2.32702+c4012a063 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

/usr/share/dotnet/sdk/2.2.402/NuGet.targets(123,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [/app/Covenant.csproj]
/usr/share/dotnet/sdk/2.2.402/NuGet.targets(123,5): error :   Resource temporarily unavailable [/app/Covenant.csproj]
The command '/bin/sh -c dotnet publish -c Release -o out' returned a non-zero code: 1
`

**Comment by cobbr** [comment]
@stlorenz This usually indicates a networking issue on your host during nuget package retrieval. I'd check on your internet connection and try again.

**Comment by stlorenz** [comment]
I have a working connection for every other task on the machine. 
Ping an wget work too

``wget https://api.nuget.org/v3/index.json 
--2019-09-18 09:00:48--  https://api.nuget.org/v3/index.json
Resolving api.nuget.org (api.nuget.org)... 152.199.23.209
Connecting to api.nuget.org (api.nuget.org)|152.199.23.209|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7557 (7.4K) [application/json]
Saving to: 'index.json'

index.json   100%   7.38K  --.-KB/s    in 0s      

2019-09-18 09:00:48 (148 MB/s) - 'index.json' saved

**Comment by stlorenz** [comment]
nvm. THe docker interface did not work properly. Fixed
