### ISSUE TITLE
ConnectAttempts behaviour

### ISSUE THREAD

**Issue by charlieMKR** [cobbr/Covenant#59]
The ConnectAttempts parameter, as defined in the wiki,  is the number of consecutive times a grunt will attempt to poll the listener before quitting. If a grunt cannot reach the listener and fails to successfully poll the listener more times than the ConnectAttempts value, it will quit.

The grunt quits even if it's reaching the listener (at least if it's not receiving any command from the operator). You can reproduce this by reducing the ConnectAttempts to 10. The grunt stops polling after a minute of no interaction, even if the listener is answering correctly. IS this the expected behaviour?

**Comment by cobbr** [comment]
@charlieMKR That is not expected behavior.

I'll try to reproduce and get in a fix ASAP if I can confirm.

**Comment by cobbr** [comment]
I think I've fixed this in f36feb12f89a19fdb1ec6e2c87dca467ac384a7a. Was an easy enough fix, not sure how this got messed up. Thanks for the heads up, glad we addressed this.

Can you test and confirm it's working for you @charlieMKR?

**Comment by charlieMKR** [comment]
Looks like it's fixed now :) Thanks!
