### ISSUE TITLE
[Question] What kind of an environment are you using?

### ISSUE THREAD

**Issue by daimalkogaz** [cobbr/Covenant#60]
I would assume a VM sandbox, but what OS?

**Comment by cobbr** [comment]
Hey @daimalkogaz , I don't really know what you are asking. Can you elaborate a little bit?

**Comment by cobbr** [comment]
Closing for now. Can re-open if more information is provided.

**Comment by daimalkogaz** [comment]
> Hey @daimalkogaz , I don't really know what you are asking. Can you elaborate a little bit?

What I wanted to know was which OS are you using for experiment and playing around with the framework? Personally I am using a Win7 distro on a VM. But I was wondering is there something better and faster one might use as a sandbox?

**Comment by cobbr** [comment]
I've tested on lots of different configurations of VMs and OSs. If you are just using as a sandbox, I'd say it's up to personal preference.
