### ISSUE TITLE
ScreenShot

### ISSUE THREAD

**Issue by Pickfordmatt** [cobbr/Covenant#61]
Hi,

Loving the work, I'm having a slight issue screenshooting within Windows 10 64bit where it only captures the top 1/4 of the screen. Is this a known issue or am I doing it wrong?

Thanks,
Matt

<img width="1026" alt="Screenshot 2019-09-21 at 15 58 43" src="https://user-images.githubusercontent.com/3343862/65375033-b57c5c80-dc88-11e9-9516-9c23780a3e8d.png">

**Comment by cobbr** [comment]
Hey @Pickfordmatt, it is not a known issue. Can you share some details about your target system?
Please provide: OS version, screen resolution size, are you using multiple monitors

**Comment by Pickfordmatt** [comment]
Well it’s a virtual machine, Windows 10 64-bit, 1920x1080 res. Currently run under VMWare Fusion for Mac. The more I write the more I realise this is quite a niche setup.

**Comment by cobbr** [comment]
Well, oddly enough, I have the same setup @Pickfordmatt. But I am not able to reproduce the issue unfortunately 🙁 

Can you share a screenshot running the screenshot task in the Interact menu?

**Comment by mpgn** [comment]
I've tested this module today on a Windows 10 x64, working like a charm on my side.

**Comment by cobbr** [comment]
Must be something specific about your VM @Pickfordmatt.

Can you share the screenshot whenever you have a chance? Also, do you have any other non-standard display configurations set in Fusion?

**Comment by Pickfordmatt** [comment]
I've updated VMWare tools and it seems to have fixed the problem, sorry for wasting any time. Cheers

**Comment by cobbr** [comment]
Strange! Glad it's working now. If you run into this again let me know, and we can re-open the issue.
