### ISSUE TITLE
[Bug] BindPort is set to ConnectPort when restarting a listener

### ISSUE THREAD

**Issue by emiltayl** [cobbr/Covenant#63]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
I have been playing with Covenant and listeners with a BindPort different from its ConnectPort. When I create new listeners they are started on the correct port (BindPort). However if I restart the listener either through the web interface or by restarting Covenant, the listeners seems to start up listening to the ConnectPort.

In the SQLite database, it seems like the BindPort is set correctly initially (although the interface displays the ConnectPort in the BindPort field), but when the listener is restarted, the BindPort is changed in the database as well.

**To Reproduce**
1. Create a new listener with BindPort 9876 and ConnectPort 6789
2. `netstat -pln` will show that Covenant is listening to port 9876
3. Restart the listener either by restarting Covenant or by restarting the listener in the interface
4. `netstat -pln` will now show that Covenant is listening to port 6789
5. The BindPort seemingly also gets updated in the database, changing BindPort to 6789

**Expected behavior**
The BindPort should not change when restarting the listener. The interface should also display the correct BindPort.

**Covenant Server Information:**
 - OS: Debian 10 (stable)
 - Docker or Native: Native

**Browser Information:**
 - Firefox 69.0.1

**Additional context**
Built from the latest commit (02b221a)

**Comment by emiltayl** [comment]
https://github.com/cobbr/Covenant/blob/02b221a/Covenant/Models/Listeners/HttpListener.cs#L94 seems to be the culprit, at least I got the expected behavior on the server when commenting out that line. I have not had time to test this thoroughly though, so I do not know if removing that line breaks anything.

**Comment by cobbr** [comment]
Thanks for the heads up and for hunting this down @emiltayl! 🙂 

Will get in a fix here soon.

**Comment by cobbr** [comment]
I think I've fixed this in f36feb12f89a19fdb1ec6e2c87dca467ac384a7a

Can you check to see if it's working for you now @emiltayl?

**Comment by emiltayl** [comment]
That seemed to fix it, I'm not able to reproduce the original bug after the latest changes. As an added bonus, the code changed to fix this makes more sense to me now than it did before the fix (although I am not very familiar with this code base _yet_).
