### ISSUE TITLE
[Bug|Feature Request] When the grunt restarted, the ID(Grunt Name) changed. How to avoid?

### ISSUE THREAD

**Issue by c0me0nb0y** [cobbr/Covenant#64]
I ran a grunt, and I can see it with an ID(Grunt Name). That's great.
But when I restarted the grunt, its ID changed. The Note I had wrote gone at the same time. And it's seems to there are two grunts, and two grunts in the graph .

So, Is there a way that when I restart the grunt, the ID of the grunt will not change?
Or was it not designed with this feature? Or I did not use it in a right way?

So I'm not sure if this is a Bug or a Feature Request.

**Comment by cobbr** [comment]
@c0me0nb0y Did you kill the Grunt and then launch the same binary again?

If so, this is expected behavior. Each new run of a launcher results in a unique Grunt. This is necessary so that you can use the same payload multiple times.

**Comment by cobbr** [comment]
Closing for now. Let me know if I have misunderstood the issue.

**Comment by c0me0nb0y** [comment]
Hello, cobbr. Thank you very much for your answer. You didn't get me wrong. Your idea is also great.

Now let's assume such a situation. I controlled three machines and renamed them A, B, C with detailed annotations. And I added persistence to them.
One day, three machines restarted, I want to distinguish them, only can rely on the previous IP, user name and other information, and then rename the 3 grunts, re-annotate them, and delete the previous grunts.
This is troublesome.

Can you start such a branch so that the ID of the same machine **remains unchanged** when it goes online again? Thank you!

I'm not familiar with C # and asp. So if you don't like the changes above, can you give me some **suggestions**? In fact, I've already started to do this. I'm just having a headache with the asynchronous communication of C#, and I haven't found out how the ID of the server is generated. And I cannot compile it in visual studio, so I don't know how to debug it.

Look forward to your reply. I would appreciate it if you could improve it or give me some suggestions.
