### ISSUE TITLE
how to hide files GruntStager.exe ? 

### ISSUE THREAD

**Issue by slamet404** [cobbr/Covenant#65]
Hii

sorry question again

how to hide files GruntStager.exe not running in cmd

because every cmd im close the listener also close

how hidden file GruntStager.exe but service grunts still running

thanks
![f280527e-f0c2-4b75-a2fe-06d2e19deab2](https://user-images.githubusercontent.com/5875641/65401450-5cc8d300-ddf2-11e9-8fdf-54a001cdf63e.jpeg)

**Comment by cobbr** [comment]
Hi @slamet404 , the Grunt does not automatically hide the window it's executed in. You can modify the `ImplantTemplate` with code that will hide the windows if you choose to do so.

Also, please use the Issue Template for future issues! It really helps me to understand the problem and hep diagnose. Thanks!
