### ISSUE TITLE
PersistAutoRun - Name & Value

### ISSUE THREAD

**Issue by Pickfordmatt** [cobbr/Covenant#68]
The PersistAutoRun task puts the Name and Value parameters the wrong way around, the location of the executable will be set to the name and vice versa.

**Comment by rasta-mouse** [comment]
lol fail.  I'm happy to fix this one @cobbr since it's my dumb Task in the first place.

**Comment by cobbr** [comment]
That would be fantastic! Thanks @rasta-mouse 🙂

**Comment by Pickfordmatt** [comment]
Happy days!

**Comment by cobbr** [comment]
Hey @Pickfordmatt , I think I've fixed this in 2192187412636af7ea1528e8c6d86a256ddd9f69

Could you re-pull and re-test to confirm it is working as expected?

**Comment by Pickfordmatt** [comment]
Yep fixed for me, thanks both

**Comment by cobbr** [comment]
Great! Thanks for the heads up @Pickfordmatt 🙂
