### ISSUE TITLE
[Bug] "Illegal characters in path" on payload execution.

### ISSUE THREAD

**Issue by Ls094id** [cobbr/Covenant#69]
Hiya, 

After working for some time, my launchers began giving me "Illegal characters in path" upon payload execution. This happens irrespective of SSL configuration (on or off), IP or hostname in connect address, and port number. I've tried tearing down the docker, and the entire machine, changing IPs and hosts, and rebuilding to no avail. This seems to happen with powershell, binary, MSBUILD, and InstallUtil, but I haven't tested every single launcher. 

I'm running on Ubuntu 18.04. Sandbox machines where the payload was tested were Win 10 and Win 7. I've tried dotnet 3.5 and 4.0. NetCore21 returns a black screen to me when I hit generate. 

Here's the issue with an unobfuscated powershell launcher:
![Capture](https://user-images.githubusercontent.com/55753368/65524214-0f606a80-deb3-11e9-857b-a5dfaf6ed1e7.PNG)

Thanks!

**Comment by cobbr** [comment]
Hey @Ls094id could you please use the provided Issue Template? It really helps me diagnose the issue. Going to close this one.
