### ISSUE TITLE
mscorlib: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by notonlybytes** [cobbr/Covenant#7]
Launchers/Grunts, which are using a COM activated Delegate throw a "mscorlib: Object reference not set to an instance of an object."

**Comment by cobbr** [comment]
Confirmed as a bug. Thanks @notonlybytes

**Comment by cobbr** [comment]
Hey @notonlybytes, I'm actually not 100% sure that this is a bug.

What OS are you trying to establish a Grunt on? I think that Windows 10 may have changed some things that broke the DotNet2JScript-based launchers in the latest version of Win10.

Could you test this on a lower OS version like Win 7/8.1? Seems to be working for me on those or lower versions of Win10 (not sure where the line is).

**Comment by notonlybytes** [comment]
Hi @cobbr, thanks for additional information / hints. Tests were mainly conducted in a Win10 environment, probably RS4, but I don't have the details anymore. Unfortunately I can't currently dive deeper to give you additional results. But keep the next Covenant versions coming nevertheless ;)

**Comment by cobbr** [comment]
will do! thanks @notonlybytes
