### ISSUE TITLE
[Bug] "Illegal characters in path" on payload execution

### ISSUE THREAD

**Issue by Ls094id** [cobbr/Covenant#70]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
After working for some time, my launchers began giving me "Illegal characters in path" upon payload execution. This happens irrespective of SSL configuration (on or off), IP or hostname in connect address, and port number. I've tried tearing down the docker, and the entire machine, changing IPs and hosts, rebuilding, and multiple browsers to no avail. This seems to happen with powershell, binary, MSBUILD, and InstallUtil, but I haven't tested every single launcher.

**To Reproduce**
1. Go to 'Launchers > Powershell'
2. Fill out connection/Launcher information
3. Hit generate
4. Copy code to test endpoint
5. Run generated code in Powershell

**Expected behavior**
Payload execution, C2 callback

**Screenshots**
![65524214-0f606a80-deb3-11e9-857b-a5dfaf6ed1e7](https://user-images.githubusercontent.com/55753368/65529841-80f0e680-debc-11e9-9610-9d61e12aeead.png)

**Covenant Server Information:**
 - OS: Ubuntu 18.04 LTS
 - Docker or Native: Native

**Browser Information:**
 - Firefox
 - Version 68.0.1
 - Chrome 
 - Version 77.0.3865.90

**Target Information (System that implant is running on):**
 - OS: Windows 7
 - Version SP 1
 - OS: Windows 10
  - Version 1903

**Additional context**
The Listener is HTTP over port 80 without SSL (see picture below) and the HttpProfile I'm using is an unmodified CustomHttpProfile.yaml.
<img width="1135" alt="Screen Shot 2019-09-24 at 11 51 16 AM" src="https://user-images.githubusercontent.com/55753368/65532687-e693a180-dec1-11e9-8eac-be97844cb239.png">
Thanks, sorry for dropping the format on the last ticket.

**Comment by cobbr** [comment]
Thanks for updating to this format @Ls094id! I really appreciate it. Could you also share the HttpProfile you are using?

**Comment by Ls094id** [comment]
Sure, the Listener is HTTP over port 80 without SSL (see picture below) and the HttpProfile I'm using is an unmodified CustomHttpProfile.yaml.
<img width="1135" alt="Screen Shot 2019-09-24 at 11 51 16 AM" src="https://user-images.githubusercontent.com/55753368/65532687-e693a180-dec1-11e9-8eac-be97844cb239.png">

I'll add this to the OP.

**Comment by cobbr** [comment]
Thanks @Ls094id .

If you are unable to share the ConnectAddress, it will make it harder to debug, but I definitely understand why you may be unable to. I'll try to reproduce with a generic ConnectAddress and get back to you.

Are you able to share this: Does your ConnectAddress containing any "odd" characters?

**Comment by Ls094id** [comment]
Afraid I can't share the ConnectAddress at this point. I can say that it is a standard public IPv4 at this stage of troubleshooting, however.

**Comment by Ls094id** [comment]
Did a lot of troubleshooting today - seems like the issue was my browser. I switched over to Edge (Microsoft Edge 42.17134.1.0) and it worked just fine. If you want, I can provide more details.

**Comment by cobbr** [comment]
@Ls094id Details would be great! I haven't been able to reproduce this.

**Comment by cobbr** [comment]
Glad you got it fixed @Ls094id! I still haven't been able to reproduce this, so closing for now. If anyone runs into this problem again, let me know and I will re-open.

**Comment by ll3N1GmAll** [comment]
I too am receiving this "illegal characters in path" error on the following launchers: binary & msbuild. I am using a standard 192.168.1.x private IP for Covenant. I am also using the default unmodified CustomHttpProfile listener. However, I am not using a browser for anything other than to pull down the files to the target for testing. I've used edge and IE to download them; but I don't think that is relevant.

**Comment by afsheen07** [comment]
@Ls094id Can please you provide more details? I have tried every browser and it's still giving me this error..
