### ISSUE TITLE
[Bug] Assembly Parameter Count Mismatch

### ISSUE THREAD

**Issue by Pickfordmatt** [cobbr/Covenant#71]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
I'm trying to run a C# executable file from a grunt, i'm expecting this to work similar to execute-assembly within Cobalt Strike, apologies if that is not the intention.

**To Reproduce**
1. Deploy a grunt
2. Click on tasks > assembly
3. Select the C# executable

**Expected behavior**
I expected the executable to pop a blank WinForm of the same .NET version.

**Screenshots**
![encodedassembly](https://user-images.githubusercontent.com/3343862/65535287-05615a80-def9-11e9-879b-d6c88f2c7210.png)

**Covenant Server Information:**
 - OS: Ubuntu 18
 - Docker or Native: Docker

**Browser Information:**
 - Browser Chrome
 - Version 76.0.3809.132

**Target Information (System that implant is running on):**
 - OS: Windows 10
 - Version Microsoft Windows NT 6.2.9200.0

Many thanks,
Matt

**Comment by Pickfordmatt** [comment]
Just wanted to add that if you run an entirely console based exe it work fine.

**Comment by cobbr** [comment]
@Pickfordmatt Are you able to share the code of the Assembly you are trying to execute?

My guess is that your `Main()` function does not accept any arguments. The Assembly task expects the main function to accept a `string[]` like `Main(string[] args)` to pass in your parameters.

**Comment by Pickfordmatt** [comment]
Yep can do, it’s a completely empty WinForm. What’s the best way to share? You’re correct there’s no arguments within the main function.

**Comment by Pickfordmatt** [comment]
@cobbr Sure! I've just included the args and the same error happened again, its a C# WinForm for reference.

`using System;
using System.Collections.Generic;
using System.Linq;
using System.Windows.Forms;

namespace blankwinform
{
    static class Program
    {
        /// <summary>
        /// The main entry point for the application.
        /// </summary>
        [STAThread]
        static void Main()
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new Form1());
            string[] args;
            
        }
    }
}
`

**Comment by cobbr** [comment]
Hey @Pickfordmatt , your Main function still doesn't accept a string[] argument. You need something like `static void Main(string[] args)`

**Comment by Pickfordmatt** [comment]
I'm an idiot - that works thank you!

**Comment by cobbr** [comment]
Great! Glad it's working 🙂
