### ISSUE TITLE
[Bug] SharpUp - NullReferenceException

### ISSUE THREAD

**Issue by rasta-mouse** [cobbr/Covenant#74]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
Commandline arguments for SharpUp are not required.  However, running the SharpUp Task from the UI without an arg results in a `NullReferenceException` in `GruntTaskingController.cs`.

The Stack Trace highlights:
```c#
command += " /" + tasking.GruntTask.Options[i].Name.ToLower() + ":\"" + tasking.Parameters[i].Replace("\"", "\\\"") + "\"";
```

Entering a garbage string is a temporary workaround since SharpUp only looks for the string `audit`.

Issuing the SharpUp command from the CLI works as expected.

EDIT:  I also notice the Assembly Task has the same bug.

**To Reproduce**
1. `Grunts` > `[Grunt Name]` > `Task`
2. Select `SharpUp` from the menu
3. Click `Task`

**Expected behavior**
The Task should execute.

**Screenshots**
![image](https://user-images.githubusercontent.com/7346521/65590651-0dfe7300-df83-11e9-95ea-8dd15ae682e9.png)

![image](https://user-images.githubusercontent.com/7346521/65591038-b14f8800-df83-11e9-8aa9-5515f73d311f.png)

![image](https://user-images.githubusercontent.com/7346521/65591089-c62c1b80-df83-11e9-8d1c-a7e8227a9639.png)

**Covenant Server Information:**
 - OS: Kali Linux Rolling 2019.4
 - Docker or Native: Native

**Browser Information:**
 - Browser: Chrome
 - Version: 77.0.3865.90 (Official Build) (64-bit)

**Target Information (System that implant is running on):**
 - OS: Windows 10
 - Version: 1809 (Build 17763.737)

**Comment by cobbr** [comment]
Fixed in f434ad5476ffd5113342ece1fc299e4567b4baf3

Thanks @rasta-mouse !!
