### ISSUE TITLE
[Bug|Feature Request] Error creating listener

### ISSUE THREAD

**Issue by LIZySARA** [cobbr/Covenant#76]
**Feature Request or Bug**
Feature Request | Bug

**Expected behavior**

**Screenshots**
<img width="1389" alt="Screenshot at Sep 26 01-01-16" src="https://user-images.githubusercontent.com/22563762/65643221-d2eb5680-dff9-11e9-83fe-8c99c4ea9113.png">

**Covenant Server Information:**
 - Docker or Native: [e.g. Native] Native

**Browser Information:**
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22]  Version 77.0.3865.90 

**Target Information (System that implant is running on):**
 - OS: [e.g. iOS8.1]  macOS mojave 10.14.6

**Additional context**
Why this error?

**Comment by cobbr** [comment]
Hey @LIZySARA , could you fill out the information in the issue template? This would really help me to diagnose the issue! Thanks!

**Comment by cobbr** [comment]
I think I've realized what's going on here. @LIZySARA  You must click "Generate" before hosting! Have you generated the launcher?

**Comment by LIZySARA** [comment]
@cobbr  Generate the launcher before the heberger? I do not understand you can ilustrate in capture please?

**Comment by cobbr** [comment]
@LIZySARA Sure! It's illustrated on this page of the wiki: https://github.com/cobbr/Covenant/wiki/Launchers

You'll need to click on that Generate button in the Generate tab before Hosting the launcher.

**Comment by cobbr** [comment]
@LIZySARA Closing for now. If you continue to experience issues, we can re-open.
