### ISSUE TITLE
[Bug] ImpersonateProcess Task is pointing to ImpersonateUser code

### ISSUE THREAD

**Issue by rasta-mouse** [cobbr/Covenant#77]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
In `DbInitializer.cs` the ImpersonateProcess Task is pointing to ImpersonateUser code.
https://github.com/cobbr/Covenant/blob/master/Covenant/Core/DbInitializer.cs#L999

**Comment by cobbr** [comment]
Nice catch! Fixed in 8afc59820a208a7e15544e95a32dc5a87ef4e233
