### ISSUE TITLE
[Bug] ImpersonateProcess Task converts PID to int rather than uint

### ISSUE THREAD

**Issue by rasta-mouse** [cobbr/Covenant#79]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
`ImpersonateProcess` in SharpSploit [expects](https://github.com/cobbr/SharpSploit/blob/master/SharpSploit/Credentials/Tokens.cs#L98) a `UInt32` but the ImpersonateProcess Task in Covenant [parses](https://github.com/cobbr/Covenant/blob/master/Covenant/Data/Tasks/CSharp/ImpersonateProcess.task#L13) the PID to an `int`.

This causes the Task to throw the following error:
```
CompilerException: CompilationErrors: 
(14,42): error CS1503: Argument 1: cannot convert from 'int' to 'uint'
```

**To Reproduce**
1. `Grunt` > `<GruntName>` > `Task`
2. `ImpersonateProcess`
3. Enter a PID and go

**Expected behavior**
The Task should attempt to impersonate the target process.

**Covenant Server Information:**
 - OS: Kali Linux 2019.4
 - Docker or Native: Native

**Browser Information:**
 - Browser: Chrome
 - Version: 77.0.3865.90 (Official Build) (64-bit)

**Target Information (System that implant is running on):**
 - OS: Windows 10
 - Version: 1809 (Build 17763.1)

**Comment by cobbr** [comment]
Nice catch! Fixed in 8afc59820a208a7e15544e95a32dc5a87ef4e233
