### ISSUE TITLE
Can not generate file

### ISSUE THREAD

**Issue by pasoles** [cobbr/Covenant#8]
Hi guyz 

Probably I am doing something wrong but I can not generate the files that the launchers require.
For example when I try to generate an hta file I type "Write test.hta", I get an output without errors [*] Wrote MshtaLauncher's hta to: "/app/Data/test.hta", but I can not locate the file.

Any suggestions??

Thanks

**Comment by notonlybytes** [comment]
the file is located inside the docker container. To access it use something similar to:
`# docker cp <containerid>:/app/Data/test.hta .`
in your case most likely
`# docker cp elite:/app/Data/test.hta .`

**Comment by pasoles** [comment]
Thank you very much

**Comment by cobbr** [comment]
Thanks @notonlybytes, that is correct.

If you follow the instructions in the Elite readme: https://github.com/cobbr/Elite/blob/master/README.md

It has you startup docker in a way that creates a shared `Data` folder, so this is mirrored between your docker host and container.
