### ISSUE TITLE
[Bug] Cannot use same Url for Hosted files on multiple Listeners

### ISSUE THREAD

**Issue by rasta-mouse** [cobbr/Covenant#82]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
It seems that you are unable to host files with the same Url on more than one Listener (even deleted ones).

**To Reproduce**
1. Clone Covenant.
2. Create a Listener.
3. Generate any Launcher (e.g. PowerShell) and Host is at `/Grunt.ps1`.
4. Confirm `/Grunt.ps1` is hosted on the Listener.
5. Delete the Listener.
6. Create a new Listener.
7. Generate the same Launcher as step 3 and Host it with the same Url (`/Grunt.ps1`).
8. `/Grunt.ps1` will not be Hosted.

**Expected behavior**
`/Grunt.ps1` should be hosted on the second Listener.

**Screenshots**
n/a

**Covenant Server Information:**
 - OS: Kali Linux Rolling 2019.4
 - Docker or Native: Native

**Browser Information:**
 - Browser: Chrome
 - Version: 77.0.3865.90 (Official Build) (64-bit)

**Target Information (System that implant is running on):**
n/a

**Additional context**
n/a

**Comment by cobbr** [comment]
Fixed in 5e118bd727e0564deb929bc5f3fc18fdae287eba
Thanks @rasta-mouse!
