### ISSUE TITLE
[Bug] Loop Exception: System.Net.WebException

### ISSUE THREAD

**Issue by rasta-mouse** [cobbr/Covenant#83]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
When executing Tasks (e.g. Seatbelt or Assembly) without Parameters, the Grunt throws the following error.

```
Loop Exception: System.Net.WebException The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at GruntExecutor.HttpMessenger.Read()
   at GruntExecutor.TaskingMessenger.ReadTaskingMessage()
   at GruntExecutor.Grunt.Execute(String CovenantURI, String CovenantCertHash, String GUID, Aes SessionKey)
```

**To Reproduce**
1. Launch a new Grunt
2. `Grunts` > `[Grunt Name]` > `Task` > `Seatbelt`
3. Leave `Command` field empty
4. Click `Task` button

**Expected behavior**
Seatbelt should be executed without arguments, and therefore [print its Usage](https://github.com/GhostPack/Seatbelt/blob/master/Seatbelt/Program.cs#L6916-L6920).

**Screenshots**
![image](https://user-images.githubusercontent.com/7346521/65829362-c5a1c680-e29c-11e9-8e10-a84c3245cce5.png)

![image](https://user-images.githubusercontent.com/7346521/65829372-dc481d80-e29c-11e9-995b-f3b290bd9bc6.png)

**Covenant Server Information:**
 - OS: Kali Linux Rolling 2019.4
 - Docker or Native: Native

**Browser Information:**
 - Browser: Chrome
 - Version: 77.0.3865.90 (Official Build) (64-bit)

**Target Information (System that implant is running on):**
 - OS: Windows 10
 - Version: 1809 (Build 17763.737)

**Additional context**
n/a

**Comment by cobbr** [comment]
Fixed in 2a9f7524ba23846000f44908e75c7ef39ec67613
Thanks @rasta-mouse!
