### ISSUE TITLE
[Feature Request] Have listener only allow one Grunt with same ip (No duplicates)

### ISSUE THREAD

**Issue by NotoriousRebel** [cobbr/Covenant#85]
**Feature Request or Bug**
Feature Request 

**Describe the feature request or bug**
This feature would make it so if you already have a Grunt with the powershell
launcher on a specific listener and take for example you have a schedule task 
that runs when the user logs in. That would mean when the user logs in and 
executes the powershell command that starts a new Grunt the server would
first check if a Grunt under that ip address, if same listener, and if same launcher.
If all three of those conditions are met then a new Grunt is not started up.

**Additional context**
The reason why this feature would be great is because take for example
you have a lot of persistence on 45 Windows Boxes. If they all login and just one of your persistence mechanisms is triggerred a new Grunt is created. When this happens
over and over again this crashes the server. With this feature the server would not crash as there would only be one Grunt associated with each ip address, listener, and launcher.

**Comment by cobbr** [comment]
Hey @NotoriousRebel I think the recommended solution here is going to be creating your own payload that first checks for another running Grunt. This is fairly easy to do by modifying an `ImplantTemplate`.

There's many circumstances under which you *would* want multiple Grunts on the same machine, so I don't think this would be a good thing to build into the default ImplantTemplate.

**Comment by NotoriousRebel** [comment]
@cobbr To clarify what I mean there are 100% cases where you would want multiple Grunts that is not the problem. The problem is when you have numerous boxes that are calling back to you. When you have a lot of persistence mechanisms that all call back it overwhelms the server and it crashes. It would be cool if you could perhaps set a limit of the number of Grunts with the same ip and are created with the same launcher. For example for this listener if the same ip calls back and is the powershell launcher there can only be 2 powershell callbacks, etc.

**Comment by cobbr** [comment]
@NotoriousRebel If the server is being overwhelmed and crashing, that's an issue we would want to look into. Has this happened to you and can you provide an example?

If I looked into this feature, it's not something I'd want to implement server-side. In my opinion, the implant should decide whether to quit or not without reaching out to the server. Which is why I think this is better handled with a custom ImplantTemplate.

For example, the server has no idea what kind of launcher is calling back. It collects process name information, but what if you have an ImplantTemplate that is migrating processes?

**Comment by rasta-mouse** [comment]
My two cents is that this should be dealt with by the operator.  IMO the tactic of ramming 40 1-hour scheduled tasks across an environment is just bad and the framework should need to deal with that for you.

**Comment by NotoriousRebel** [comment]
@rasta-mouse yeah it's kind of my fault 😅. I automated the deployment of [SharPersist](https://github.com/fireeye/SharPersist) in PowerShell and it would be fine if there was just maybe 1 or 2 boxes. But for what I was using it for was across around 60 boxes so it crashed the server numerous times as more and more Grunts were spawned.

**Comment by NotoriousRebel** [comment]
Maybe a low priority of being able to specify a number of Grunts that can call back with the same ip, lancher, and same listener.

**Comment by cobbr** [comment]
@NotoriousRebel Sounds like you have done more load testing on Covenant than I have 🙂 

I'll add load testing to my to-do list. There's no reason Covenant shouldn't be able to handle 100+ active Grunts, though there will likely be a higher memory requirement.

**Comment by NotoriousRebel** [comment]
@cobbr how I did it was with 60 windows boxes did a powershell launcher on all of them as well as the autodeployment of sharpersist which meant a lot of callbacks that eventually crashed the server.

**Comment by cobbr** [comment]
I'll plan to do some load testing. For now, I don't plan to implement this kind of feature, and will leave it to the operator to maintain control of their own implants and persistence mechanisms.
