### ISSUE TITLE
[Feature Request] Incorporate more LOLBAS for launchers. 

### ISSUE THREAD

**Issue by NotoriousRebel** [cobbr/Covenant#86]
**Feature Request or Bug**
Feature Request 

**Describe the feature request or bug**
The incorporation of more Living Off The Land Binaries and Scripts [(LOLBAS)](https://github.com/LOLBAS-Project/LOLBAS)
for launchers.

**Expected behavior**
Same functionality as any other launcher.

**Additional context**
This would be great as currently the powershell, regsvr32, and msbuild launchers all get caught by Windows Defender. (Only tested these, did not test other launchers) With the incorporation of more LOLBAS this would hopefully mean not getting caught by windows defender and regardless may be harder for blue teamers to find. As something running powershell.exe will stand right out but maybe not HH.exe, etc. If you wanted to take it one step further a task could be determing what LOLBAS exist on a system and if they exist have another task that would be for a LOLBAS that exists on the system create a payload for it and execute it. Although, that may be fairly complex.

**Comment by cobbr** [comment]
@NotoriousRebel I don't think we will be adding many more Launcher types, unless you have a specific request. It's already getting a bit cumbersome to maintain the ones currently implemented.

I should add this to the Covenant wiki somewhere, but the official "AV evasion" policy for Covenant payloads is going to be something like this:

As an open source project, default Covenant launchers and payloads *will* and *should* be signatured by AV vendors. Covenant does not attempt to play a cat and mouse game with AV vendors. It is the operator's responsibility to take Covenant payloads and customize them to avoid detection.

**Comment by cobbr** [comment]
Closing this for now. I'll plan to update the Covenant wiki with an official stance on AV Evasion.

If you have a **specific** request for a new type of launcher, we can evaluate the request and re-open this issue.
