### ISSUE TITLE
[Bug] WMIGrunt adds an extraneous "powershell" string

### ISSUE THREAD

**Issue by rasta-mouse** [cobbr/Covenant#89]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
The `WMIGrunt` Task adds an extraneous `powershell` string to the PowerShell Launcher, which causes execution to fail.

**To Reproduce**
1. `Grunts` > `[Grunt Name]` > `Task`
2. `WMIGrunt`
3. Enter `PowerShell` for Launcher (and fill in details required for your test env)
4. Click `Task`
5. See `Taskings` output

**Expected behavior**
A new Grunt should activate.

**Screenshots**
![image](https://user-images.githubusercontent.com/7346521/65864909-86da4200-e36a-11e9-866d-2187823fb7e0.png)
![image](https://user-images.githubusercontent.com/7346521/65865344-2bf51a80-e36b-11e9-85f3-c3b264afaf4c.png)

**Covenant Server Information:**
 - OS: Kali Linux Rolling 2019.4
 - Docker or Native: Native

**Browser Information:**
 - Browser: Chrome
 - Version: 77.0.3865.90 (Official Build) (64-bit)

**Target Information (System that implant is running on):**
 - OS: Windows 10
 - Version: 1809 (Build 17763.737)

**Additional context**
n/a

**Comment by rasta-mouse** [comment]
@cobbr I think a simple `split.RemoveAt(0);` would fix this?

**Comment by cobbr** [comment]
Fixed in 5854cee9f814bf735448ea95dfc9fb12c3f1a75b

Thanks @rasta-mouse!
