### ISSUE TITLE
Trouble with launching with docker windows 10 WSL [REVOLVED]

### ISSUE THREAD

**Issue by LIZySARA** [cobbr/Covenant#9]
Hi, 

`~/Covenant/Covenant# docker build -t covenant .
ERRO[0000] failed to dial gRPC: cannot connect to the Docker daemon. Is 'docker daemon' running on this host?: dial unix /var/run/docker.sock: connect: no such file or directory
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

**Comment by panagioto** [comment]
Hi LIZySARA

Ensure the docker service is running.
`service docker start`

**Comment by LIZySARA** [comment]
Thx but I already made this command and I still have the same error
