### ISSUE TITLE
[Bug] "while true" functions never return

### ISSUE THREAD

**Issue by rasta-mouse** [cobbr/Covenant#94]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
Functions such as `Rubeus harvest` and `Rubeus monitor` drop into `while (true)` loops.  Grunt Tasks that execute these never flush the console output to the Task output and there's no ability to terminate the assembly to force it to do so.

The Task status remains as `Tasked` indefinitely.

Furthermore, this seems to cause SMB Grunts to enter a `Lost` status.

**To Reproduce**
1. Go to `Grunts` > `[Grunt Name]` > `Task`.
2. Select the `Rubeus` Task.
3. Enter `monitor` in the Command box.
4. Click `Task`.

**Expected behavior**
The Task to receive data continuously without needing the Task to complete.
A job system so these types of Assembly / PowerShell functions can be terminated.

**Screenshots**
![image](https://user-images.githubusercontent.com/7346521/66109980-ad43eb80-e5bd-11e9-9f33-bfba432a5334.png)

**Covenant Server Information:**
 - OS: Kali Linux Rolling 2019.4
 - Docker or Native: Native

**Browser Information:**
 - Browser: Chrome
 - Version: 77.0.3865.90 (Official Build) (64-bit)

**Target Information (System that implant is running on):**
Tested with `Windows 10 1809 (17763.737)` and `Server 2016 1607 (14393.2941)`.

**Additional context**
n/a

**Comment by cobbr** [comment]
Good catch @rasta-mouse. The answer to this probably going to be "iterative" output, which is on the to-do list.

**Comment by cobbr** [comment]
Addressed with streaming output feature in v0.6 👍
