### ISSUE TITLE
[Bug] Cannot chain SMB Grunts

### ISSUE THREAD

**Issue by rasta-mouse** [cobbr/Covenant#95]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
I'm unable to connect to an SMB Grunt from another SMB Grunt.
`HTTPGrunt => SMBGrunt => SMBGrunt`.

The `Connect` Task returns the following error.

```
Task Exception: Access to the path is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Pipes.NamedPipeClientStream.Connect(Int32 timeout)
   at GruntExecutor.SMBMessenger..ctor(String Hostname, String PipeName, Int32 Timeout)
   at GruntExecutor.TaskingMessenger.Connect(String Hostname, String PipeName)
   at GruntExecutor.Grunt.TaskExecute(TaskingMessenger messenger, GruntTaskingMessage message)
```

I've tried using different credentials and pipe names.

**To Reproduce**
1. Execute an `HTTPGrunt` on `Host1`.
2. Execute an `SMBGrunt` on `Host2`.
3. Connect from `Host1` to `Host2`.
4. Execute an `SMBGrunt` on `Host3`.
5. `Connect` from `Host2` to `Host3`.

**Expected behavior**
For the SMBGrunt to connect to the second SMBGrunt.

**Screenshots**
n/a

**Covenant Server Information:**
 - OS: Kali Rolling 2019.4
 - Docker or Native: Native

**Browser Information:**
 - Browser: Chrome
 - Version: 77.0.3865.90 (Official Build) (64-bit)

**Target Information (System that implant is running on):**
Tested with `Windows 10 1809 (17763.737)`, `Server 2016 1607 (14393.2941)` and `Server 2012 R2`

**Additional context**
I can connect to `Host3` from `Host1`.

**Comment by rasta-mouse** [comment]
This just happened to work when I tried linking multiple SMB Grunts running as SYSTEM.  Seems there's some other nuance with the issue above that I'm not quite sure of yet.

**Comment by cobbr** [comment]
@rasta-mouse If you are able to reproduce the issue, it may help to provide a portion of the data model when you encounter the issue. Providing the results of the `GET /api/grunts` API when the issue is encountered.

I'm wondering if this has to do with disconnecting a parent/child relationship, connecting to a new Grunt at the some location, or something like that.

**Comment by rasta-mouse** [comment]
Could be, I did have a lot of Grunts flying around at the time.  Feel free to close this and I'll open a new one if I run into it again.

**Comment by rasta-mouse** [comment]
@cobbr multiple SMB Grunts on the same machine certainly seems to be a problem.

**Comment by cobbr** [comment]
@rasta-mouse How so? I do this often when testing.

**Comment by rasta-mouse** [comment]
I have two hosts.

- `Host 1` has an HTTP Grunt running.
- I execute an SMB Grunt on `Host 2` and `connect` to it from `Host 1` fine.
- If I execute a second SMB Grunt on `Host 2`, it can take a couple of tries before I can connect to it (from `Host 1`).  The task says it's connected successfully, but it won't appear in the Grunt list.
- Then if I `kill` one of the SMB Grunts it exits ok, but the second SMB Grunt enters a `Lost` state, even though the process still appears to be running on the target.
- If I try to `connect` back to the SMB Grunt again from `Host 1`, the task says successful but it doesn't come out of its `Lost` state and it won't respond to Tasks.

Repeat the setup.
- HTTP Grunt on `Host 1`, SMB Grunt on `Host 2` & `connect` the two.
- Execute a second SMB Grunt on `Host 2`
- `Connect` to the new SMB Grunt from the other SMB Grunt already running on `Host 2`.  The task says successful but the existing SMB Grunt enters a `Lost` state.  Both processes are still running on the target.
- Sometimes I can reconnect back to the SMB Grunts on `Host 2` from `Host 1`, but this also seems randomly hit and miss.

But this is only when I use the same PipeName across all the SMB Grunts.  If I use different PipeNames for the Grunts running on the same machine it seems to behave as it should.  Is that consistent with your experience?

**Comment by cobbr** [comment]
@rasta-mouse Ahh, yeah that's as expected. The SMB Grunt is a **bind** connection. You can only have 1 SMB Grunt per pipename per machine. You'll need a new payload with a new pipe name configured to have more than one SMB Grunt on a single machine.

**Comment by rasta-mouse** [comment]
Just me being dumb as usual 🙂 I haven't been able to reproduce the original error I posted so I'm closing this for now.

**Comment by cobbr** [comment]
@rasta-mouse Nah, not dumb at all 🙂
