### ISSUE TITLE
[Bug] Empty response from server

### ISSUE THREAD

**Issue by bkaraceylan** [cobbr/Covenant#96]
**Feature Request or Bug**
Bug

**Describe the feature request or bug** 
Covenant web server returns nothing.

**To Reproduce**
1. dotnet build
2. dotnet run
3. curl 127.0.0.1:7443
4. curl: (52) Empty reply from server
or
1. sudo docker run -d --name covenant -v /home/adm/mycontainers/Covenant/Covenant/Data:/app/Data covenant
2. curl 172.17.0.2:7443 
3.  curl: (52) Empty reply from server

**Expected behavior** 
Expected to reach the greeting page.

**Covenant Server Information:**
 - OS: Ubuntu 18.04.3 LTS
 - Docker or Native: Both

**Browser Information:**
 - Curl, Firefox, Chrome
 - Latest

**Comment by cobbr** [comment]
@bkaraceylan You are missing some key setup steps for Docker installation. Please refer to the Wiki for setup: https://github.com/cobbr/Covenant/wiki/Installation-And-Startup

**Comment by cobbr** [comment]
Further, I would advise **not** using Docker unless you are fairly familiar with how it works.

**Comment by bkaraceylan** [comment]
I skipped the docker build command and I did not map the ports to test it locally. Mapping the ports and accessing through the public ip produces the same result. My docker network is fine and the app is running in the container. Not exposed or closed ports will return a connection error, not an empty response. However, I don't think this is docker related since building and running with dotnet-sdk-2.2 still produces the same result.

**Comment by cobbr** [comment]
@bkaraceylan Seems to be working fine for me.

![Screen Shot 2019-10-07 at 9 43 32 AM](https://user-images.githubusercontent.com/8904306/66321974-03c76780-e8e7-11e9-8617-423893b3c8b9.png)

Your command in the issue do not match the commands in the setup guide. Did you use this command: `$ ~/Covenant/Covenant > docker run -it -p 7443:7443 -p 80:80 -p 443:443 --name covenant -v </absolute/path/to/Covenant/Covenant/Data>:/app/Data covenant`

The port parameters are required.

**Comment by bkaraceylan** [comment]
Oh I've just realized the exposed port is https. I was trying to access through http... Sorry for taking your time.

**Comment by cobbr** [comment]
No worries @bkaraceylan! Glad you got it working. 🙂 

Sorry I assumed it was a Docker setup mistake. I just have nightmares about debugging Docker issues lol 😛

**Comment by bkaraceylan** [comment]
I can only imagine :) Keep up the good work mate!
