### ISSUE TITLE
[Feature Request] Do not rename the old Grunt

### ISSUE THREAD

**Issue by c0me0nb0y** [cobbr/Covenant#97]
**Feature Request**
Can you start such a branch so that the ID of the same machine remains unchanged when it goes online again? Thank you!

**Describe the feature request**
I have Requested this feature in `https://github.com/cobbr/Covenant/issues/64`, and you closed it.
I think you did not see what I replied since I replied so late. My Bad!

My original reply is as follows. 

---------
Now let's assume such a situation. I controlled three machines and renamed them A, B, C with detailed annotations. And I added persistence to them.
One day, three machines restarted, I want to distinguish them, only can rely on the previous IP, user name and other information, and then rename the 3 grunts, re-annotate them, and delete the previous grunts.
This is troublesome.

Can you start such a branch so that the ID of the same machine remains unchanged when it goes online again? Thank you!

I'm not familiar with C # and asp. So if you don't like the changes above, can you give me some suggestions? In fact, I've already started to do this. I'm just having a headache with the asynchronous communication of C#, and I haven't found out how the ID of the server is generated. And I cannot compile it in visual studio, so I don't know how to debug it.

Look forward to your reply. I would appreciate it if you could improve it or give me some suggestions.

**Comment by c0me0nb0y** [comment]
Thank you. Maybe I could try it myself.

**Comment by cobbr** [comment]
Best of luck @c0me0nb0y, that will be an undertaking, feel free to ping me with any questions that come up. And also let me know if you come up with a workable solution 🙂
