### ISSUE TITLE
[Feature Request] How to debug it?

### ISSUE THREAD

**Issue by c0me0nb0y** [cobbr/Covenant#98]
**Feature Request**
I'd like to debug it in visual studio, but I compiled it failed, and I cannot fix it by myself.
Could you give me some advice? How you debug it?
Maybe I can join you to fix other bugs.

**Comment by rasta-mouse** [comment]
Select Covenant and hit "play" works fine for me
![image](https://user-images.githubusercontent.com/7346521/66414743-e6cb8b00-e9f1-11e9-998e-a1f0c7a7e714.png)

**Comment by c0me0nb0y** [comment]
Thank you both.
I thought I couldn't use visual studio before. Now I fix it.
